Repository CUBRID/cubrid, pull requests merged in 2018-08, with the labels that each got.

#1159 [CBRD-22218] Corrected log data by logging first and then removing fr…
  src/storage/file_manager.c
Labels: bug

#1160 [CBRD-22220] clears trace stats to reuse xasl clone
  src/query/query_executor.c
Labels: bug

#1161 [CBRD-22220] clears trace stats to reuse xasl clone (#1160)
  src/query/query_executor.c
Labels: bug

#1039 [CBRD-21673] Serialize the JSONs written on the disk
  src/base/memory_alloc.h
  src/base/memory_hash.c
  src/base/object_representation.h
  src/broker/cas_execute.c
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/compat/db_macro.c
  src/compat/db_value_printer.cpp
  src/compat/dbtype.h
  src/compat/dbtype_def.h
  src/compat/dbtype_function.h
  src/compat/dbtype_function.i
  src/executables/csql_result_format.c
  src/executables/load_object.c
  src/executables/loader.c
  src/object/object_domain.c
  src/object/object_primitive.c
  src/object/object_representation.c
  src/parser/parse_dbi.c
  src/query/arithmetic.c
  src/query/string_opfunc.c
  win/cubridcs/cubridcs.def
Labels: change disk image, enhancement, in progress

#1163 [CBRD-21524] fix bad merge
  src/base/system_parameter.h
Labels: bug

#1164 [CBRD-22227] fix overflow to init log buffer
  src/transaction/log_page_buffer.c
Labels: bug

#1165 [CBRD-22230] fixed to correctly refer to index_status
  src/object/schema_manager.c
Labels: bug

#1166 [CBRD-22228] fixed dropped fk reference
  src/object/class_object.c
Labels: bug

#1167 [CBRD-22236] fixed unhandled error of sm_stats_remove_online_index_stats
  src/object/schema_manager.c
Labels: bug

#1168 [CBRD-22232] [JSON]Cannot coerce value of domain "national character" to domain "json"
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/executables/loader.c
  src/object/object_domain.c
  src/parser/parse_dbi.c
  src/query/string_opfunc.c
Labels: bug

#1169 [CBRD-22226] [shell] Core dumped in db_json_serialize at src/compat/db_json.cpp:2945
  src/object/object_primitive.c
Labels: bug

#1170 [CBRD-22239] Fix UMR of dwb_flush_force
  src/storage/double_write_buffer.c
Labels: bug

#1172 [CBRD-22255] show index statement has Visible column
  src/parser/parser_support.c
  src/query/query_executor.c
Labels: enhancement, test case revise required

#1173 [CBRD-22257] keep error stack safe-guard for server mode only
  src/base/error_context.cpp
Labels: bug

#1174 [CBRD-22260] undoredo logging for initializing new pages
  src/storage/btree.c
  src/storage/extendible_hash.c
  src/storage/heap_file.c
  src/storage/system_catalog.c
  src/transaction/recovery.c
Labels: bug

#1151 [CBRD-22015] Query execution with commit
  src/base/xserver_interface.h
  src/broker/cas_execute.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_sr.c
  src/communication/network_interface_sr.h
  src/communication/network_sr.c
  src/compat/db_admin.c
  src/compat/db_query.c
  src/compat/db_vdb.c
  src/compat/dbi.h
  src/compat/dbi_compat.h
  src/connection/client_support.c
  src/executables/csql.c
  src/object/schema_manager.c
  src/object/schema_manager.h
  src/object/trigger_manager.c
  src/object/trigger_manager.h
  src/parser/parse_tree.c
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/parser.h
  src/parser/parser_support.c
  src/parser/query_result.c
  src/parser/semantic_check.c
  src/query/execute_statement.c
  src/query/query_list.h
  src/query/xasl_cache.c
  src/session/session.c
  src/session/session.h
  src/session/session_sr.c
  src/transaction/locator_cl.c
  src/transaction/lock_manager.c
  src/transaction/transaction_cl.c
  src/transaction/transaction_cl.h
  src/transaction/transaction_sr.c
  src/transaction/transaction_sr.h
  win/cubridcs/cubridcs.def
  win/cubridsa/cubridsa.def
Labels: enhancement

#1175 [CBRD-22266] expect allocated page for OLD_PAGE_DEALLOCATED
  src/storage/page_buffer.c
Labels: bug

#1176 [CBRD-22268] remove duplicate b-tree root page initialization
  src/storage/btree.c
Labels: bug

#1177 [CBRD-22272] class object might be decached
  src/object/schema_manager.c
Labels: bug

#1178 [CBRD-22273] server side auto-commit missed block_nowhere_statement p…
  src/query/execute_statement.c
Labels: bug

#1180 [CBRD-22277] fix worker pool stopping
  src/thread/thread_worker_pool.hpp
Labels: bug
