Repository CUBRID/cubrid, pull requests merged in 2018-03, with the labels that each got.

#1025 [CBRD-20757] remove convert_password from build
  src/executables/convert_password.c
  src/query/query_opfunc.c
  src/thread/thread.c
  util/CMakeLists.txt
Labels: refactoring

#1009 [CBRD-21842] Fix wake up strategy for remove log archives daemon
  src/transaction/log_manager.c
  src/transaction/log_page_buffer.c
Labels: bug, enhancement

#1026 [CBRD-21944] cas_main reload error manager
  src/broker/cas.c
Labels: bug

#1029 [CBRD-21948] skip dropped file notification during recovery
  src/query/vacuum.c
Labels: bug

#1028 [CBRD-21852] migrate log flush daemon thread to new API
  src/base/perf_monitor.c
  src/base/perf_monitor.h
  src/communication/network_interface_sr.c
  src/communication/network_sr.c
  src/query/query_executor.c
  src/query/vacuum.c
  src/session/session.c
  src/storage/page_buffer.c
  src/thread/thread.c
  src/thread/thread.h
  src/thread/thread_looper.cpp
  src/thread/thread_looper.hpp
  src/thread/thread_manager.cpp
  src/thread/thread_waiter.cpp
  src/thread/thread_waiter.hpp
  src/thread/thread_worker_pool.hpp
  src/transaction/boot_sr.c
  src/transaction/lock_manager.c
  src/transaction/log_manager.c
  src/transaction/log_manager.h
  src/transaction/log_page_buffer.c
Labels: refactoring

#1030 [CBRD-21524] reserve some error codes for JSON
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/base/error_code.h
  src/compat/db_json.cpp
Labels: refactoring

#1031 [CBRD-21951] fixes memory leak of "show index"
  src/query/query_executor.c
Labels: bug

#1032 [CBRD-21941] force wake up of remove log archives daemon
  src/transaction/log_manager.c
Labels: bug

#1027 [CBRD-21943] [Replication] communication channel
  cubrid/CMakeLists.txt
  src/communication/communication_channel.cpp
  src/communication/communication_channel.hpp
  src/connection/connection_defs.h
  src/connection/connection_sr.h
  src/connection/connection_support.c
  src/connection/connection_support.h
  unit_tests/CMakeLists.txt
  unit_tests/communication_channel/CMakeLists.txt
  unit_tests/communication_channel/test_main.cpp
Labels: enhancement, task

#1033 [CBRD-21952] flush pages directly on server stop
  src/transaction/log_page_buffer.c
Labels: bug

#1037 [CBRD-21953] system generated select for client-side update has column names as well as its value
  src/parser/parse_tree_cl.c
  src/parser/xasl_generation.c
Labels: bug

#1040 [CBRD-21960] fixed memory leak of "show columns"
  src/query/query_executor.c
Labels: bug

#1041 [CBRD-21941] apply old sleeping strategy for remove log archive daemon
  src/transaction/log_manager.c
Labels: bug

#1043 [CBRD-21966] Make locale based on %VS150COMCOMNTOOLS% for VS2017 v150
  locales/make_locale_x64.bat
Labels: enhancement

#1042 [CBRD-21799] replace lock-free circular queue
  src/base/base_flag.hpp
  src/base/lock_free.c
  src/base/lock_free.h
  src/base/lockfree_circular_queue.hpp
  src/executables/unittests_cqueue.c
  src/query/vacuum.c
  src/storage/page_buffer.c
  unit_tests/lockfree/test_cqueue_functional.cpp
  util/CMakeLists.txt
Labels: refactoring

#1046 [CBRD-21970] fix lfcq & vacuum
  src/base/lockfree_circular_queue.hpp
  src/query/vacuum.c
  unit_tests/lockfree/test_cqueue_functional.cpp
Labels: bug

#1045 [CBRD-21974] fix pt_make_val_list type missmatch
  src/compat/db_macro.c
  src/compat/dbtype.h
  src/parser/parse_dbi.c
  src/parser/parser.h
  src/parser/xasl_generation.c
Labels: bug, in progress

#1047 [CBRD-21975] Fix pgbuf_get_thread_waiting_for_direct_victim argument
  src/storage/page_buffer.c
Labels: bug

#1048 [CBRD-21976][Regression] make locale failed on Windows
  locales/make_locale_x64.bat
Labels: bug, enhancement

#1036 [CBRD-21956] migrate server request worker threads
  src/base/perf_monitor.c
  src/base/perf_monitor.h
  src/base/system_parameter.c
  src/communication/communication_channel.cpp
  src/communication/communication_channel.hpp
  src/communication/network_sr.c
  src/connection/server_support.c
  src/connection/server_support.h
  src/query/vacuum.c
  src/storage/external_sort.c
  src/storage/file_io.c
  src/storage/page_buffer.c
  src/thread/critical_section.c
  src/thread/thread.c
  src/thread/thread.h
  src/thread/thread_entry_task.cpp
  src/thread/thread_entry_task.hpp
  src/thread/thread_manager.cpp
  src/thread/thread_manager.hpp
  src/thread/thread_worker_pool.cpp
  src/thread/thread_worker_pool.hpp
  src/transaction/lock_manager.c
  src/transaction/lock_manager.h
  src/transaction/log_manager.c
  src/transaction/mvcc.c
  unit_tests/communication_channel/test_main.cpp
Labels: refactoring

#1044 [CBRD-21791] thread daemon statistics
  src/base/perf_monitor.c
  src/base/perf_monitor.h
  src/storage/page_buffer.c
  src/storage/page_buffer.h
  src/thread/thread.c
  src/thread/thread_daemon.cpp
  src/thread/thread_daemon.hpp
  src/thread/thread_looper.cpp
  src/thread/thread_looper.hpp
  src/thread/thread_waiter.cpp
  src/thread/thread_waiter.hpp
  src/transaction/lock_manager.c
  src/transaction/lock_manager.h
  src/transaction/log_manager.c
  src/transaction/log_manager.h
Labels: enhancement
