Repository CUBRID/cubrid, pull requests merged in 2018-12, with the labels that each got.

#1386 [CBRD-22611] do not accept numerics for json document arguments
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/base/error_code.h
  src/compat/db_json.cpp
  src/parser/func_type.cpp
Labels: bug

#1344 [CBRD-22523] JSON_TABLE csql crashed when path expression is empty
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/parser/semantic_check.c
  src/query/xasl_to_stream.c
Labels: bug

#1384 [CBRD-22586] Flush data volume header page at backup and checkpoint
  src/storage/disk_manager.c
  src/transaction/log_page_buffer.c
Labels: bug

#1390 [CBRD-22621] Handle interrupt at file_dealloc
  src/storage/extendible_hash.c
  src/storage/system_catalog.c
Labels: bug

#1388 [CBRD-22618] Fix invisible index during reorganize of partitions
  src/object/class_object.c
  src/object/class_object.h
  src/query/execute_schema.c
Labels: bug

#1383 [CBRD-22604] generic collation checking
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/parser/func_type.cpp
  src/parser/func_type.hpp
  src/parser/parse_tree.h
  src/parser/parser.h
  src/parser/parser_message.h
  src/parser/semantic_check.c
  src/parser/type_checking.c
Labels: refactoring

#1391 [CBRD-22624] Fix shared constraints with foreign keys
  src/object/schema_manager.c
  src/object/schema_template.c
  src/object/schema_template.h
Labels: bug

#1392 [APIS-779] implement isClosed() of CUBRIDResultSet and CUBRIDResultSe…
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSet.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSetWithoutQuery.java
Labels: bug

#1394 [APIS-771] Wrap a thrown UnsupportedOperationException in a SQLExcept…
  src/jdbc/cubrid/jdbc/driver/CUBRIDBlob.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDCallableStatement.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDDataSource.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDDatabaseMetaData.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDPreparedStatement.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSet.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSetMetaData.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSetWithoutQuery.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDStatement.java
Labels: bug

#1395 [APIS-779] implement isClosed() of CUBRIDResultSet and CUBRIDResultSe…
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSet.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSetWithoutQuery.java
Labels: bug

#1397 [CBRD-22628] Revert last PR and better handle shared constraints with online index
  src/object/schema_manager.c
  src/object/schema_template.c
  src/object/schema_template.h
Labels: bug

#1387 [CBRD-22618] Skip online and invisible indexes for query graph build
  src/optimizer/query_graph.c
Labels: bug

#1378 [CBRD-22536] change common type between json and string to string
  src/parser/type_checking.c
Labels: bug

#1400 [CBRD-22633] fix memory leak of #1397
  src/object/schema_manager.c
Labels: bug

#1389 [CBRD-22619] Fix Invisible indexes for rebuild
  src/object/schema_manager.c
  src/object/schema_manager.h
  src/query/execute_schema.c
Labels: bug

#1402 [CBRD-22620] Fixed some er_log_debug calls
  src/storage/btree_load.c
Labels: bug

#1399 [CBRD-22622] Migrate all JSON function from PT_EXPR to PT_FUNCTION
  src/compat/db_json.cpp
  src/object/object_primitive.c
  src/optimizer/query_graph.c
  src/optimizer/query_planner.c
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/func_type.cpp
  src/parser/func_type.hpp
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/parse_type.hpp
  src/parser/parser.h
  src/parser/parser_support.c
  src/parser/semantic_check.c
  src/parser/type_checking.c
  src/parser/xasl_generation.c
  src/query/arithmetic.c
  src/query/arithmetic.h
  src/query/fetch.c
  src/query/query_dump.c
  src/query/query_dump.h
  src/query/query_executor.c
  src/query/query_opfunc.c
  src/query/query_opfunc.h
  src/query/string_opfunc.c
  src/query/string_opfunc.h
  src/storage/storage_common.c
  src/storage/storage_common.h
Labels: bug, refactoring

#1398 [CBRD-22632] Better handling of statistics so that query optimizer doesn't pick an unavailable index
  src/object/class_object.c
  src/object/class_object.h
  src/object/schema_manager.c
  src/object/schema_manager.h
  src/object/schema_template.c
  src/optimizer/query_graph.c
  src/parser/name_resolution.c
  src/transaction/locator_sr.c
Labels: refactoring

#1403 [CBRD-22639] remove assertions for unknown function code
  src/storage/storage_common.c
Labels: bug

#1404 [CBRD-22643] fix json functions as identifiers
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
Labels: bug

#1405 [CBRD-22645] fix slip of #1399 on pt_is_const_expr_node
  src/parser/parse_tree_cl.c
Labels: bug

#1407 [CBRD-22640] update stats even though table has no index
  src/object/schema_manager.c
Labels: bug

#1406 [CBRD-22646] correct json_valid behavior
  src/parser/func_type.cpp
  src/query/arithmetic.c
Labels: bug

#1396 [CBRD-22540] Add support for json_path wildcards
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/parser/xasl_generation.c
  src/query/arithmetic.c
  src/query/scan_json_table.cpp
  src/query/string_opfunc.c
  src/query/string_opfunc.h
  src/query/xasl_to_stream.c
  src/xasl/access_json_table.cpp
  src/xasl/access_json_table.hpp
  src/xasl/xasl_stream.cpp
Labels: bug

#1408 [CBRD-22642] Set new error in case of partition created on a class in a hierarchy
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/base/error_code.h
  src/query/execute_schema.c
Labels: bug

#1410 [CBRD-22612] csql crash in db_json_array_shift_values
  src/compat/db_json.cpp
Labels: bug

#1411 [CBRD-22495] initialize json table scan properly
  src/query/scan_manager.c
  src/query/stream_to_xasl.c
Labels: bug

#1412 [CBRD-22647] fix memory leak of json_contains_path()
  src/query/arithmetic.c
Labels: bug

#1414 [CBRD-22652] do not update statistics on views
  src/object/schema_manager.c
Labels: bug

#1409 [CBRD-22354] Remove spam from server error log file
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/communication/network_interface_sr.c
  src/communication/network_sr.c
  src/storage/btree.c
  src/storage/double_write_buffer.c
  src/storage/es.c
  src/storage/es_common.h
  src/storage/es_posix.c
  src/storage/heap_file.c
  src/storage/page_buffer.c
  src/transaction/log_page_buffer.c
  src/transaction/log_writer.c
  src/transaction/replication.c
Labels: enhancement

#1415 [CBRD-22648] JSON_EXTRACT returned order does not match the input order
  src/compat/db_json.cpp
Labels: bug

#1416 [CBRD-22638] Consider compression when computes length of nchar varying
  src/object/object_primitive.c
Labels: bug

#1417 [CBRD-22658] Fix json_contains regressions
  src/compat/db_json.cpp
Labels: bug

#1418 [CBRD-22659] JSON csql crashed when insert json data with enable_string_compression=n
  src/object/object_representation.c
Labels: bug

#1225 [CBRD-22254] Loaddb server side error management
  cubrid/CMakeLists.txt
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  sa/CMakeLists.txt
  src/communication/network.h
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/communication/network_interface_sr.h
  src/communication/network_sr.c
  src/compat/dbi_compat.h
  src/executables/esql_symbol_table.c
  src/loaddb/load_common.cpp
  src/loaddb/load_common.hpp
  src/loaddb/load_db.c
  src/loaddb/load_db_value_converter.cpp
  src/loaddb/load_driver.cpp
  src/loaddb/load_driver.hpp
  src/loaddb/load_error_handler.cpp
  src/loaddb/load_error_handler.hpp
  src/loaddb/load_grammar.yy
  src/loaddb/load_lexer.l
  src/loaddb/load_manager.cpp
  src/loaddb/load_manager.hpp
  src/loaddb/load_sa_loader.cpp
  src/loaddb/load_sa_loader.hpp
  src/loaddb/load_scanner.hpp
  src/loaddb/load_semantic_helper.cpp
  src/loaddb/load_semantic_helper.hpp
  src/loaddb/load_server_loader.cpp
  src/loaddb/load_server_loader.hpp
  src/loaddb/load_session.cpp
  src/loaddb/load_session.hpp
  src/session/session.c
  src/session/session.h
  src/thread/thread_entry.cpp
  src/thread/thread_entry.hpp
Labels: enhancement

#1419 [CBRD-22664] Unexpected error returend when using json functions as identifiers.
  src/parser/csql_lexer.l
Labels: bug

#1420 [CBRD-22665] fix client memory leaks mainly json schema
  src/object/object_representation.c
  src/object/transform_cl.c
  src/transaction/boot_cl.c
Labels: bug
