Repository CUBRID/cubrid, pull requests merged in 2018-02, with the labels that each got.

#998 [CBRD-21842] migrate remove log archives daemon thread to new API
  src/thread/thread.c
  src/thread/thread.h
  src/transaction/log_page_buffer.c
Labels: refactoring

#999 [CBRD-21901] fix deadlock detection
  src/transaction/lock_manager.c
Labels: bug

#1000 [CBRD-21876] - Handle memory leaks in db_json_keys
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/query/string_opfunc.c
Labels: bug

#1001 [CBRD-21884] Crash for json_array_append in view
  src/query/string_opfunc.c
Labels: bug

#1002 [CBRD-21902] stop checkpoint daemon before log finalize enters in critical section
  src/transaction/log_impl.h
  src/transaction/log_manager.c
  src/transaction/log_page_buffer.c
Labels: bug

#1003 [CBRD-21897] fix to avoid deadlock of "show indexes"
  src/query/query_executor.c
  src/storage/statistics_sr.c
  src/storage/system_catalog.c
Labels: bug

#1004 [CBRD-21916] db_json_get_json_from_str returns null for an invalid json
  src/compat/db_json.cpp
Labels: bug

#1005 [CBRD-21883] Tokenize an SQL path string that's surrounded by double quotes
  src/compat/db_json.cpp
Labels: bug

#1006 [CBRD-21914] deregister worker in case of an early out from execute
  contrib/gdb_debugging_scripts/thread_tran.gdb
  src/thread/thread_worker_pool.hpp
Labels: bug

#1007 [CBRD-21841] optimize deadlock detection daemon task
  src/thread/thread_looper.hpp
  src/transaction/lock_manager.c
  src/transaction/lock_manager.h
Labels: enhancement

#1008 [CBRD-21903] Fix to delay initialization of log page buffer structures
  src/transaction/log_manager.c
  src/transaction/log_page_buffer.c
Labels: bug

#1010 [CBRD-21844] migrate session control daemon thread to new API
  src/session/session.c
  src/session/session.h
  src/thread/thread.c
  src/thread/thread.h
  src/transaction/log_page_buffer.c
Labels: refactoring

#1011 [CBRD-21846] migrate auto volume expansion daemon thread to new API
  src/storage/disk_manager.c
  src/thread/thread.c
  src/thread/thread.h
Labels: refactoring

#1013 [CBRD-21847] migrate log clock daemon thread to new API
  src/communication/network_interface_sr.c
  src/query/query_manager.c
  src/session/session.c
  src/storage/disk_manager.c
  src/thread/thread.c
  src/thread/thread.h
  src/transaction/lock_manager.c
  src/transaction/log_global.c
  src/transaction/log_impl.h
  src/transaction/log_manager.c
  src/transaction/log_manager.h
  src/transaction/log_page_buffer.c
  src/transaction/log_tran_table.c
  src/transaction/log_writer.c
Labels: refactoring

#1016 [CBRD-21524] fix ambiguous conditions
  src/object/set_object.c
Labels: bug

#977 [CBRD-21804] Separate error context management from thread
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/error_context.cpp
  src/base/error_context.hpp
  src/base/error_manager.c
  src/base/error_manager.h
  src/broker/broker.c
  src/broker/cas.c
  src/communication/network_sr.c
  src/connection/heartbeat.c
  src/executables/commdb.c
  src/executables/csql.c
  src/executables/load_object.c
  src/executables/loaddb.c
  src/executables/master.c
  src/executables/master_heartbeat.c
  src/executables/master_request.c
  src/executables/master_util.h
  src/executables/util_common.c
  src/executables/util_service.c
  src/object/authenticate.c
  src/parser/semantic_check.c
  src/query/execute_schema.c
  src/thread/critical_section.c
  src/thread/critical_section.h
  src/thread/thread.c
  src/thread/thread_entry.cpp
  src/thread/thread_entry.hpp
  src/thread/thread_entry_task.cpp
  src/thread/thread_manager.cpp
  src/transaction/boot_cl.c
  src/transaction/boot_sr.c
  src/transaction/locator_cl.c
  src/transaction/log_impl.h
  src/transaction/log_tran_table.c
Labels: bug, refactoring

#1017 [CBRD-21933] fixes a memory leak of query recompilation
  src/query/execute_statement.c
Labels: bug

#1019 [CBRD-21847] fix windows linker error for es.obj
  src/query/vacuum.c
  src/query/vacuum.h
  src/storage/es.c
  src/storage/es.h
  src/transaction/log_global.c
  src/transaction/log_impl.h
  src/transaction/log_manager.c
  src/transaction/recovery.c
Labels: bug

#1021 [CBRD-21937] disable error context/message logging
  src/base/error_context.cpp
  src/base/error_context.hpp
  src/base/error_manager.c
Labels: bug

#1022 [CBRD-21940] Fix reloading error manager for broker/cas
  src/base/error_manager.c
  src/communication/network_sr.c
  src/transaction/boot_cl.c
Labels: bug

#1018 [CBRD-21845] migrate check ha delay info daemon thread to new API
  src/base/error_manager.c
  src/connection/connection_defs.h
  src/connection/connection_error.h
  src/connection/server_support.c
  src/jsp/jsp_cl.c
  src/object/object_primitive.c
  src/thread/thread.c
  src/thread/thread.h
  src/transaction/log_manager.c
Labels: refactoring

#996 [CBRD-21887] Wrong result sets were returned by json_set
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/base/error_code.h
  src/compat/db_json.cpp
Labels: bug, in progress

#993 [CBRD-21889] Handle duplicate keys in json_keys
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/base/error_code.h
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/query/string_opfunc.c
Labels: bug, in progress

#1024 [CBRD-21848] [CBRD-21849] [CBRD-21850] [CBRD-21851] page flush daemons migration
  src/storage/page_buffer.c
  src/storage/page_buffer.h
  src/thread/thread.c
  src/thread/thread.h
  src/thread/thread_daemon.cpp
  src/thread/thread_daemon.hpp
  src/thread/thread_looper.cpp
  src/thread/thread_looper.hpp
  src/thread/thread_waiter.hpp
  src/transaction/boot_sr.c
  src/transaction/log_manager.c
Labels: refactoring
