Repository CUBRID/cubrid, pull requests merged in 2018-05, with the labels that each got.

#1074 [CBRD-22034] remove gcc 4.4.7 compatibility - test_worker_pool
  unit_tests/thread/test_worker_pool.cpp
Labels: refactoring

#1073 [CBRD-22008] no context task/daemons
  src/communication/stream_transfer_receiver.cpp
  src/communication/stream_transfer_sender.cpp
  src/query/vacuum.c
  src/session/session.c
  src/storage/page_buffer.c
  src/thread/thread_daemon.cpp
  src/thread/thread_daemon.hpp
  src/thread/thread_manager.cpp
  src/thread/thread_manager.hpp
  src/thread/thread_task.hpp
  src/transaction/lock_manager.c
  src/transaction/log_manager.c
  unit_tests/communication_channel/test_main.cpp
  unit_tests/transfer_channel/test_main.cpp
Labels: refactoring

#1075 [CBRD-22046] remove obsoleted css_Job_queue, thread_worker
  src/communication/network_sr.c
  src/connection/connection_sr.c
  src/connection/job_queue.h
  src/connection/server_support.c
  src/connection/server_support.h
  src/query/show_scan.c
  src/storage/external_sort.c
  src/storage/file_io.c
  src/thread/thread.c
  src/thread/thread.h
  src/thread/thread_entry_task.cpp
  src/thread/thread_worker_pool.hpp
  src/transaction/log_manager.c
  unit_tests/thread/test_worker_pool.cpp
Labels: refactoring

#1077 [CBRD-22053] remove obsoleted DIAG_DEVEL codes
  broker/CMakeLists.txt
  src/base/perf_monitor.c
  src/base/perf_monitor.h
  src/communication/network_interface_sr.c
  src/communication/network_sr.c
  src/query/query_executor.c
  src/storage/page_buffer.c
  src/transaction/boot_sr.c
  src/transaction/lock_manager.c
Labels: refactoring

#1076 [CBRD-22036] Improve performance of db_json_replace_token_special_chars
  src/compat/db_json.cpp
Labels: enhancement

#1080 [CBRD-22047] fix slow file header sanity checks stacking
  src/storage/file_manager.c
Labels: bug

#1078 [CBRD-22044] backupdb also allows a FIFO (named pipe) file
  src/executables/util_cs.c
  src/storage/file_io.c
Labels: enhancement

#1085 [CBRD-22079] remove cub_admin => cubridsa linking
  util/CMakeLists.txt
Labels: bug

#1086 [CBRD-22077] fix windows install
  win/CMakeLists.txt
Labels: bug

#1087 [CBRD-22082] check stop_talk and errors on read & queue
  src/connection/connection_sr.c
  src/connection/server_support.c
Labels: bug

#1088 [CBRD-22081] remove incorrect file_expand_to safe-guard
  src/storage/file_io.c
Labels: bug

#1081 [CBRD-22042] [HA] SBR Ad-hoc Client Implementation
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  src/base/process_util.c
  src/base/process_util.h
  src/compat/db.h
  src/compat/db_admin.c
  src/compat/db_admin.h
  src/executables/ddl_proxy_client.cpp
  src/executables/utility.h
  unit_tests/CMakeLists.txt
  unit_tests/ddl_proxy_client/CMakeLists.txt
  unit_tests/ddl_proxy_client/test_main.cpp
  util/CMakeLists.txt
Labels: enhancement, in progress

#1084 [APIS-771] Wrap a thrown UnsupportedOperationException in a SQLExceptio…
  src/jdbc/cubrid/jdbc/driver/CUBRIDBlob.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDCallableStatement.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDDataSource.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDDatabaseMetaData.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDPreparedStatement.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSet.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSetMetaData.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSetWithoutQuery.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDStatement.java
Labels: bug

#1090 [CBRD-22084] fix checking gcrypt was successfully loaded
  src/query/crypt_opfunc.c
Labels: bug

#1089 [CBRD-22087] set connection error when a client properly receives it f…
  src/connection/connection_cl.c
Labels: bug

#1091 [CBRD-22089] fix potential memory leak when a connections suffers fro…
  src/connection/connection_sr.c
Labels: bug

#1092 [CBRD-22083] safe-guard connection entry's transaction index
  src/communication/network_sr.c
  src/connection/client_support.c
  src/connection/connection_cl.c
  src/connection/connection_defs.h
  src/connection/connection_list_cl.c
  src/connection/connection_sr.c
  src/connection/connection_support.c
  src/connection/server_support.c
  src/transaction/boot_sr.c
Labels: bug

#1094 [CBRD-22091] protocol mismatches when zero size buffer is delivered
  src/communication/network_cl.c
  src/communication/network_interface_sr.c
  src/connection/connection_cl.c
Labels: bug

#1095 [CBRD-22093] fixes query execution also expects nil list_id
  src/communication/network_cl.c
Labels: bug

#1096 [CBRD-22095] clearing deadlock victim also resets tran_abort_reason
  src/transaction/lock_manager.c
Labels: bug

#1098 [CBRD-22064] force thread entry wakeup on shutdown
  src/thread/thread_entry.cpp
Labels: bug

#1093 [CBRD-22074] [HA] cluster modifications for replication channels
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/communication/network_sr.c
  src/connection/connection_defs.h
  src/connection/heartbeat.c
  src/connection/heartbeat.h
  src/connection/server_support.c
  src/connection/server_support.h
  src/connection/tcp.c
  src/connection/tcp.h
  src/connection/wintcp.c
  src/connection/wintcp.h
  src/executables/master.c
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
  src/executables/master_request.c
  src/executables/master_request.h
  src/executables/util_common.c
Labels: enhancement, in progress

#1103 [CBRD-22101] fix compile for gcc 8.1.0
  src/heaplayers/sanitycheckheap.h
Labels: bug

#1104 [CBRD-22104] use interrupt reason on shutdown threads
  src/thread/thread_entry.cpp
Labels: bug

#1102 [CBRD-22103] [HA] [Regression] Core dumped in hb_resource_job_send_master_hostname
  src/executables/master_heartbeat.c
Labels: bug

#1099 [CBRD-22012] vacuum worker should expect interrupted error during shutdown
  src/query/vacuum.c
Labels: bug

#1101 [CBRD-22106] resource tracking
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/fileline_location.cpp
  src/base/fileline_location.hpp
  src/base/memory_alloc.c
  src/base/memory_alloc.h
  src/base/perf_def.hpp
  src/base/process_util.c
  src/base/resource_tracker.cpp
  src/base/resource_tracker.hpp
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/broker/cas_execute.c
  src/communication/network_sr.c
  src/connection/server_support.c
  src/executables/master_heartbeat.h
  src/executables/unittests_snapshot.c
  src/query/filter_pred_cache.c
  src/query/list_file.c
  src/query/list_file.h
  src/query/query_executor.c
  src/query/query_manager.c
  src/query/stream_to_xasl.c
  src/query/xasl.h
  src/storage/btree_load.c
  src/storage/page_buffer.c
  src/storage/statistics_sr.c
  src/thread/critical_section.c
  src/thread/critical_section.h
  src/thread/critical_section_tracker.cpp
  src/thread/critical_section_tracker.hpp
  src/thread/thread.c
  src/thread/thread.h
  src/thread/thread_entry.cpp
  src/thread/thread_entry.hpp
  src/thread/thread_entry_task.cpp
  src/thread/thread_manager.hpp
  unit_tests/CMakeLists.txt
  unit_tests/memory_alloc/test_memory_alloc_helper.cpp
  unit_tests/resource_tracker/CMakeLists.txt
  unit_tests/resource_tracker/test_restrack_main.cpp
Labels: refactoring

#1100 [CBRD-22075] fix print_log_msg on loaddb
  src/executables/loaddb.c
Labels: bug

#1105 [CBRD-22116] show an error that loaddb fails to restart db
  src/executables/loaddb.c
Labels: bug

#1106 [CBRD-22121] fix stopping execution on shutdown
  src/query/vacuum.c
  src/thread/thread_daemon.hpp
  src/thread/thread_entry.cpp
  src/thread/thread_entry.hpp
  src/thread/thread_entry_task.cpp
  src/thread/thread_entry_task.hpp
  src/thread/thread_task.hpp
  src/thread/thread_worker_pool.hpp
Labels: bug

#1107 [CBRD-22125] loaddb log file was unavailable for restart errors
  src/executables/loaddb.c
Labels: bug

#1108 [CBRD-22125] correct fclose
  src/executables/loaddb.c
Labels: bug
