Repository CUBRID/cubrid, pull requests merged in 2018-04, with the labels that each got.

#1049 [CBRD-21791] fix updating PERFMON_ACTIVATION_FLAG_LAST
  src/base/perf_monitor.h
Labels: bug

#1051 [CBRD-21982] assign private LRU list to vacuum workers
  src/query/vacuum.c
  src/query/vacuum.h
Labels: bug

#1053 [CBRD-21984] make daemon stats grep-friendly
  src/base/perf_monitor.c
Labels: refactoring

#1054 [CBRD-21986] fixes deadlock detector to keep PRM_ID_LK_RUN_DEADLOCK_INTERVAL
  src/transaction/lock_manager.c
Labels: bug

#1055 [CBRD-21987] stop checkpoint on shutdown
  src/storage/page_buffer.c
  src/thread/thread_daemon.cpp
  src/thread/thread_daemon.hpp
Labels: bug

#1056 [CBRD-21988] pgbuf_block_bcb expects thread handle
  src/query/query_dump.c
Labels: bug

#1052 [CBRD-21983] fix vacuum prefetch log
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/query/vacuum.c
  src/query/vacuum.h
Labels: bug

#1058 [CBRD-21994] do not interrupt reflect unique statistics
  src/session/session.c
  src/storage/btree.c
  src/transaction/log_tran_table.c
Labels: bug

#1060 [CBRD-21996] stop logwr request handler before connection
  src/connection/server_support.c
Labels: bug

#1062 [CBRD-21995] fix calling stop log writer
  src/connection/server_support.c
Labels: bug

#1063 [CBRD-22011] do not count connection threads twice
  src/thread/thread_manager.cpp
Labels: bug

#1066 [CBRD-21980] [Regression] [HA] tables can't be replicated to slave node
  src/thread/thread_entry_task.cpp
Labels: bug

#1061 [CBRD-21955] [Replication] Transfer channel for replication data
  cubrid/CMakeLists.txt
  src/base/cubstream.cpp
  src/base/cubstream.hpp
  src/communication/communication_channel.hpp
  src/communication/stream_transfer_receiver.cpp
  src/communication/stream_transfer_receiver.hpp
  src/communication/stream_transfer_sender.cpp
  src/communication/stream_transfer_sender.hpp
  src/thread/thread_manager.cpp
  src/thread/thread_manager.hpp
  unit_tests/CMakeLists.txt
  unit_tests/transfer_channel/CMakeLists.txt
  unit_tests/transfer_channel/test_main.cpp
Labels: enhancement, in progress

#1065 [CBRD-22024] performance statistics collecting interface
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/get_clockfreq.c
  src/base/packer.cpp
  src/base/perf.cpp
  src/base/perf.hpp
  src/base/perf_def.hpp
  src/base/perf_monitor.c
  src/base/perf_monitor.h
  src/base/pinnable_buffer.hpp
  src/base/tsc_timer.h
  src/communication/stream_transfer_receiver.cpp
  src/communication/stream_transfer_sender.cpp
  src/connection/server_support.c
  src/query/query_executor.c
  src/query/query_manager.c
  src/storage/heap_file.c
  src/storage/page_buffer.c
  src/thread/thread_daemon.cpp
  src/thread/thread_daemon.hpp
  src/thread/thread_looper.cpp
  src/thread/thread_looper.hpp
  src/thread/thread_waiter.cpp
  src/thread/thread_waiter.hpp
  src/thread/thread_worker_pool.cpp
  src/thread/thread_worker_pool.hpp
  src/transaction/lock_manager.c
  unit_tests/thread/test_manager.cpp
Labels: enhancement, refactoring

#1067 [CBRD-22019] debug code for starting threads
  src/thread/thread_manager.cpp
  src/thread/thread_worker_pool.cpp
  src/thread/thread_worker_pool.hpp
  unit_tests/object_factory/test_object_factory.cpp
  unit_tests/object_factory/test_object_factory.hpp
Labels: bug

#1059 [CBRD-21998] do not kill system transaction
  src/connection/server_support.c
  src/query/show_scan.c
  src/thread/thread.c
  src/transaction/log_tran_table.c
Labels: bug

#1072 [CBRD-22032] return main entry lf transactions
  src/thread/thread.c
Labels: bug
