Repository CUBRID/cubrid, pull requests merged in 2018-06, with the labels that each got.

#1109 [CBRD-22127] safer decaching class mop from workspace
  src/object/work_space.c
Labels: bug

#1111 [CBRD-22130] "show index" statements needs a table lock
  src/storage/btree.c
Labels: bug

#1112 [CBRD-22132] Variadic instead numbered macros for cataloged formatted messages: PT_ERRORmf?, PT_WARNINGmfx?
  src/parser/parse_tree.h
Labels: enhancement, refactoring

#1110 [CBRD-22118] authorizations for some show and update statistics statements
  src/parser/parse_tree_cl.c
  src/parser/parser_support.c
  src/parser/show_meta.c
  src/parser/show_meta.h
  src/query/execute_statement.c
  src/query/show_scan.c
Labels: bug

#1114 [CBRD-22136] collecting and registering single statistics
  CMakeLists.txt
  cubrid/CMakeLists.txt
  src/base/collapsable_circular_queue.hpp
  src/base/packing_stream.hpp
  src/monitor/monitor_collect.cpp
  src/monitor/monitor_collect.hpp
  src/monitor/monitor_definition.hpp
  src/monitor/monitor_registration.cpp
  src/monitor/monitor_registration.hpp
  src/monitor/monitor_statistic.cpp
  src/monitor/monitor_statistic.hpp
  src/monitor/monitor_transaction.cpp
  src/monitor/monitor_transaction.hpp
  src/thread/thread_manager.cpp
  src/thread/thread_manager.hpp
  unit_tests/CMakeLists.txt
  unit_tests/monitor/CMakeLists.txt
  unit_tests/monitor/test_monitor_main.cpp
  unit_tests/stream/test_stream.cpp
Labels: refactoring

#1115 [CBRD-22123] Broker failed to connect to database server when insert data with multi-threads
  src/connection/tcp.c
  src/connection/wintcp.c
Labels: bug

#1116 [CBRD-22145] fix number of server request workers
  src/connection/server_support.c
Labels: bug

#1113 [CBRD-22108] Grammar for update default
  src/base/object_representation_sr.c
  src/base/object_representation_sr.h
  src/compat/db_temp.c
  src/executables/unload_schema.c
  src/object/class_object.c
  src/object/class_object.h
  src/object/object_printer.cpp
  src/object/schema_manager.c
  src/object/schema_manager.h
  src/object/schema_template.c
  src/object/schema_template.h
  src/object/transform_cl.c
  src/parser/csql_grammar.y
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/semantic_check.c
  src/query/execute_schema.c
  src/query/query_executor.c
  src/storage/catalog_class.c
Labels: enhancement

#1082 [CBRD-22013] Private memory unique pointer
  src/base/contiguous_memory_buffer.hpp
  src/base/memory_alloc.h
  src/compat/db_json.cpp
  src/thread/thread_manager.hpp
  unit_tests/memory_alloc/CMakeLists.txt
  unit_tests/memory_alloc/test_db_private_alloc.cpp
  unit_tests/memory_alloc/test_extensible_array.cpp
  unit_tests/memory_alloc/test_main.cpp
  unit_tests/memory_alloc/test_memory_alloc_helper.cpp
  unit_tests/memory_alloc/test_private_unique_ptr.cpp
  unit_tests/memory_alloc/test_private_unique_ptr.hpp
Labels: enhancement

#1119 [CBRD-22148] fetch interface and counter/timer/max statistics
  src/monitor/monitor_collect.cpp
  src/monitor/monitor_collect.hpp
  src/monitor/monitor_definition.hpp
  src/monitor/monitor_registration.cpp
  src/monitor/monitor_registration.hpp
  src/monitor/monitor_statistic.cpp
  src/monitor/monitor_statistic.hpp
  src/monitor/monitor_transaction.hpp
  unit_tests/monitor/test_monitor_main.cpp
Labels: enhancement, refactoring

#1121 [CBRD-22153] lock demotion primitives
  src/base/xserver_interface.h
  src/communication/network.h
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/communication/network_interface_sr.h
  src/communication/network_sr.c
  src/object/work_space.c
  src/object/work_space.h
  src/transaction/locator_sr.c
  src/transaction/lock_manager.c
  src/transaction/lock_manager.h
Labels: enhancement

#1122 [CBRD-22157] client cached bad class locks for committed read transac…
  src/transaction/locator_cl.c
Labels: bug
