Repository CUBRID/cubrid, pull requests merged in 2018-07, with the labels that each got.

#1123 [CBRD-22154] Replace macro definition P with PREC
  src/base/dtoa.c
  src/base/mprec.c
  src/base/mprec.h
Labels: refactoring

#1124 [CBRD-21832] DL in db_json_allocate_doc
  src/compat/db_json.cpp
  src/parser/parse_dbi.c
  src/parser/view_transform.c
Labels: bug

#1127 [CBRD-22137] fix recovery of vacuum data page
  src/query/vacuum.c
Labels: bug

#1126 [CBRD-22123] Broker failed to connect to database server
  src/connection/server_support.c
  src/executables/master.c
  src/thread/thread_manager.cpp
  src/thread/thread_manager.hpp
  src/thread/thread_worker_pool.hpp
Labels: enhancement

#1117 [CBRD-22073] Master/Slave Replication Channel
  CMakeLists.txt
  cubrid/CMakeLists.txt
  src/base/cubstream.hpp
  src/communication/communication_channel.cpp
  src/communication/communication_channel.hpp
  src/communication/communication_server_channel.cpp
  src/communication/communication_server_channel.hpp
  src/communication/stream_transfer_receiver.cpp
  src/communication/stream_transfer_receiver.hpp
  src/communication/stream_transfer_sender.cpp
  src/communication/stream_transfer_sender.hpp
  src/connection/connection_cl.c
  src/connection/connection_cl.h
  src/connection/connection_defs.h
  src/connection/connection_support.c
  src/connection/server_support.c
  src/executables/master_heartbeat.c
  src/replication/replication_master_senders_manager.cpp
  src/replication/replication_master_senders_manager.hpp
  unit_tests/CMakeLists.txt
  unit_tests/common/CMakeLists.txt
  unit_tests/common/mock_stream.cpp
  unit_tests/common/mock_stream.hpp
  unit_tests/communication_channel/test_main.cpp
  unit_tests/replication_channels/CMakeLists.txt
  unit_tests/replication_channels/cub_master_mock.cpp
  unit_tests/replication_channels/cub_master_mock.hpp
  unit_tests/replication_channels/master_replication_channel_mock.cpp
  unit_tests/replication_channels/master_replication_channel_mock.hpp
  unit_tests/replication_channels/slave_replication_channel_mock.cpp
  unit_tests/replication_channels/slave_replication_channel_mock.hpp
  unit_tests/replication_channels/test_main.cpp
  unit_tests/transfer_channel/test_main.cpp
  win/cubridcs/cubridcs.def
Labels: enhancement, in progress

#1128 [CBRD-22165] [HA] Core dumped in cubreplication::master_senders_manager::get_stream
  src/connection/server_support.c
Labels: bug

#1120 [CBRD-22109] Update query defaults
  src/parser/xasl_generation.c
  src/parser/xasl_generation.h
  src/query/execute_statement.c
  src/query/execute_statement.h
Labels: enhancement

#1129 [CBRD-22166] [Regression] Core dumped in map_running_contexts
  src/connection/server_support.c
Labels: bug

#1131 [CBRD-22164] fix vacuum_data_load_and_recover after copydb
  src/query/vacuum.c
Labels: bug

#1132 [CBRD-22172] introduce symbolic links to the latest server {error,eve…
  src/base/error_manager.c
  src/base/error_manager.h
  src/base/event_log.c
  src/communication/network_sr.c
  src/transaction/boot_sr.c
Labels: enhancement

#1133 [CBRD-22054] Update query defaults
  src/parser/xasl_generation.c
Labels: bug

#1134 [CBRD-22173] fix typo of #1132
  src/base/error_manager.c
Labels: bug

#1135 [CBRD-22178] optimize available worker queues
  src/thread/thread_worker_pool.hpp
Labels: enhancement

#1136 [CBRD-22178] protect retire context
  src/thread/thread_worker_pool.hpp
Labels: bug

#1138 [CBRD-22035] Remove GCC 4.4.7 compatibility code - string buffer
  src/base/mem_block.hpp
  src/base/string_buffer.hpp
  src/object/object_primitive.c
  src/object/object_print.c
  src/parser/parse_tree_cl.c
  src/parser/parser_support.c
Labels: enhancement

#1139 [CBRD-22174] reset last blockid for copied database
  src/query/vacuum.c
Labels: bug

#1137 [CBRD-22179] Fix replication unit test for Windows
  src/connection/connection_support.c
  src/connection/connection_support.h
  unit_tests/replication_channels/CMakeLists.txt
  unit_tests/replication_channels/cub_master_mock.cpp
  unit_tests/replication_channels/master_replication_channel_mock.cpp
  unit_tests/replication_channels/test_main.cpp
Labels: bug

#1141 [CBRD-22193] fix waiting workers to stop
  src/thread/thread_worker_pool.hpp
Labels: bug

#1142 [CBRD-22192] delete m_available_workers
  src/thread/thread_worker_pool.hpp
Labels: bug

#1144 [CBRD-22169] Core dumped in free_node_in_tree_pre
  src/parser/view_transform.c
Labels: bug

#1145 [CBRD-22197] fix UMR of db_find_string_in_in_set
  src/query/string_opfunc.c
Labels: bug

#1146 [CBRD-22171] DL in db_json_allocate_doc
  src/parser/type_checking.c
Labels: bug

#1148 [CBRD-22174] first boot after copydb
  src/query/vacuum.c
  src/query/vacuum.h
  src/transaction/boot_sr.c
  src/transaction/log_impl.h
  src/transaction/log_page_buffer.c
Labels: bug

#1147 [CBRD-22201] Refactor pt_fold_const_expr to avoid memory leaks
  src/parser/type_checking.c
Labels: bug, enhancement

#1150 [CBRD-22207] thread worker pool configuration
  contrib/gdb_debugging_scripts/thread_tran.gdb
  src/base/contiguous_memory_buffer.hpp
  src/base/extensible_array.hpp
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/connection/server_support.c
  src/query/vacuum.c
  src/thread/thread_compat.hpp
  src/thread/thread_manager.cpp
  src/thread/thread_manager.hpp
  src/thread/thread_waiter.hpp
  src/thread/thread_worker_pool.cpp
  src/thread/thread_worker_pool.hpp
  unit_tests/replication_channels/slave_replication_channel_mock.cpp
  unit_tests/replication_channels/test_main.cpp
  unit_tests/resource_tracker/test_restrack_main.cpp
  unit_tests/stream/test_stream.cpp
  unit_tests/thread/test_manager.cpp
  unit_tests/thread/test_worker_pool.cpp
  unit_tests/transfer_channel/test_main.cpp
Labels: enhancement

#1152 [CBRD-22213] fix mapping running contexts
  src/thread/thread_worker_pool.hpp
Labels: bug

#1153 [CRBD-22210] Remove redefinition of inline
  src/executables/esql_grammar.y
  src/parser/csql_grammar.y
  src/storage/es_list.h
Labels: refactoring

#1154 [CBRD-22215] ON UPDATE does not apply to ODKU
  src/parser/xasl_generation.c
Labels: bug

#1155 [CBRD-22216] fixed connection worker pool to start a task
  src/connection/connection_globals.c
  src/connection/server_support.c
Labels: bug, refactoring
