Repository CUBRID/cubrid, pull requests merged in 2018-10, with the labels that each got.

#1212 [CBRD-22345] vacuum consume iteration may allocate multiple data pages
  src/query/vacuum.c
Labels: bug

#1209 [CBRD-22343] reset sysop LSA's
  src/transaction/log_recovery.c
Labels: bug

#1220 [CBRD-22299] JSON_MERGE_PRESERVE function
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
Labels: enhancement

#1221 [CBRD-22205] JSON_MERGE_PATCH function
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/optimizer/query_graph.c
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/parse_tree_cl.c
  src/parser/parser_support.c
  src/parser/semantic_check.c
  src/parser/type_checking.c
  src/parser/xasl_generation.c
  src/query/fetch.c
  src/query/query_dump.c
  src/query/query_opfunc.c
  src/query/string_opfunc.c
  src/query/string_opfunc.h
  src/storage/storage_common.h
Labels: enhancement

#1208 [CBRD-22300] JSON_QUOTE function
  src/parser/csql_grammar.y
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/type_checking.c
  src/parser/xasl_generation.c
  src/query/fetch.c
  src/query/query_opfunc.c
  src/query/query_opfunc.h
  src/query/string_opfunc.c
  src/query/string_opfunc.h
  src/storage/storage_common.h
Labels: enhancement

#1218 [CBRD-22359] JSON_SEARCH function
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/optimizer/query_graph.c
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/parser_support.c
  src/parser/semantic_check.c
  src/parser/type_checking.c
  src/parser/xasl_generation.c
  src/query/fetch.c
  src/query/query_dump.c
  src/query/query_opfunc.c
  src/query/string_opfunc.c
  src/query/string_opfunc.h
  src/storage/storage_common.h
Labels: enhancement

#1215 [CBRD-22305] JSON_OBJECTAGG function
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/broker/shard_proxy_io.c
  src/broker/shard_proxy_io.h
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/object/object_primitive.c
  src/object/object_primitive.h
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/parse_tree_cl.c
  src/parser/parser_message.h
  src/parser/parser_support.c
  src/parser/type_checking.c
  src/parser/xasl_generation.c
  src/query/arithmetic.c
  src/query/arithmetic.h
  src/query/query_dump.c
  src/query/query_executor.c
  src/query/query_opfunc.c
  src/query/query_opfunc.h
  src/query/regu_var.h
  src/query/stream_to_xasl.c
  src/query/xasl_to_stream.c
  src/storage/storage_common.h
Labels: enhancement

#1226 [CBRD-22362] Avoid failed assertion of error module init for ha processes.
  src/base/error_manager.c
  src/base/error_manager.h
  src/executables/util_cs.c
Labels: bug

#1224 [CBRD-22361] Fixed race condition caused by log writer, get log pag…
  src/transaction/log_page_buffer.c
Labels: bug

#1202 [CBRD-22324] Commits after fetching the result
  src/broker/cas_execute.c
  src/communication/network_interface_sr.c
Labels: bug

#1219 [CBRD-22342] consider DWB block version when forcing flush
  src/storage/double_write_buffer.c
Labels: bug

#1229 [CBRD-22362] fix release mode compile of #1226
  src/base/error_manager.c
  src/base/error_manager.h
Labels: bug

#1230 [CBRD-22305] fix UMR of pt_to_aggregate_node
  src/parser/xasl_generation.c
Labels: bug

#1223 [CBRD-22181] Enable CTEs for client-side queries
  src/parser/xasl_generation.c
  src/query/execute_statement.c
  src/query/query_executor.c
  src/query/xasl.h
Labels: enhancement

#1231 [CBRD-22373] Fixed assertion of dwb_flush_block
  src/storage/double_write_buffer.c
Labels: bug

#1232 [CBRD-22378] To generate XASL of percentil functions loops infinitely
  src/parser/xasl_generation.c
Labels: bug

#1216 [CBRD-22335] Accept unique online indexes.
  src/communication/network_interface_sr.c
  src/object/schema_manager.c
  src/storage/btree.c
  src/storage/btree.h
  src/storage/btree_load.c
  src/transaction/log_manager.c
  src/transaction/log_manager.h
Labels: enhancement

#1233 [CBRD-22375] Core dumped in cubbase::restrack_assert
  src/query/query_opfunc.c
Labels: bug

#1234 [CBRD-22379] Fixed DWB issue when stop server
  src/storage/double_write_buffer.c
Labels: bug

#1235 [CBRD-22397] Skip online index loading for shared constraints
  src/object/schema_manager.c
Labels: bug

#1236 [CBRD-22398] forget coercion error of comparing incompatible domains …
  src/object/object_domain.c
Labels: bug

#1237 [CBRD-22393] Fixed flush issue when server stops
  src/storage/double_write_buffer.c
Labels: bug

#1238 [CBRD-22400] Index name can't be displayed in the error message
  src/storage/btree.c
  src/storage/btree.h
  src/storage/btree_load.c
Labels: bug

#1239 [CBRD-22402] Fixed flush force issue
  src/storage/double_write_buffer.c
Labels: bug

#1240 [CBRD-21869] add support for BIGINT type in JSON
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/compat/db_macro.c
  src/object/object_domain.c
  src/query/arithmetic.c
  src/query/string_opfunc.c
Labels: enhancement

#1241 [CBRD-22394] pt_to_aggregate_node memory leak
  src/parser/xasl_generation.c
Labels: bug

#1243 [CBRD-22363] compute log page checksum before log writer send to slave
  src/transaction/log_impl.h
  src/transaction/log_page_buffer.c
  src/transaction/log_writer.c
Labels: bug

#1242 [CBRD-22398] bestspace ignores warnings to interogate existing errors
  src/storage/heap_file.c
Labels: bug

#1244 [CBRD-22396] fix potential ABW of cub_master
  src/executables/master.c
Labels: bug

#1245 [CBRD-22414] fix memory leak in json pretty function
  src/compat/db_json.cpp
  src/query/arithmetic.c
Labels: bug

#1247 [CBRD-22423] Fixed debug code - slip of 57200d8ec34cb86f
  src/storage/double_write_buffer.c
Labels: bug

#1248 [CBRD-22418] Fix NULL key case for Online Index
  src/storage/btree.c
  src/storage/btree_load.c
  src/transaction/locator_sr.c
Labels: bug

#1249 [CBRD-22403] Core dumped in pt_uncorr_post
  src/parser/xasl_generation.c
Labels: bug

#1250 [CBRD-22420] Fix bad cast
  src/storage/btree_load.c
  src/storage/heap_file.c
  src/storage/heap_file.h
Labels: bug

#1251 [CBRD-21755] Add missing row in _db_data_type
  src/transaction/boot_cl.c
Labels: bug

#1252 [CBRD-22413] use different name nodes for spec.as_attr_list and json table columns
  src/parser/name_resolution.c
  src/parser/parse_tree_cl.c
Labels: bug

#1255 [CBRD-22406] JSON table print issue
  src/parser/parse_tree_cl.c
Labels: bug

#1253 [CBRD-22418] correct {unique | not_null} btree index type
  src/object/schema_manager.c
  src/storage/btree.c
  src/storage/btree.h
  src/storage/btree_load.c
  src/transaction/locator_sr.c
Labels: bug, refactoring

#1256 [CBRD-21486] fileio_expand_to return error code
  src/storage/file_io.c
Labels: bug

#1254 [CBRD-22417] fix memory leak in json table
  src/query/query_executor.c
  src/query/scan_json_table.cpp
  src/query/scan_json_table.hpp
  src/query/stream_to_xasl.c
  src/query/xasl.h
  src/xasl/access_json_table.cpp
  src/xasl/access_json_table.hpp
  src/xasl/xasl_stream.cpp
Labels: bug

#1262 [CBRD-22429] Fix bad statistics of Online Index
  src/storage/btree.c
Labels: bug

#1260 [CBRD-22433] add missing expr definition of str_to_date
  src/parser/type_checking.c
  src/query/string_opfunc.c
Labels: bug

#1261 [CBRD-22437] fix crash to print a bad group_concat expr
  src/parser/parse_tree_cl.c
Labels: bug

#1263 [CBRD-22439] raises an error where mq_translate to subquery has a par…
  src/parser/xasl_generation.c
Labels: bug

#1258 [CBRD-22421] Set correct index status of online index
  src/object/class_object.c
Labels: bug

#1259 [CBRD-22432] fix memory leaks in json table
  src/compat/db_json.cpp
  src/object/object_domain.c
  src/query/scan_json_table.cpp
  src/query/scan_json_table.hpp
  src/xasl/access_json_table.cpp
Labels: bug

#1269 [CBRD-22433] Revert #1260 - add missing expr definition of str_to_date
  src/parser/type_checking.c
  src/query/string_opfunc.c
Labels: bug

#1267 [CBRD-22434] fix cast from empty DB_TYPE_JSON to DB_TYPE_DATETIME
  src/object/object_domain.c
Labels: bug

#1270 [CBRD-22444] json table: delete json iterators only when xasl is destroyed
  src/query/scan_json_table.cpp
  src/xasl/access_json_table.cpp
  src/xasl/access_json_table.hpp
Labels: bug

#1265 [CBRD-22420] filtered index may not properly end but client misunders…
  src/communication/network_interface_sr.c
  src/storage/btree_load.c
Labels: bug

#1271 [CBRD-22443] demoted lock should be restored even though operation fails
  src/storage/btree_load.c
Labels: bug

#1272 [CBRD-21936] Force read of log header on restoredb
  src/transaction/log_impl.h
  src/transaction/log_manager.c
  src/transaction/log_page_buffer.c
Labels: bug

#1274 [CBRD-22441] do not interrupt fileio_expand_to
  src/storage/disk_manager.c
  src/storage/file_io.c
Labels: bug

#1273 [CBRD-22447] Fix key_len_in_page set for insert_helper
  src/storage/btree.c
Labels: bug

#1276 [CBRD-22443] online index creation is only allowed for safe cases
  src/object/schema_manager.c
Labels: bug

#1275 [CBRD-22438] fix using hostvar in json table expression
  src/parser/semantic_check.c
  src/query/scan_json_table.cpp
  src/query/scan_json_table.hpp
  src/query/scan_manager.c
Labels: bug

#1266 [CBRD-22422] fix leak when key value is reset to null
  src/storage/btree.c
  src/storage/btree_load.c
  src/storage/btree_load.h
  src/transaction/locator_sr.c
Labels: bug

#1279 [CBRD-22459] Fix possible leaks for online index
  src/storage/btree.c
Labels: bug

#1278 [CBRD-22457] fix memory leak in json unquote
  src/query/arithmetic.c
Labels: bug

#1277 [CBRD-22443] client resynchronizes cached lock if server fails to restore the demoted lock
  src/communication/network_interface_cl.c
  src/communication/network_interface_sr.c
Labels: bug

#1282 [CBRD-22319] add system parameter for read ahead fadvise
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/storage/file_io.c
Labels: enhancement

#1283 [CBRD-22436] create view as json_table bug
  src/parser/parse_tree_cl.c
  src/parser/view_transform.c
Labels: bug

#1284 [CBRD-22431] fold IF function to a varchar
  src/parser/type_checking.c
Labels: bug

#1281 [CBRD-22454] add option to cast from DB_JSON_BOOL to any other type
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/object/object_domain.c
Labels: enhancement

#1285 [CBRD-22318] Add heap best space statistics
  src/base/perf_monitor.c
  src/base/perf_monitor.h
  src/storage/heap_file.c
Labels: enhancement

#1286 [CBRD-22460] online creation of function index leaked
  src/storage/btree_load.c
Labels: bug

#1288 [CBRD-22338] vacuum_data_load_and_recover: remove wrong safe-guard
  src/query/vacuum.c
Labels: bug

#1291 [CBRD-22462] online creation of index should manage savepoint
  src/object/schema_manager.c
Labels: bug

#1292 [CBRD-22466] online IB uses scancache to scan heap
  src/storage/btree_load.c
Labels: bug

#1293 [CBRD-22468] fix rv_keyval_data memory leaks
  src/storage/btree.c
Labels: bug

#1294 [CBRD-22453] fix json_array_insert when invalid json path is provided
  src/compat/db_json.cpp
Labels: bug

#1295 [CBRD-22470] fix btree_insert_sysop_end rcvindex
  src/storage/btree.c
  src/transaction/log_manager.c
Labels: bug

#1296 [CBRD-22471] fix latch leaks to overflow page
  src/storage/btree.c
Labels: bug

#1297 [CBRD-22475] fix translation of ->> operator
  src/parser/csql_grammar.y
Labels: bug

#1299 [CBRD-22473] fix memory leak in json_search function
  src/compat/db_json.cpp
Labels: bug

#1298 [CBRD-22450] Disable Replace and ODKU for online indexes
  src/query/query_executor.c
Labels: bug

#1300 [CBRD-22124] make cubthread::entry::shutdown atomic
  src/thread/thread_entry.hpp
Labels: enhancement
