Repository CUBRID/cubrid, pull requests merged in 2019-06, with the labels that each got.

#1609 [CBRD-22950] Slave ack on consume
  sa/CMakeLists.txt
  src/replication/log_consumer.cpp
  src/replication/log_consumer.hpp
  src/replication/log_generator.cpp
  src/replication/master_control_channel.cpp
  src/replication/replication_master_node.cpp
  src/replication/replication_slave_node.cpp
  src/replication/replication_slave_node.hpp
  src/transaction/locator_sr.c
Labels: task

#1611 [CBRD-22997] adjust recdes area for apply
  src/replication/replication_object.cpp
  src/storage/heap_file.c
  src/storage/heap_file.h
Labels: bug, regression

#1614 [CBRD-22998] prevent slave_node connect to self master_node
  src/base/hostname.hpp
  src/master/master_heartbeat.cpp
  src/master/master_heartbeat.hpp
Labels: bug

#1613 [CBRD-22950] fix replication_channels unit test compile & test
  unit_tests/common/mock_stream.cpp
  unit_tests/common/mock_stream.hpp
  unit_tests/replication_channels/slave_replication_channel_mock.cpp
  unit_tests/replication_channels/slave_replication_channel_mock.hpp
  unit_tests/replication_channels/test_main.cpp
Labels: bug

#1615 [CBRD-23001] Free transaction descriptor at redo of log_group_complete record
  src/transaction/log_recovery.c
Labels: bug

#1618 [CBRD-23002] do name resolution & semantic checks on select pt node for PT_CREATE_ENTITY node
  src/executables/util_cs.c
  src/parser/semantic_check.c
Labels: bug

#1619 [CBRD-23002] do name resolution & semantic checks on select pt node for PT_CREATE_ENTITY node
  src/parser/semantic_check.c
Labels: bug

#1622 [CBRD-23009] free tdes on redo of LOG_FINISH_POSTPONE
  src/transaction/log_recovery.c
Labels: bug

#1621 [CBRD-23003] Fix stream receive amount to be aligned to 8 bytes.
  src/communication/communication_channel.hpp
  src/communication/stream_transfer_receiver.cpp
Labels: bug

#1623 [CBRD-22956] Stream entry for new master becoming active
  src/replication/log_consumer.cpp
  src/replication/replication_master_node.cpp
  src/replication/replication_master_node.hpp
  src/replication/replication_stream_entry.cpp
  src/replication/replication_stream_entry.hpp
Labels: task

#1620 [CBRD-22997] record_descriptor: allow resizing a record_descriptor with a invalid
  src/storage/record_descriptor.cpp
Labels: bug

#1624 [CBRD-23013] Fix error handling in case of string conversion scenarios
  src/loaddb/load_lexer.l
  src/loaddb/load_scanner.hpp
Labels: bug

#1625 [CBRD-22953] Ack stream pos for END_CHKPT record
  src/transaction/log_global.c
  src/transaction/log_impl.h
  src/transaction/log_page_buffer.c
  src/transaction/log_record.hpp
  src/transaction/log_recovery.c
  src/transaction/transaction_master_group_complete_manager.cpp
Labels: task

#1631 [CBRD-22978] Locator multi insert function
  src/storage/heap_file.c
  src/storage/heap_file.h
  src/transaction/boot_sr.c
  src/transaction/locator_sr.c
  src/transaction/locator_sr.h
Labels: task

#1630 [CBRD-22954] Recovery of active transactions start stream position
  src/transaction/log_global.c
  src/transaction/log_impl.h
  src/transaction/log_recovery.c
Labels: task

#1627 [CBRD-23006] Add assert in timezone module to catch internal error.
  src/base/tz_support.c
Labels: bug

#1632 [CBRD-23017] Remove duplicate on_transaction_commit call
  src/transaction/log_manager.c
Labels: bug

#1633 [CBRD-23018] changed_attrs_row_repl_entry: use proper heap id on pack/get_packed_size
  src/replication/replication_object.cpp
Labels: bug

#1634 [CBRD-23006] create session without connection for replication apply
  src/base/tz_support.c
  src/compat/dbtype_def.h
  src/connection/connection_defs.h
  src/connection/connection_sr.c
  src/connection/connection_support.c
  src/connection/server_support.c
  src/session/session.c
  src/session/session.h
  src/session/session_sr.c
  src/thread/thread_entry.cpp
  src/thread/thread_entry.hpp
  src/transaction/locator_sr.c
Labels: bug

#1635 [CBRD-23008] [replication] ddl_proxy: disable trigger execution
  src/executables/util_cs.c
Labels: bug

#1636 [CBRD-23008] locator_force: safe start top operation
  src/transaction/locator_sr.c
Labels: bug

#1637 [CBRD-23020] [replication] fix memory leak in master_senders_supervisor_task::execute
  src/replication/replication_master_node.cpp
  src/replication/replication_master_senders_manager.cpp
  src/replication/replication_master_senders_manager.hpp
  unit_tests/replication_channels/cub_master_mock.cpp
  unit_tests/replication_channels/master_replication_channel_mock.cpp
  unit_tests/replication_channels/master_replication_channel_mock.hpp
Labels: bug

#1638 [CBRD-23024] safe guard master/slave node finalize
  src/connection/server_support.c
  src/replication/replication_master_node.cpp
  src/replication/replication_slave_node.cpp
Labels: bug

#1639 [CBRD-23023] reset private lru index after execution
  src/connection/server_support.c
  src/thread/thread_entry_task.cpp
Labels: bug

#1640 [CBRD-23021] Add flag FOR_HA_CONTEXT for no_backslash_escapes, ansi_quotes, mysql_trigger_correlation_names
  src/base/system_parameter.c
Labels: bug

#1642 [CBRD-23025] init session tz_region
  src/session/session.c
Labels: bug

#1644 [CBRD-23027] fix get session parameter when session parameters are missing
  src/session/session.c
Labels: bug

#1645 [CBRD-23030] disable by default debug replication data
  src/base/system_parameter.c
Labels: bug
