Repository CUBRID/cubrid, pull requests merged in 2019-09, with the labels that each got.

#1832 [CBRD-23112] comment for windows execute_process issue
  CMakeLists.txt
Labels: enhancement

#1833 [CBRD-23226] move SA_MODE process vacuum data to xvacuum
  src/query/vacuum.c
Labels: refactoring

#1836 [CBRD-23224] cub_master: fix send hostname of the master node
  src/executables/master_heartbeat.c
Labels: bug

#1837 [CBRD-23221] fix log postpone cache
  src/transaction/log_postpone_cache.cpp
Labels: bug

#1799 [CBRD-23159] Updated slave node GCM
  cubrid/CMakeLists.txt
  src/replication/log_consumer.hpp
  src/replication/replication_master_node.cpp
  src/transaction/log_manager.h
  src/transaction/log_page_buffer.c
  src/transaction/transaction_group_complete_manager.cpp
  src/transaction/transaction_group_complete_manager.hpp
  src/transaction/transaction_group_completion.hpp
  src/transaction/transaction_master_group_complete_manager.cpp
  src/transaction/transaction_master_group_complete_manager.hpp
  src/transaction/transaction_slave_group_complete_manager.cpp
  src/transaction/transaction_slave_group_complete_manager.hpp
Labels: task

#1800 [CBRD-23160] Added single node GCM
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/transaction/log_manager.h
  src/transaction/transaction_group_complete_manager.cpp
  src/transaction/transaction_master_group_complete_manager.cpp
  src/transaction/transaction_single_node_group_complete_manager.cpp
  src/transaction/transaction_single_node_group_complete_manager.hpp
  src/transaction/transaction_slave_group_complete_manager.hpp
Labels: task

#1839 [CBRD-23173] Loaddb must use BU_LOCK
  src/loaddb/load_server_loader.cpp
  src/storage/heap_file.c
  src/transaction/locator_sr.c
Labels: task

#1843 [CBRD-22892] remove unnecessary code (not covered by remove password ddl_proxy)
  src/object/authenticate.c
Labels: bug

#1842 [CBRD-23229] Fix statement print for replication when contains host var or parameters
  src/query/execute_statement.c
Labels: bug

#1841 [CBRD-23023] reset private_lru_index on retire and recycle context
  src/connection/server_support.c
  src/thread/thread_entry_task.cpp
Labels: bug

#1834 [CBRD-23226] Refactoring of vacuum job cursor
  src/query/vacuum.c
Labels: refactoring

#1840 [CBRD-23157] stream entry to notify slave stream write finished
  src/communication/communication_channel.cpp
  src/communication/stream_transfer_receiver.cpp
  src/communication/stream_transfer_receiver.hpp
  src/connection/server_support.c
  src/replication/ha_operations.cpp
  src/replication/log_consumer.cpp
  src/replication/replication_master_node.cpp
  src/replication/replication_node.cpp
  src/replication/replication_node.hpp
  src/replication/replication_node_manager.cpp
  src/replication/replication_slave_node.cpp
  src/replication/replication_slave_node.hpp
  src/replication/replication_stream_entry.hpp
  src/transaction/log_manager.c
Labels: enhancement, task

#1845 [CBRD-23230] backport string_buffer::hex_dump
  src/base/string_buffer.cpp
  src/base/string_buffer.hpp
Labels: enhancement

#1848 [CBRD-23144] add loaddb worker pool stats
  src/base/perf_monitor.c
  src/base/perf_monitor.h
  src/loaddb/load_worker_manager.cpp
  src/loaddb/load_worker_manager.hpp
Labels: enhancement

#1850 [CBRD-23226] Separate server/sa_mode run task function
  src/query/vacuum.c
Labels: refactoring

#1849 [CBRD-23226] vacuum data update
  src/query/vacuum.c
Labels: refactoring

#1851 [CBRD-23144] fix crashes of loaddb worker pool
  src/base/perf_monitor.c
  src/loaddb/load_worker_manager.cpp
Labels: bug, regression

#1856 [CBRD-23226] vacuum data entry functions
  src/query/vacuum.c
Labels: refactoring

#1858 [CBRD-23226] vacuum data job cursor start_job_on_current_entry
  src/query/vacuum.c
Labels: refactoring

#1857 [CBRD-23118] set media crash resetlog before broken log record
  src/transaction/log_recovery.c
Labels: bug, legacy

#1852 [CBRD-22661] Disable FK check for loaddb
  src/loaddb/load_server_loader.cpp
  src/transaction/locator_sr.c
  src/transaction/locator_sr.h
Labels: bug

#1859 [CBRD-23240] Correct vacuum_sa_run_job is partial block argument
  src/query/vacuum.c
Labels: bug, regression

#1838 [CBRD-23217] use ext mem block for log postpone cache entry
  src/compat/db_client_type.hpp
  src/transaction/log_postpone_cache.cpp
  src/transaction/log_postpone_cache.hpp
  src/transaction/log_tran_table.c
Labels: enhancement

#1853 [CBRD-23231] loaddb: add option to load trigger file
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  src/executables/util_admin.c
  src/executables/util_front.c
  src/executables/utility.h
  src/loaddb/load_common.hpp
  src/loaddb/load_db.c
Labels: enhancement

#1860 [CBRD-23244] pass vacuum_process_log_block a data entry copy
  src/query/vacuum.c
Labels: bug, regression

#1854 [CBRD-23239] fix uninitialized variable in btree delete key from leaf
  src/storage/btree.c
Labels: bug

#1844 [CBRD-23201] Added the classname to the hfid cache
  src/connection/connection_support.c
  src/query/vacuum.c
  src/storage/catalog_class.c
  src/storage/compactdb_sr.c
  src/storage/heap_file.c
  src/storage/heap_file.h
  src/storage/page_buffer.c
  src/transaction/boot_sr.c
  src/transaction/locator_sr.c
Labels: task

#1863 [CBRD-23222] xvacuum - consume all vacuum data blocks
  src/query/vacuum.c
Labels: bug, refactoring

#1861 [CBRD-23246] Fix foreign key check
  src/transaction/locator_sr.c
Labels: bug

#1855 [CBRD-23232] use proper scan for getting class record
  src/loaddb/load_server_loader.cpp
Labels: bug

#1862 [CBRD-23241] Remove new slave request and process master hostname
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/connection/connection_defs.h
  src/connection/heartbeat.h
  src/connection/server_support.c
  src/connection/server_support.h
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
  src/executables/master_request.h
Labels: bug

#1866 [CBRD-23249] initialize classname entry of hfid table
  src/storage/heap_file.c
Labels: bug

#1867 [CBRD-23226] rename oldest/newest mvccid variables
  src/executables/unittests_snapshot.c
  src/query/vacuum.c
  src/query/vacuum.h
  src/storage/btree_load.c
  src/transaction/locator_sr.c
  src/transaction/log_append.cpp
  src/transaction/log_impl.h
  src/transaction/log_manager.c
  src/transaction/log_page_buffer.c
  src/transaction/log_storage.hpp
  src/transaction/log_tran_table.c
  src/transaction/mvcc_table.cpp
  src/transaction/mvcc_table.hpp
Labels: refactoring

#1781 [CBRD-23118] fix fetching pages after log reset
  src/transaction/log_page_buffer.c
  src/transaction/log_recovery.c
  src/transaction/log_storage.hpp
Labels: bug, legacy

#1870 [CBRD-23226] Fix vacuum_data_entry default constructor
  src/query/vacuum.c
Labels: bug, regression

#1869 [CBRD-23253] Fix conversion table for conversion functions
  src/loaddb/load_db_value_converter.cpp
Labels: bug

#1871 [CBRD-23173] No instance lock for bulk loading
  src/storage/heap_file.c
  src/transaction/lock_manager.c
Labels: enhancement

#1872 [CBRD-23258] loaddb data file open may not be given
  src/loaddb/load_db.c
Labels: bug

#1873 [CBRD-23259] Increase the number of tasks available in the workerpool
  src/loaddb/load_worker_manager.cpp
Labels: task

#1874 [CBRD-23255] xvacuum update data when cursor becomes invalid
  src/query/vacuum.c
Labels: bug, regression

#1868 [CBRD-23118] remove log_recovery_resetlog is_new_append_page argument
  src/transaction/log_impl.h
  src/transaction/log_page_buffer.c
  src/transaction/log_recovery.c
Labels: refactoring

#1879 [CBRD-23264] Fix locks check during index insert
  src/storage/btree.c
Labels: bug

#1884 [CBRD-22879] Change signature of packable_object::get_packed_size
  src/base/packable_object.hpp
  src/storage/record_descriptor.cpp
  src/storage/record_descriptor.hpp
  src/transaction/client_credentials.cpp
  src/transaction/client_credentials.hpp
Labels: refactoring

#1885 [CBRD-22600] Robustness fixes to pystatdump.py
  contrib/pystatdump/pystatdump.py
Labels: bug

#1883 [CBRD-23260] Lock-free transaction index
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/lockfree_transaction.cpp
  src/base/lockfree_transaction.hpp
  src/base/lockfree_transaction_index.cpp
  src/base/lockfree_transaction_index.hpp
  src/thread/thread_entry.cpp
  src/thread/thread_entry.hpp
  src/thread/thread_manager.cpp
Labels: refactoring

#1892 [CBRD-23267] Reset set_Ref_area and set_Object_area on area_final
  src/base/area_alloc.c
  src/object/set_object.c
  src/object/set_object.h
Labels: bug, regression

#1888 [CBRD-22679] blacklist functions returning json_types as function_indexes
  src/parser/parse_tree_cl.c
Labels: bug

#1887 [CBRD-23273] loaddb: initialize load driver on thread
  src/loaddb/load_session.cpp
Labels: bug

#1890 [CBRD-23275] loaddb: log error when table is missing
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  src/executables/utility.h
  src/loaddb/load_session.cpp
Labels: bug

#1895 [CBRD-22679] fix hdr comment of pt_function_is_allowed_as_function_index
  src/parser/parse_tree_cl.c
Labels: refactoring

#1893 [CBRD-23281] loaddb: fix race condition on batch commit
  src/loaddb/load_session.cpp
  src/loaddb/load_session.hpp
Labels: bug

#1889 [CBRD-22729] Avoid dummy benchmark func evaluation
  src/query/query_executor.c
Labels: bug

#1894 [CBRD-22879] Fix compile
  unit_tests/packing/test_packing.cpp
  unit_tests/packing/test_packing.hpp
Labels: bug

#1891 [CBRD-23279] Fix incorrect page unfix
  src/transaction/locator_sr.c
Labels: bug

#1897 [CBRD-23276] Fixed locking check for rollbacking an insert on unique index
  src/storage/btree.c
Labels: bug

#1898 [CBRD-23271] loaddb: check for heap_attrinfo_set errors
  src/loaddb/load_server_loader.cpp
Labels: bug

#1899 [CBRD-23287] Fix notifying task capper of ended task
  cubrid/CMakeLists.txt
  src/loaddb/load_session.cpp
  src/loaddb/load_worker_manager.cpp
  src/loaddb/load_worker_manager.hpp
  src/thread/thread_worker_pool.hpp
  src/thread/thread_worker_pool_taskcap.hpp
Labels: bug

#1865 [CBRD-23216] clarify vacuum oldest unvacuumed mvccid management
  src/query/vacuum.c
  src/query/vacuum.h
  src/transaction/log_append.cpp
  src/transaction/log_page_buffer.c
  src/transaction/log_storage.hpp
Labels: refactoring

#1900 [CBRD-23283] loaddb: check missing not null attributes
  src/loaddb/load_server_loader.cpp
Labels: bug

#1903 [CBRD-23285] loaddb: skip empty lines
  src/loaddb/load_common.cpp
Labels: bug

#1904 [CBRD-23291] attributes are added as definition order
  src/loaddb/load_server_loader.cpp
Labels: bug

#1905 [CBRD-23290] no oldest unvacuumed update when data is empty
  src/base/lockfree_circular_queue.hpp
  src/query/vacuum.c
Labels: bug

#1907 [CBRD-23295] loaddb: copy attribute name
  src/loaddb/load_class_registry.cpp
  src/loaddb/load_class_registry.hpp
Labels: bug

#1908 [CBRD-23260] Rename lockfree_transaction_system files
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/lockfree_transaction.cpp
  src/base/lockfree_transaction.hpp
  src/base/lockfree_transaction_system.cpp
  src/base/lockfree_transaction_system.hpp
  src/thread/thread_entry.cpp
  src/thread/thread_manager.cpp
Labels: refactoring

#1909 [CBRD-23260] Separate table/descriptor files
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/lockfree_transaction_descriptor.cpp
  src/base/lockfree_transaction_descriptor.hpp
  src/base/lockfree_transaction_system.hpp
  src/base/lockfree_transaction_table.cpp
  src/base/lockfree_transaction_table.hpp
Labels: refactoring

#1910 [CBRD-23293] Fix conversion function for numeric type
  src/loaddb/load_db_value_converter.cpp
Labels: bug

#1913 [CBRD-23303] Changed the message of --load-only parameter
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  src/loaddb/load_db.c
Labels: task

#1914 [CBRD-23306] activate intl_check_input_string on server
  src/base/intl_support.c
  src/base/intl_support.h
  src/base/system_parameter.c
Labels: bug

#1902 [CBRD-23226] Move oldest visible management to mvcc table
  src/base/perf_monitor.c
  src/executables/unittests_snapshot.c
  src/query/vacuum.c
  src/query/vacuum.h
  src/storage/btree_load.c
  src/transaction/locator_sr.c
  src/transaction/log_append.cpp
  src/transaction/log_impl.h
  src/transaction/log_manager.c
  src/transaction/log_tran_table.c
  src/transaction/mvcc_table.cpp
  src/transaction/mvcc_table.hpp
Labels: refactoring

#1915 [CBRD-23226] vacuum_master_task refactoring
  src/query/vacuum.c
Labels: refactoring

#1916 [CBRD-23260] Rename and explain better
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/lockfree_transaction_descriptor.cpp
  src/base/lockfree_transaction_descriptor.hpp
  src/base/lockfree_transaction_reclaimable.hpp
  src/base/lockfree_transaction_system.hpp
  src/base/lockfree_transaction_table.hpp
Labels: refactoring

#1917 [CBRD-23308] stop loading when interrupted or failed
  src/loaddb/load_db.c
Labels: bug

#1918 [CBRD-23301] Fix error filtering and rows committed message
  src/loaddb/load_db_value_converter.cpp
  src/loaddb/load_driver.cpp
  src/loaddb/load_driver.hpp
  src/loaddb/load_error_handler.cpp
  src/loaddb/load_error_handler.hpp
  src/loaddb/load_server_loader.cpp
  src/loaddb/load_session.cpp
Labels: bug

#1911 [CBRD-22546] Fix Json escaped unicode sequence behaviors
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/compat/db_json_path.cpp
  src/compat/db_json_path.hpp
  src/query/arithmetic.c
Labels: bug

#1924 [CBRD-23321] Fix array_end_token dump assertion
  src/compat/db_json_path.cpp
Labels: bug

#1925 [CBRD-23319] add session to online index workers
  src/storage/btree_load.c
Labels: bug

#1926 [CBRD-23320] fix vacuum_master_task::should_interrupt_iteration return
  src/query/vacuum.c
Labels: bug

#1923 [CBRD-23318] loaddb shows detailed error messages
  src/loaddb/load_server_loader.cpp
Labels: bug

#1921 [CBRD-22990] Fixed sysop in select incr
  src/query/query_executor.c
Labels: bug

#1927 [CBRD-23313] Check snapshot before key generation when function index is involved
  src/storage/btree_load.c
Labels: bug

#1929 [CBRD-23322] Fixed unique statistics
  src/storage/btree_load.c
Labels: bug

#1931 [CBRD-23331] fix slips of incr patch: #1921
  src/query/query_executor.c
Labels: bug, regression

#1922 [CBRD-23266] lock-free freelist & transaction
  src/base/lockfree_freelist.hpp
  src/base/lockfree_transaction_descriptor.cpp
  src/base/lockfree_transaction_descriptor.hpp
  src/base/lockfree_transaction_reclaimable.hpp
  src/base/lockfree_transaction_table.cpp
  src/base/lockfree_transaction_table.hpp
  unit_tests/lockfree/test_freelist_functional.cpp
Labels: refactoring

#1932 [CBRD-23330] Fix vacuum_master_task refactoring regressions
  src/query/vacuum.c
Labels: bug, regression

#1928 [CBRD-23297] interrupt only one load session
  src/base/util_func.c
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_sr.c
  src/loaddb/load_db.c
  src/loaddb/load_session.cpp
  src/loaddb/load_session.hpp
  src/loaddb/load_worker_manager.cpp
  src/loaddb/load_worker_manager.hpp
Labels: bug

#1934 [CBRD-23336] loaddb: fix merge with develop
  CMakeLists.txt
  src/executables/unload_object.c
  src/executables/unloaddb.c
  src/executables/unloaddb.h
  unit_tests/CMakeLists.txt
Labels: bug

#1936 [CBRD-23341] scan may start instant lock mode
  src/query/query_executor.c
Labels: bug, regression

#1933 [CBRD-23338] allow numbers to monetary conversions
  src/loaddb/load_db_value_converter.cpp
Labels: bug

#1937 [CBRD-23336] cmake: download and install win_flex_bison
  .appveyor.yml
  CMakeLists.txt
Labels: bug

#1935 [CBRD-23337] Loaddb workers does not acquire locks
  src/loaddb/load_server_loader.cpp
  src/storage/btree.c
  src/storage/heap_file.c
  src/transaction/locator_sr.c
  src/transaction/lock_manager.c
  src/transaction/lock_manager.h
Labels: bug

#1938 [CBRD-23346] loaddb: fix load from server file system
  src/loaddb/load_db.c
Labels: bug

#1940 [CBRD-23299] loaddb: do not copy CLOB/BLOB files
  src/loaddb/load_server_loader.cpp
Labels: bug

#1939 [CBRD-23344] Fixed issue caused by unique statistics
  src/storage/btree_load.c
Labels: bug

#1942 [CBRD-23349] Disable interrupt safe-guard in SA_MODE
  src/transaction/log_tran_table.c
Labels: bug

#1943 [CBRD-23364] loaddb does not lock objects to check fk constraint
  src/storage/catalog_class.c
  src/transaction/locator_sr.c
  src/transaction/locator_sr.h
Labels: bug

#1945 [CBRD-23355] Do not reset LSA links at recovery in case of system tra…
  src/transaction/log_tran_table.c
Labels: bug
