Repository CUBRID/cubrid, pull requests merged in 2019-07, with the labels that each got.

#1612 [CBRD-22214] Replicate savepoints
  src/base/stream_entry.hpp
  src/replication/log_generator.cpp
  src/replication/log_generator.hpp
  src/replication/replication_object.cpp
  src/replication/replication_object.hpp
  src/replication/replication_stream_entry.cpp
  src/transaction/transaction_sr.c
Labels: bug

#1643 [CBRD-23026] Heap append pages
  src/storage/heap_file.c
  src/storage/heap_file.h
  src/storage/page_buffer.c
  src/storage/page_buffer.h
  src/transaction/locator_sr.c
Labels: task

#1648 [CBRD-23033] [replication] fix replication log generator for update statements
  src/storage/heap_file.c
Labels: bug

#1649 [CBRD-23032] thread tasks with callables
  src/connection/server_support.h
  src/session/session.c
  src/thread/thread_entry_task.hpp
  src/thread/thread_manager.hpp
  src/thread/thread_task.hpp
Labels: enhancement

#1628 [CBRD-23008] add code to print stack dump into a buffer
  cubrid/CMakeLists.txt
  src/base/stack_dump.c
  src/base/stack_dump.h
Labels: bug

#1650 [CBRD-22937] pack stream entry state and count separately
  src/replication/replication_stream_entry.cpp
  src/replication/replication_stream_entry.hpp
Labels: task

#1651 [CBRD-23035] minor changes (fix warnings & other)
  src/base/packer.cpp
  src/base/packer.hpp
  src/base/stream_entry.hpp
  src/communication/network_interface_sr.c
  src/replication/replication_object.cpp
  src/replication/replication_object.hpp
  src/replication/replication_stream_entry.hpp
  src/replication/slave_control_channel.hpp
  src/transaction/locator_sr.c
  src/transaction/replication.h
  unit_tests/packing/test_packing.cpp
Labels: task

#1652 [CBRD-23037] fix heartbeat cluster shutdown deadlock
  src/base/udp_rpc.hpp
  src/master/heartbeat_cluster.cpp
  src/master/master_heartbeat.cpp
Labels: bug

#1653 [CBRD-21524] fix warning: type qualifiers ignored on cast result type
  src/base/locale_support.c
  src/base/lock_free.c
  src/base/lock_free.h
  src/base/packer.cpp
  src/compat/db_macro.c
  src/executables/compactdb_cl.c
  src/executables/loader.c
  src/object/object_domain.c
  src/object/transform_cl.c
  src/parser/parser_allocator.cpp
  src/parser/parser_support.c
  src/parser/type_checking.c
  src/query/execute_schema.c
  src/query/numeric_opfunc.h
  src/query/query_executor.c
  src/query/string_opfunc.c
Labels: task

#1657 [CBRD-23037] fix hearbeat deadlock on shutdown
  src/master/master_heartbeat.cpp
Labels: bug

#1616 [CBRD-22984] replication_row_apply
  cubrid/CMakeLists.txt
  src/base/object_representation.h
  src/base/object_representation_sr.c
  src/base/object_representation_sr.h
  src/base/xserver_interface.h
  src/object/object_representation.c
  src/object/transform.c
  src/object/transform.h
  src/replication/replication_object.cpp
  src/replication/replication_row_apply.cpp
  src/replication/replication_row_apply.hpp
  src/storage/btree.c
  src/storage/btree.h
  src/storage/heap_file.c
  src/storage/heap_file.h
  src/transaction/locator_sr.c
  src/transaction/locator_sr.h
Labels: refactoring

#1617 [CBRD-22951] Send ack on stream flush
  src/base/cubstream.hpp
  src/base/stream_file.cpp
  src/base/stream_file.hpp
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/communication/stream_transfer_sender.cpp
  src/replication/log_consumer.cpp
  src/replication/log_consumer.hpp
  src/replication/replication_common.hpp
  src/replication/replication_slave_node.cpp
  src/replication/replication_slave_node.hpp
  src/replication/slave_control_channel.cpp
  src/replication/slave_control_channel.hpp
Labels: task

#1655 [CBRD-23034] replace simple task classes with callable tasks
  src/query/vacuum.c
  src/replication/replication_master_senders_manager.cpp
  src/replication/replication_master_senders_manager.hpp
  src/storage/disk_manager.c
  src/storage/double_write_buffer.c
  src/storage/external_sort.c
  src/storage/file_io.c
  src/storage/page_buffer.c
  src/thread/thread_task.hpp
  src/transaction/lock_manager.c
  src/transaction/log_manager.c
Labels: refactoring

#1659 [CBRD-23040] fix cleanup_migrate_to_long_transations check_valid safe-guard
  src/transaction/mvcc_active_tran.cpp
Labels: bug

#1662 [CBRD-22951] fix case slave_node has no connection to a master
  src/replication/replication_slave_node.cpp
  src/replication/slave_control_channel.cpp
  src/replication/slave_control_channel.hpp
Labels: bug

#1660 [CBRD-23041] packer::get_all_packed_size_starting_offset
  src/base/packer.cpp
  src/base/packer.hpp
  src/replication/replication_object.cpp
  unit_tests/packing/test_packing.cpp
  unit_tests/stream/test_stream.cpp
Labels: enhancement

#1664 [CBRD-23043] fix UMR of db_add_time
  src/query/string_opfunc.c
Labels: bug

#1665 [CBRD-23039] fix UMR on callers of heap_get_visible_version
  src/query/query_executor.c
  src/query/scan_manager.c
  src/query/serial.c
  src/storage/catalog_class.c
  src/storage/heap_file.c
  src/transaction/locator_sr.c
  src/transaction/lock_manager.c
Labels: bug

#1668 [CBRD-23042] [replication] always demote master to slave
  src/base/system_parameter.c
  src/master/master_heartbeat.cpp
  src/master/master_heartbeat.hpp
Labels: task

#1667 [CBRD-23048] [replication] fix flooding of the server err log file
  src/communication/stream_transfer_receiver.cpp
  src/communication/stream_transfer_sender.cpp
Labels: bug

#1562 [CBRD-22923] avoid dereferencing from outside of buffer
  src/compat/db_date.c
Labels: bug

#1673 [CBRD-23031] Incorrect results of ADDDATE when subtracting certain months
  src/query/string_opfunc.c
Labels: bug

#1669 [CBRD-23047] [replication] fix cub_master send of the master hostname to cub_server
  src/master/heartbeat_cluster.cpp
  src/master/master_heartbeat.cpp
  src/master/master_heartbeat.hpp
  src/master/master_request.c
  src/master/master_request.h
  src/replication/master_control_channel.cpp
Labels: bug

#1674 [CBRD-22780] fix stream delete order
  src/replication/replication_node_manager.cpp
Labels: bug

#1658 [CBRD-21524] fix warning: cast between incompatible function types
  src/object/transform_cl.c
Labels: refactoring

#1672 [CBRD-23045] fix UMR of accessing null value
  src/object/object_primitive.c
Labels: bug

#1661 [CBRD-22892] Disable password for ddl_proxy
  src/communication/network_interface_cl.c
  src/communication/network_interface_sr.c
  src/executables/ddl_proxy_client.cpp
  src/executables/util_cs.c
  src/executables/utility.h
  src/query/execute_statement.c
  src/replication/log_generator.cpp
  src/replication/replication_db_copy.cpp
  src/replication/replication_db_copy.hpp
  src/replication/replication_object.cpp
  src/replication/replication_object.hpp
  src/transaction/locator_sr.c
  src/transaction/locator_sr.h
  src/transaction/replication.h
Labels: task

#1654 [CBRD-23036] Replicating sub-transactions
  cubrid/CMakeLists.txt
  src/replication/log_consumer.cpp
  src/replication/log_consumer.hpp
  src/replication/log_generator.cpp
  src/replication/log_generator.hpp
  src/replication/replication_stream_entry.cpp
  src/replication/replication_stream_entry.hpp
  src/replication/replication_subtran_apply.cpp
  src/replication/replication_subtran_apply.hpp
  src/replication/replication_subtran_generate.cpp
  src/replication/replication_subtran_generate.hpp
  src/storage/heap_file.c
  src/storage/heap_file.h
  src/thread/thread_entry.hpp
  src/transaction/locator_sr.c
  src/transaction/lock_manager.c
Labels: task

#1676 [CBRD-23036] fix compile
  src/replication/log_consumer.hpp
  unit_tests/stream/test_stream.cpp
Labels: bug

#1679 [CBRD-23057] [replication] fix set representation id
  src/object/object_representation.c
Labels: bug

#1670 [CBRD-23051] Pack list of OID
  src/base/packer.cpp
  src/base/packer.hpp
Labels: enhancement

#1680 [CBRD-23058] [replication] reserve area size for heap adjustment
  src/replication/replication_row_apply.cpp
Labels: bug

#1663 [CBRD-23004] convert xtran start/end sysop intro replication savepoints
  src/replication/log_generator.cpp
  src/replication/log_generator.hpp
  src/transaction/transaction_sr.c
Labels: task

#1686 [CBRD-23066] Fix uninited ctrl_sender
  src/replication/replication_slave_node.cpp
Labels: bug

#1683 [CBRD-23063] suppress windows spammer warnings
  src/base/error_code.h
  src/base/lock_free.c
Labels: enhancement

#1684 [CBRD-21524] suppress -Wformat-truncation GCC warning
  src/base/error_manager.c
  src/base/language_support.c
  src/base/locale_support.c
  src/base/tz_compile.c
  src/base/unicode_support.c
  src/broker/broker.c
  src/broker/broker_admin_pub.c
  src/broker/broker_filename.c
  src/broker/broker_tester.c
  src/broker/cas.c
  src/broker/cas_log.c
  src/broker/cas_sql_log2.c
  src/broker/shard_proxy_log.c
  src/cci/cas_cci.c
  src/cm_common/cm_dep_tasks.c
  src/executables/checksumdb.c
  src/executables/csql.c
  src/executables/util_cs.c
  src/storage/es_posix.c
  src/storage/file_io.c
  src/storage/page_buffer.c
  src/tools/cci_applier.c
  src/transaction/log_applier.c
  src/transaction/log_applier_sql_log.c
Labels: enhancement

#1687 [CBRD-23067] Add semaphore class
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/semaphore.hpp
Labels: enhancement

#1685 [CBRD-21524] fix -Wformat-overflow GCC warning
  src/base/ini_parser.c
  src/broker/broker_acl.c
  src/broker/broker_admin_pub.c
  src/broker/cas_execute.c
  src/broker/shard_admin_pub.c
  src/transaction/log_writer.c
Labels: enhancement

#1678 [CBRD-23056] setup protocol slave node connection to master node
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/base/error_code.h
  src/base/multi_thread_stream.cpp
  src/base/multi_thread_stream.hpp
  src/base/stream_file.cpp
  src/base/stream_file.hpp
  src/communication/communication_channel.cpp
  src/communication/communication_channel.hpp
  src/communication/communication_server_channel.cpp
  src/communication/stream_transfer_receiver.cpp
  src/communication/stream_transfer_sender.cpp
  src/connection/connection_defs.h
  src/connection/server_support.c
  src/master/master.c
  src/replication/log_consumer.cpp
  src/replication/log_consumer.hpp
  src/replication/replication_common.hpp
  src/replication/replication_master_node.cpp
  src/replication/replication_master_node.hpp
  src/replication/replication_node.cpp
  src/replication/replication_node.hpp
  src/replication/replication_slave_node.cpp
  src/replication/replication_slave_node.hpp
Labels: enhancement

#1688 [CBRD-23068] set ER_OBJ_OBJECT_NOT_FOUND error
  src/replication/replication_row_apply.cpp
Labels: bug

#1646 [CBRD-22955] Filtered apply after master crash
  src/communication/stream_transfer_sender.cpp
  src/connection/server_support.c
  src/replication/log_consumer.cpp
  src/replication/log_generator.cpp
  src/replication/log_generator.hpp
  src/replication/master_control_channel.cpp
  src/replication/master_control_channel.hpp
  src/replication/replication_master_node.cpp
  src/replication/replication_slave_node.cpp
  src/replication/slave_control_channel.cpp
  src/transaction/log_global.c
  src/transaction/log_impl.h
  src/transaction/log_manager.c
  src/transaction/log_manager.h
  src/transaction/log_page_buffer.c
  src/transaction/log_recovery.c
  src/transaction/log_storage.hpp
  src/transaction/log_tran_table.c
  src/transaction/transaction_master_group_complete_manager.cpp
Labels: task

#1692 [CBRD-22675] backport record descriptor changes from ha replication
  src/storage/record_descriptor.cpp
  src/storage/record_descriptor.hpp
Labels: task

#1691 [CBRD-23070] Update SA_MODE vacuum data last blockid
  src/query/vacuum.c
  src/query/vacuum.h
  src/transaction/boot_sr.c
Labels: bug

#1694 [CBRD-23070] Update vacuum last blockid on SA_MODE shutdown
  src/query/vacuum.c
  src/query/vacuum.h
  src/transaction/boot_sr.c
Labels: enhancement

#1693 [CBRD-22786] fix to backup considers vacuum
  src/transaction/log_page_buffer.c
Labels: bug

#1695 [CBRD-22786] [10.1p3] fix to backup considers vacuum (#1693)
  src/transaction/log_page_buffer.c
Labels: bug

#1696 [CBRD-23075] [10.1p3] fix UMR on callers of heap_get_visible_version (#1665)
  src/query/query_executor.c
  src/query/scan_manager.c
  src/query/serial.c
  src/storage/catalog_class.c
  src/storage/heap_file.c
  src/transaction/locator_sr.c
  src/transaction/lock_manager.c
Labels: bug

#1697 [CBRD-23076] [10.1p3] fix UMR of db_add_time (#1664)
  src/query/string_opfunc.c
Labels: bug

#1698 [CBRD-23077] [10.1p3] Incorrect results of ADDDATE when subtracting certain mo…
  src/query/string_opfunc.c
Labels: bug

#1699 [CBRD-22786] Windows build fix
  src/query/vacuum.c
Labels: bug

#1701 [CBRD-23080] fix UMR of accessing null value (#1672)
  src/compat/db_macro.c
  src/compat/dbtype.h
  src/object/object_primitive.c
Labels: bug

#1702 [CBRD-23081] [10.1p3] avoid dereferencing from outside of buffer (#1562)
  src/compat/db_date.c
Labels: bug

#1703 [CBRD-23082] [10.1p3] avoid checking type if db_val is null (#1545)
  src/object/object_primitive.h
Labels: bug

#1704 [CBRD-23083] [10.1p3] fix free (page|sector) size of partition (#1540)
  src/storage/file_io.c
Labels: bug

#1700 [CBRD-23072] [JSON] Fix path validation
  src/compat/db_json_path.cpp
Labels: bug

#1689 [CBRD-22371] Insert multiple records at a time into heap
  CMakeLists.txt
  src/loaddb/load_common.hpp
  src/loaddb/load_grammar.yy
  src/loaddb/load_sa_loader.cpp
  src/loaddb/load_sa_loader.hpp
  src/loaddb/load_server_loader.cpp
  src/loaddb/load_server_loader.hpp
  src/loaddb/load_session.cpp
  src/storage/heap_file.c
  src/transaction/locator_sr.c
  src/transaction/locator_sr.h
Labels: task

#1705 [CBRD-23086] also update vacuum_Data_load.vpid_first when deallocates…
  src/query/vacuum.c
Labels: bug

#1706 [CBRD-23086] [10.1p3] also update vacuum_Data_load.vpid_first when deallocates…
  src/query/vacuum.c
Labels: bug

#1707 [CBRD-23090] do not update/reflect vacuum data last blockid on restoredb
  src/query/vacuum.c
  src/query/vacuum.h
  src/transaction/boot_sr.c
Labels: bug

#1708 [CBRD-23090] do not update/reflect vacuum data last blockid on restoredb
  src/query/vacuum.c
  src/query/vacuum.h
  src/transaction/boot_sr.c
Labels: bug

#1710 [CBRD-21948] skip dropped file notification during recovery
  src/query/vacuum.c
Labels: bug

#1711 [CBRD-22137] fix recovery of vacuum data page
  src/query/vacuum.c
Labels: bug

#1712 [CBRD-22692] fix pt_substitute_analytic_reference (#1524)
  src/parser/xasl_generation.c
Labels: bug

#1713 [CBRD-22805] fix disk_to_class missing error (#1510)
  src/object/transform_cl.c
  src/transaction/boot_cl.c
Labels: bug

#1714 [CBRD-22696] no MRO for aggregate queries (#1428)
  src/optimizer/plan_generation.c
Labels: bug

#1715 [CBRD-22638] Consider compression when computes length of nchar varyi…
  src/object/object_primitive.c
Labels: bug

#1716 [CBRD-22017] Fixed index of log page (#1375)
  src/transaction/log_page_buffer.c
Labels: bug

#1717 [CBRD-22594] Fix case of error during unique search (#1373)
  src/storage/btree.c
Labels: bug

#1718 [CBRD-22574] report invalid use of aggregate function (#1360)
  src/query/execute_statement.c
Labels: bug

#1719 [CBRD-22590] scan_next_index_lookup_heap: handle S_ERROR (#1358)
  src/query/scan_manager.c
Labels: bug

#1720 [CBRD-22484] backup failed with any other backup (#1349)
  src/transaction/log_page_buffer.c
Labels: bug

#1721 [CBRD-22550] forget error to determine return type of width_bucket (#…
  src/query/arithmetic.c
Labels: bug

#1723 [CBRD-22578] removes useless ordering clause for single tuple agg que…
  src/parser/semantic_check.c
Labels: bug

#1747 [CBRD-22164] fix vacuum_data_load_and_recover after copydb
  src/query/vacuum.c
Labels: bug

#1724 [CBRD-22441] do not interrupt fileio_expand_to (#1274)
  src/storage/disk_manager.c
  src/storage/file_io.c
Labels: bug

#1725 [CBRD-22621] Handle interrupt at file_dealloc (#1390)
  src/storage/extendible_hash.c
  src/storage/system_catalog.c
Labels: bug

#1726 [CBRD-22439] raises an error where mq_translate to subquery has a par…
  src/parser/xasl_generation.c
Labels: bug

#1727 [CBRD-22403] Core dumped in pt_uncorr_post (#1249)
  src/parser/xasl_generation.c
Labels: bug

#1728 [CBRD-22409] fix walking/copying union parser node (#1246)
  src/parser/parse_tree_cl.c
  src/parser/parser.h
  src/parser/semantic_check.c
Labels: bug

#1729 [CBRD-22396] fix potential ABW of cub_master (#1244)
  src/executables/master.c
Labels: bug

#1730 [CBRD-22394] pt_to_aggregate_node memory leak (#1241)
  src/parser/xasl_generation.c
Labels: bug

#1752 [CBRD-22345] vacuum consume iteration may allocate multiple data pages
  src/query/vacuum.c
Labels: bug

#1731 [CBRD-22398] forget coercion error of comparing incompatible domains …
  src/object/object_domain.c
Labels: bug

#1732 [CBRD-22718] Fixed reset sysop start LSA (#1455, #1227, #1209)
  src/transaction/log_recovery.c
Labels: bug

#1733 [CBRD-22327] fix vulerability of pt_eval_type_pre (#1204)
  src/parser/type_checking.c
Labels: bug

#1734 [CBRD-22266] expect allocated page for OLD_PAGE_DEALLOCATED (#1175)
  src/storage/page_buffer.c
Labels: bug

#1735 [CBRD-22260] undoredo logging for initializing new pages (#1174)
  src/storage/btree.c
  src/storage/extendible_hash.c
  src/storage/heap_file.c
  src/storage/system_catalog.c
  src/transaction/recovery.c
Labels: bug

#1736 [CBRD-22197] fix UMR of db_find_string_in_in_set (#1145)
  src/query/string_opfunc.c
Labels: bug

#1737 [CBRD-22157] client cached bad class locks for committed read transac…
  src/transaction/locator_cl.c
Labels: bug

#1738 [CBRD-22130] "show index" statements needs a table lock (#1111)
  src/storage/btree.c
Labels: bug

#1739 [CBRD-22127] safer decaching class mop from workspace (#1109)
  src/object/work_space.c
Labels: bug

#1740 [CBRD-22095] clearing deadlock victim also resets tran_abort_reason (…
  src/transaction/lock_manager.c
Labels: bug

#1742 [CBRD-22087] set connection error when a client properly receives it …
  src/connection/connection_cl.c
Labels: bug

#1743 [CBRD-21966] Make locale based on %VS150COMCOMNTOOLS% for VS2017 v150 (#1043, #1048)
  locales/make_locale_x64.bat
Labels: bug

#1744 [CBRD-21953] system generated select for client-side update has colum…
  src/parser/parse_tree_cl.c
  src/parser/xasl_generation.c
Labels: bug

#1745 [CBRD-21897] fix to avoid deadlock of "show indexes" (#1003)
  src/query/query_executor.c
  src/storage/statistics_sr.c
  src/storage/system_catalog.c
Labels: bug

#1746 [CBRD-21895] cci_set_cas_change_mode: fixes bad retry (#990)
  src/cci/cas_cci.c
Labels: bug

#1748 [CBRD-21862] IVR of mht_get_hash_number with zero length string (#986)
  src/base/memory_hash.c
Labels: bug

#1749 [CBRD-21860] (potential) FMR of do_insert_template (#984, #987, #988)
  src/object/object_template.c
  src/object/object_template.h
  src/query/execute_statement.c
Labels: bug

#1750 [CBRD-21861] UMR of tp_atof with zero length string (#985)
  src/object/object_domain.c
Labels: bug

#1751 [CBRD-22174] first boot after copydb
  src/query/vacuum.c
  src/query/vacuum.h
  src/transaction/boot_sr.c
  src/transaction/log_impl.h
  src/transaction/log_page_buffer.c
Labels: bug

#1753 [CBRD-23089] Fix windows compile
  src/query/vacuum.c
  src/transaction/boot_sr.c
Labels: bug

#1755 [CBRD-23104] [10.1p3] fix zero precision
  src/compat/db_macro.c
Labels: bug

#1756 [CBRD-23107] fix slip of file_extdata_collect_ftab_pages and fileio_expand_to
  src/storage/disk_manager.c
  src/storage/file_io.c
  src/storage/file_manager.c
  src/transaction/log_recovery.c
Labels: bug

#1761 [CBRD-23111] fix abbrev length in version string to 7 (#1520)
  CMakeLists.txt
  build.sh
Labels: build

#1759 [CBRD-23109] HA server state header
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/replication/ha_server_state.h
  src/transaction/boot.h
Labels: refactoring

#1757 [CBRD-23101] Fix crash during slave to master
  src/connection/server_support.c
Labels: bug

#1760 [CBRD-23110] Assign MVCCID if a transactions has replication objects
  src/replication/log_generator.cpp
Labels: bug

#1754 [CBRD-23102] Fixed slow unpacking stream entry
  src/base/stream_entry.hpp
  src/replication/log_generator.cpp
  src/replication/log_generator.hpp
Labels: bug

#1763 [CBRD-23113] Add getter for transaction descriptor replication generator
  src/query/query_executor.c
  src/query/serial.c
  src/replication/log_generator.cpp
  src/storage/heap_file.c
  src/transaction/locator_sr.c
  src/transaction/log_impl.h
  src/transaction/log_manager.c
  src/transaction/log_tran_table.c
  src/transaction/transaction_master_group_complete_manager.cpp
  src/transaction/transaction_sr.c
Labels: refactoring

#1762 [CBRD-23100] Implement a global worker pool for loaddb
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/communication/network_interface_sr.c
  src/loaddb/load_driver.cpp
  src/loaddb/load_driver.hpp
  src/loaddb/load_session.cpp
  src/loaddb/load_session.hpp
Labels: bug
