Repository CUBRID/cubrid, pull requests merged in 2019-02, with the labels that each got.

#1441 [CBRD-22726] assign new size to memory block when doing exponential realloc
  src/base/mem_block.cpp
Labels: bug

#1443 [CBRD-22721] Benchmark SQL function
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/func_type.cpp
  src/parser/type_checking.c
  src/parser/xasl_generation.c
  src/query/fetch.c
  src/query/fetch.h
  src/query/query_opfunc.c
  src/storage/storage_common.c
  src/storage/storage_common.h
Labels: enhancement

#1442 [CBRD-22651] overload json_object & json_array for empty args
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/parser/csql_grammar.y
  src/parser/func_type.cpp
  src/parser/type_checking.c
  src/query/arithmetic.c
Labels: bug

#1445 [CBRD-22708] special chars are not matched
  src/compat/db_json.cpp
Labels: bug

#1447 [CBRD-22697] change json_pretty output format for null values
  src/compat/db_json.cpp
Labels: bug

#1446 [CBRD-22674] fix case db_val's domain type is db_type_char
  src/compat/db_json.cpp
  src/compat/db_json.hpp
Labels: bug

#1453 [CBRD-22724] Json_array_insert expected error message is incorrect
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/base/error_code.h
  src/compat/db_json.cpp
Labels: bug

#1454 [CBRD-22636] Improper cast to json error message
  src/object/object_domain.c
Labels: bug

#1448 [CBRD-22695] json_merge inconsistency when null/incorrect json params
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/query/arithmetic.c
Labels: bug

#1431 [CBRD-22706] Multi-threaded online index builder
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/base/memory_private_allocator.hpp
  src/base/xserver_interface.h
  src/communication/network_interface_cl.c
  src/communication/network_interface_sr.c
  src/object/schema_manager.h
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/parse_tree.h
  src/parser/parser_message.h
  src/query/execute_schema.c
  src/query/query_opfunc.c
  src/query/query_opfunc.h
  src/storage/btree.h
  src/storage/btree_load.c
  src/thread/thread_manager.hpp
Labels: enhancement

#1452 [CBRD-22271] loaddb: implement missing types conversion
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  sa/CMakeLists.txt
  src/executables/utility.h
  src/loaddb/load_class_registry.cpp
  src/loaddb/load_class_registry.hpp
  src/loaddb/load_common.cpp
  src/loaddb/load_common.hpp
  src/loaddb/load_db_value_converter.cpp
  src/loaddb/load_db_value_converter.hpp
  src/loaddb/load_error_handler.cpp
  src/loaddb/load_error_handler.hpp
  src/loaddb/load_sa_loader.cpp
  src/loaddb/load_semantic_helper.cpp
  src/loaddb/load_server_loader.cpp
  src/loaddb/load_server_loader.hpp
  src/loaddb/load_session.cpp
Labels: enhancement

#1455 [CBRD-22718] Fixed reset sysop start LSA
  src/transaction/log_recovery.c
Labels: bug

#1458 [CBRD-22660] loaddb: fix line numbering
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/loaddb/load_common.cpp
  src/loaddb/load_common.hpp
  src/loaddb/load_db.c
  src/loaddb/load_db_value_converter.cpp
  src/loaddb/load_driver.cpp
  src/loaddb/load_driver.hpp
  src/loaddb/load_error_handler.cpp
  src/loaddb/load_error_handler.hpp
  src/loaddb/load_sa_loader.cpp
  src/loaddb/load_scanner.hpp
  src/loaddb/load_server_loader.cpp
  src/loaddb/load_session.cpp
  src/loaddb/load_session.hpp
Labels: enhancement

#1211 [CBRD-22004] stream file implementation
  cubrid/CMakeLists.txt
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  sa/CMakeLists.txt
  src/base/bip_buffer.hpp
  src/base/collapsable_circular_queue.hpp
  src/base/cubstream.cpp
  src/base/cubstream.hpp
  src/base/error_code.h
  src/base/multi_thread_stream.cpp
  src/base/multi_thread_stream.hpp
  src/base/stream_file.cpp
  src/base/stream_file.hpp
  src/base/stream_io.hpp
  src/replication/replication_master_node.cpp
  src/replication/replication_master_node.hpp
  src/replication/replication_master_senders_manager.cpp
  unit_tests/stream/test_main.cpp
  unit_tests/stream/test_stream.cpp
  unit_tests/stream/test_stream.hpp
Labels: task

#1459 [CBRD-22746] loaddb: handle SIGINT and SIGQUIT signals
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  src/communication/network.h
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/communication/network_interface_sr.h
  src/communication/network_sr.c
  src/loaddb/load_common.cpp
  src/loaddb/load_common.hpp
  src/loaddb/load_db.c
  src/loaddb/load_sa_loader.cpp
  src/loaddb/load_server_loader.cpp
  src/loaddb/load_session.cpp
  src/loaddb/load_session.hpp
Labels: enhancement
