Repository CUBRID/cubrid, pull requests merged in 2019-01, with the labels that each got.

#1423 [CBRD-22675] record_descriptor
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/storage/record_descriptor.cpp
  src/storage/record_descriptor.hpp
Labels: enhancement

#1424 [CBRD-22677] JSON_SEARCH leaked when json_path is not valid
  src/query/arithmetic.c
Labels: bug

#1425 [CBRD-22681] Fixed printing collation
  src/parser/parse_tree_cl.c
Labels: bug

#1428 [CBRD-22696] no MRO for aggregate queries
  src/optimizer/plan_generation.c
Labels: bug

#1429 [CBRD-22698] Accept json table resolved names
  src/parser/name_resolution.c
Labels: bug

#1427 [CBRD-22685] GCC < 4.9.0 std::regex is experimental
  CMakeLists.txt
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/query/arithmetic.c
  src/query/string_opfunc.c
  src/query/string_opfunc.h
Labels: bug

#1430 [CBRD-22699] Ordinality in nested path does not get reset
  src/query/scan_json_table.cpp
  src/xasl/access_json_table.cpp
  src/xasl/access_json_table.hpp
Labels: bug

#1432 [CBRD-22693] pr_type functions with const signatures
  cubrid/CMakeLists.txt
  src/base/event_log.c
  src/compat/db_date.h
  src/compat/db_macro.c
  src/compat/db_value_printer.cpp
  src/compat/db_value_printer.hpp
  src/executables/csql.h
  src/executables/csql_session.c
  src/executables/load_object.c
  src/executables/loader.c
  src/object/class_object.c
  src/object/object_accessor.c
  src/object/object_domain.c
  src/object/object_primitive.c
  src/object/object_primitive.h
  src/object/object_print.c
  src/object/object_print.h
  src/object/object_representation.c
  src/object/schema_manager.c
  src/object/schema_manager.h
  src/object/set_object.c
  src/object/transform_cl.c
  src/object/virtual_object.c
  src/object/work_space.c
  src/query/cursor.c
  src/query/execute_statement.c
  src/query/fetch.c
  src/query/list_file.c
  src/query/query_evaluator.c
  src/query/query_executor.c
  src/query/query_manager.c
  src/query/query_opfunc.c
  src/query/scan_manager.c
  src/storage/btree.c
  src/storage/btree.h
  src/storage/btree_load.c
  src/storage/catalog_class.c
  src/storage/external_sort.h
  src/storage/heap_file.c
  src/transaction/locator_sr.c
  src/transaction/log_applier.c
  src/transaction/transaction_cl.c
Labels: refactoring

#1435 [CBRD-22673] separate packer and unpacker
  src/base/packable_object.hpp
  src/base/packer.cpp
  src/base/packer.hpp
  src/base/stream_entry.hpp
  src/replication/replication_object.cpp
  src/replication/replication_object.hpp
  src/replication/replication_stream_entry.cpp
  src/replication/replication_stream_entry.hpp
  unit_tests/packing/test_packing.cpp
  unit_tests/packing/test_packing.hpp
  unit_tests/stream/test_stream.cpp
  unit_tests/stream/test_stream.hpp
Labels: refactoring

#1436 [CBRD-22717] fix ctltool build issue - help_class_names
  src/object/object_print.h
Labels: bug

#1433 [CBRD-22660] loaddb - implement class registry
  cubrid/CMakeLists.txt
  src/communication/network.h
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/communication/network_interface_sr.h
  src/communication/network_sr.c
  src/loaddb/load_class_registry.cpp
  src/loaddb/load_class_registry.hpp
  src/loaddb/load_common.cpp
  src/loaddb/load_common.hpp
  src/loaddb/load_db.c
  src/loaddb/load_driver.cpp
  src/loaddb/load_driver.hpp
  src/loaddb/load_error_handler.cpp
  src/loaddb/load_grammar.yy
  src/loaddb/load_sa_loader.cpp
  src/loaddb/load_sa_loader.hpp
  src/loaddb/load_server_loader.cpp
  src/loaddb/load_server_loader.hpp
  src/loaddb/load_session.cpp
  src/loaddb/load_session.hpp
Labels: enhancement

#1437 [CBRD-22673] Extend packer with overloaded/bulk functions
  src/base/packer.cpp
  src/base/packer.hpp
  unit_tests/packing/test_main.cpp
  unit_tests/packing/test_packing.cpp
  unit_tests/packing/test_packing.hpp
Labels: enhancement

#1421 [CBRD-22623] add autowrapping for various json functions
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/parser/semantic_check.c
  src/query/arithmetic.c
  src/query/string_opfunc.c
  src/query/string_opfunc.h
  src/xasl/access_json_table.cpp
Labels: bug
