Repository CUBRID/cubrid, pull requests merged in 2019-04, with the labels that each got.

#1515 [CBRD-22844] cast logpb_get_memsize () to INT64
  src/transaction/log_append.cpp
Labels: bug

#1510 [CBRD-22805] fix disk_to_class missing error
  src/object/transform_cl.c
  src/transaction/boot_cl.c
Labels: bug

#1516 [CBRD-22849] Stats ON system parameter
  src/base/perf_monitor.c
  src/base/perf_monitor.h
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/connection/server_support.c
Labels: enhancement

#1497 [CBRD-22806] Core dumped in fpcache_entry_uninit
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/query/filter_pred_cache.c
  src/query/partition.c
  src/query/partition_sr.h
  src/query/query_manager.c
  src/query/stream_to_xasl.c
  src/query/stream_to_xasl.h
  src/query/xasl.h
  src/query/xasl_cache.c
  src/query/xasl_cache.h
  src/query/xasl_to_stream.c
  src/storage/btree_load.c
  src/storage/heap_file.c
  src/storage/heap_file.h
  src/thread/thread_entry.hpp
  src/xasl/xasl_stream.cpp
  src/xasl/xasl_stream.hpp
  src/xasl/xasl_unpack_info.cpp
  src/xasl/xasl_unpack_info.hpp
Labels: bug

#1513 [CBRD-22822] Lob locator
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/xserver_interface.h
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/object/elo.c
  src/object/elo.h
  src/object/lob_locator.cpp
  src/object/lob_locator.hpp
  src/transaction/log_impl.h
  src/transaction/log_manager.c
  src/transaction/log_tran_table.c
  src/transaction/transaction_sr.c
  src/transaction/transaction_transient.cpp
  src/transaction/transaction_transient.hpp
Labels: refactoring

#1496 [CBRD-22804] Syntax check argument
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  src/executables/utility.h
  src/loaddb/load_db.c
  src/loaddb/load_error_handler.cpp
  src/loaddb/load_error_handler.hpp
  src/loaddb/load_scanner.hpp
  src/loaddb/load_server_loader.cpp
  src/loaddb/load_server_loader.hpp
  src/loaddb/load_session.cpp
  src/loaddb/load_session.hpp
Labels: enhancement

#1517 [CBRD-22798] Low performance of JSON_WALKER
  src/compat/db_json.cpp
  src/compat/db_json_path.cpp
  src/compat/db_json_path.hpp
  src/query/scan_json_table.cpp
  src/query/scan_json_table.hpp
Labels: bug

#1514 [CBRD-22784] Large json array index causes unclear invalid path error
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/base/error_code.h
  src/compat/db_json.cpp
  src/compat/db_json.hpp
  src/compat/db_json_path.cpp
  src/compat/db_json_path.hpp
  src/query/arithmetic.c
Labels: bug

#1520 [CBRD-22857] fix abbrev length in version string to 7
  CMakeLists.txt
  build.sh
  win/build.bat
Labels: build

#1519 [CBRD-22684] JSON_QUOTE wrong behavior for special character-strings
  src/compat/db_json_path.cpp
  src/query/arithmetic.c
  src/query/string_opfunc.c
  src/query/string_opfunc.h
Labels: bug

#1521 [CBRD-21524] fix some gcc8 warnings
  src/base/dtoa.c
  src/cci/cci_network.c
  src/communication/network_cl.c
  src/compat/db_date.c
  src/compat/db_macro.c
  src/compat/db_query.c
  src/compat/db_value_printer.cpp
  src/executables/unload_schema.c
  src/object/object_domain.c
  src/object/object_printer.cpp
  src/object/object_representation.c
  src/optimizer/plan_generation.c
  src/optimizer/query_graph.c
  src/parser/parse_dbi.c
  src/parser/parse_evaluate.c
  src/parser/parse_tree_cl.c
  src/parser/semantic_check.c
  src/parser/type_checking.c
  src/parser/view_transform.c
  src/parser/xasl_generation.c
  src/query/arithmetic.c
  src/query/fetch.c
  src/query/string_opfunc.c
  src/storage/es.c
  src/storage/heap_file.c
  src/transaction/boot_cl.c
  src/transaction/log_2pc.c
  src/transaction/log_applier.c
Labels: refactoring

#1450 [CBRD-22702] fail to execute view with single NESTED_PATH
  src/parser/parse_tree_cl.c
Labels: bug

#1444 [CBRD-22694] json_object crashed in build_query_graph_function_index
  src/optimizer/query_graph.c
Labels: bug

#1524 [CBRD-22692] pt_to_set_aptr stack overflow
  src/parser/xasl_generation.c
Labels: bug

#1526 [CBRD-22865] object_fetch.h
  src/base/tz_compile.c
  src/compat/db.h
  src/compat/db_admin.c
  src/compat/db_class.c
  src/compat/db_old.c
  src/compat/db_set.c
  src/compat/db_temp.c
  src/compat/db_vdb.c
  src/compat/db_virt.c
  src/executables/checksumdb.c
  src/executables/csql.c
  src/executables/unload_object.c
  src/jsp/jsp_cl.c
  src/object/authenticate.h
  src/object/object_accessor.h
  src/object/object_description.cpp
  src/object/object_fetch.h
  src/object/object_printer.cpp
  src/object/set_object.c
  src/object/virtual_object.c
  src/parser/compile.c
  src/parser/method_transform.c
  src/parser/name_resolution.c
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/parser_support.c
  src/parser/query_result.c
  src/parser/semantic_check.c
  src/parser/show_meta.c
  src/parser/type_checking.c
  src/parser/view_transform.c
  src/parser/xasl_generation.c
  src/query/execute_schema.c
  src/query/query_method.c
  src/transaction/locator_cl.c
  src/transaction/log_applier.c
Labels: refactoring

#1525 [CBRD-22672] json_table using host variable inconsistent behavior
  src/parser/semantic_check.c
  src/query/scan_json_table.cpp
Labels: bug

#1522 [CBRD-22853] extract schema buffer
  cs/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/printer.cpp
  src/base/printer.hpp
  src/compat/db_obj.c
  src/compat/db_value_printer.cpp
  src/compat/db_value_printer.hpp
  src/compat/dbtype.h
  src/executables/extract_schema.cpp
  src/executables/extract_schema.hpp
  src/executables/load_object.c
  src/executables/load_object.h
  src/executables/unload_object.c
  src/executables/unload_schema.c
  src/executables/unloaddb.c
  src/executables/unloaddb.h
  src/object/authenticate.c
  src/object/authenticate.h
  src/object/class_object.c
  src/object/object_print.c
  src/object/object_print.h
  src/object/trigger_description.cpp
  src/object/trigger_description.hpp
  src/object/trigger_manager.c
  src/object/trigger_manager.h
Labels: enhancement

#1529 [CBRD-22870] clear string_buffer contents on flush
  src/base/printer.cpp
  src/base/printer.hpp
Labels: bug

#1530 [CBRD-22596] fix JSON_TABLE scan status
  src/query/scan_json_table.cpp
  src/query/scan_json_table.hpp
  src/query/scan_manager.c
Labels: bug

#1501 [CBRD-22830] Kubernetes integration
  CMakeLists.txt
  contrib/cloud/Dockerfile
  contrib/cloud/README.md
  contrib/cloud/build.sh
  contrib/cloud/cubrid-statefulset.yaml
  contrib/cloud/rootfs/etc/ld.so.conf.d/cubrid.conf
  contrib/cloud/rootfs/usr/local/bin/entrypoint.sh
  src/base/porting.h
  src/compat/db_admin.c
  src/connection/tcp.c
  src/connection/tcp.h
  src/connection/wintcp.c
  src/connection/wintcp.h
  src/executables/util_common.c
  src/storage/file_io.c
  src/transaction/boot_cl.c
  src/transaction/transaction_cl.c
Labels: task

#1523 [CBRD-22828] MVCC table refactoring
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/extensible_array.hpp
  src/executables/unittests_snapshot.c
  src/storage/heap_file.c
  src/transaction/log_global.c
  src/transaction/log_impl.h
  src/transaction/log_manager.c
  src/transaction/log_recovery.c
  src/transaction/log_tran_table.c
  src/transaction/mvcc.c
  src/transaction/mvcc.h
  src/transaction/mvcc_active_tran.cpp
  src/transaction/mvcc_active_tran.hpp
  src/transaction/mvcc_table.cpp
  src/transaction/mvcc_table.hpp
Labels: refactoring

#1527 [CBRD-22869] Implement the --error-file-control argument on the server
  src/loaddb/load_common.cpp
  src/loaddb/load_common.hpp
  src/loaddb/load_db.c
  src/loaddb/load_error_handler.cpp
  src/loaddb/load_error_handler.hpp
  src/loaddb/load_object.c
  src/loaddb/load_object.h
  src/loaddb/load_server_loader.cpp
Labels: task

#1532 [CBRD-22867] Fix the periodic-commit argument
  src/loaddb/load_common.hpp
  src/loaddb/load_db.c
Labels: task

#1533 [CBRD-22874] [regression][ha] fix hostname/canonical name comparison
  src/executables/master_heartbeat.c
Labels: bug

#1535 [CBRD-22878] record_descriptor extends packable_object
  src/base/packer.cpp
  src/base/packer.hpp
  src/storage/record_descriptor.cpp
  src/storage/record_descriptor.hpp
Labels: task

#1536 [CBRD-22881] initialize offset in log_lsa::set_null
  src/transaction/log_lsa.hpp
Labels: bug

#1537 [CBRD-22882] mvcc_active_tran::copy_to thread safety
  src/transaction/mvcc.c
  src/transaction/mvcc_active_tran.cpp
  src/transaction/mvcc_active_tran.hpp
  src/transaction/mvcc_table.cpp
Labels: bug

#1539 [CBRD-22885] Fix building snapshot when copy fails.
  src/transaction/mvcc_active_tran.cpp
  src/transaction/mvcc_active_tran.hpp
  src/transaction/mvcc_table.cpp
Labels: bug

#1540 [CBRD-22886] fix free (page|sector) size of partition
  src/storage/file_io.c
Labels: bug

#1541 [CBRD-22896] SA_MODE: don't do checkpoint during sysop
  src/transaction/log_manager.c
  src/transaction/log_page_buffer.c
Labels: bug

#1542 [CBRD-22897] fix mvcc_active_tran::reset_active_transactions
  src/transaction/mvcc_active_tran.cpp
  src/transaction/mvcc_active_tran.hpp
Labels: bug

#1546 [CBRD-22900] Increase hostname length according to RFC1123
  src/base/databases_file.c
  src/base/error_manager.c
  src/base/porting.h
  src/base/system_parameter.c
  src/broker/broker.c
  src/broker/broker_admin_so.h
  src/broker/broker_shm.h
  src/cm_common/cm_dep_tasks.c
  src/cm_common/cm_portable.h
  src/communication/network_cl.c
  src/communication/network_interface_sr.c
  src/compat/db_admin.c
  src/connection/connection_cl.c
  src/connection/connection_defs.h
  src/connection/connection_sr.c
  src/connection/connection_support.c
  src/connection/heartbeat.h
  src/connection/server_support.c
  src/connection/wintcp.c
  src/executables/csql.c
  src/executables/master.c
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
  src/executables/master_request.c
  src/executables/util_common.c
  src/executables/util_cs.c
  src/executables/util_sa.c
  src/executables/util_service.c
  src/storage/es_owfs.c
  src/storage/file_io.c
  src/transaction/boot.h
  src/transaction/boot_cl.c
  src/transaction/boot_cl.h
  src/transaction/boot_sr.c
  src/transaction/client_credentials.cpp
  src/transaction/lock_manager.c
  src/transaction/log_applier.c
  src/transaction/transaction_cl.c
Labels: bug

#1545 [CBRD-22877] avoid checking type if db_val is null
  src/compat/dbtype.h
Labels: bug

#1548 [CBRD-22901] improve error handling on heartbeat req/resp
  src/executables/master_heartbeat.c
Labels: bug
