Repository CUBRID/cubrid, pull requests merged in 2020-07, with the labels that each got.

#2340 [CBRD-23679] Adding a configuration parameter and control for strict type translation
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/object/object_domain.c
  src/storage/heap_file.c
Labels: enhancement, task

#2367 [CBRD-23598] Even with LIMIT 1 in a scalar subquery that uses union all, "Query result contains more than a single tuple." Error occurred (#2178)
  src/optimizer/query_rewrite.c
Labels: bug

#2368 [CBRD-22925] An error occurs when there are two 'IN' operators and rewriting predicate to reduce the equality term. (#2185)
  src/optimizer/query_graph.c
  src/parser/parse_tree_cl.c
  src/parser/type_checking.c
Labels: bug

#2369 [CBRD-22979] Segmentation fault occurs when query has derived table with 3 or more unions (#2196)
  src/parser/query_result.c
Labels: bug

#2370 [CBRD-22970] Constant variable is set to null when reusing cached XASL which is executed without data(#2197)
  src/query/query_opfunc.c
Labels: bug

#2371 [CBRD-23618] Error occur when rewriting subquery into derived table in delete or update statement (#2200)
  src/optimizer/query_rewrite.c
  src/parser/parse_tree.h
Labels: bug

#2372 [CBRD-23623] Unexpected data overflow error occurs by order of select list when the numeric type and ROUND are used together (#2204)
  src/query/numeric_opfunc.c
Labels: bug

#2373 [CBRD-23605] Wrong results returning in some select queries which has aggregate function as select list by groupby clause. (#2208)
  src/query/query_aggregate.cpp
  src/query/query_aggregate.hpp
  src/query/query_executor.c
Labels: bug

#2374 [CBRD-23658] counting Error occurred when argument of COUNT function is constant 'NULL'.(#2296)
  src/parser/type_checking.c
Labels: bug

#2375 [CBRD-21886] No query results if DECODE, CASE, or IF is used in a nested left outer join query (#2315)
  src/optimizer/query_graph.c
  src/optimizer/query_graph.h
Labels: bug

#2376 [CBRD-21022] executeBatch returns Cannot communicate with the broker or received invalid packet & CAS down with core dump (#2323)
  src/parser/xasl_generation.c
  src/query/execute_statement.c
Labels: bug

#2377 [CBRD-23650] When a query specifying an OVER function in an aggregate function using rownum has a plan, the result is null. (#2343)
  src/optimizer/plan_generation.c
  src/parser/xasl_generation.c
  src/parser/xasl_generation.h
  src/query/query_executor.c
  src/query/stream_to_xasl.c
  src/query/xasl.h
  src/query/xasl_to_stream.c
Labels: bug

#2378 [CBRD-23696] Core dump occurs when correlated subquery is used as in-line view.(#2354)
  src/optimizer/query_graph.c
  src/optimizer/query_graph.h
Labels: bug

#2361 [CBRD-23697] occurred error "Cannot coerce value of domain character to domain integer" when executing update.
  src/parser/type_checking.c
  src/query/query_dump.c
Labels: bug

#2382 [CBRD-23697] occurred error "Cannot coerce value of domain character to domain integer" when executing update. (#2361)
  src/parser/type_checking.c
  src/query/query_dump.c
Labels: bug

#2381 [CBRD-23709] error message is displayed incorrectly in 'MERGE' clause
  src/query/query_executor.c
Labels: bug

#2366 [CBRD-21828] Process '.5' style number in loaddb_object as well as '0.5
  src/loaddb/load_db_value_converter.cpp
  src/loaddb/load_sa_loader.cpp
Labels: bug

#2365 [CBRD-23649] make dummy table instead of db_root
  src/object/authenticate.c
  src/object/transform.h
  src/parser/parser_support.c
  src/parser/xasl_generation.c
  src/transaction/boot_cl.c
Labels: enhancement

#2386 [CBRD-23712] support --skip-vacuum option at csql command on SA mode
  src/communication/network_sr.c
  src/compat/db_client_type.hpp
  src/executables/csql.c
  src/executables/csql.h
  src/executables/csql_launcher.c
  src/executables/utility.h
  src/transaction/boot.h
  src/transaction/boot_sr.c
  src/transaction/boot_sr.h
Labels: enhancement

#2390 [CBRD-23714] change an limit value of max_client
  src/connection/connection_globals.h
Labels: enhancement
