Repository CUBRID/cubrid, pull requests merged in 2020-04, with the labels that each got.

#2218 [CBRD-23243] Modify the way to caculate available disk space
  src/storage/file_io.c
Labels: bug

#2217 [CBRD-23631] Change the maximum value of the 'ha_apply_max_mem_size' property from 500MB to INT_MAX.
  src/base/system_parameter.c
  src/executables/util_cs.c
Labels: enhancement

#2221 [CBRD-22135] Improve performance when using serial in HA environment. (#2206)
  src/transaction/replication.c
Labels: enhancement

#2222 [CBRD-23609] Before failure-over due to disk failure, syslog was used to record information and the disk failure detection algorithm was improved in HA environment. (#2195 #2211)
  src/connection/server_support.c
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
  src/storage/file_io.c
  src/transaction/log_manager.c
  src/transaction/log_manager.h
Labels: enhancement

#2223 [CBRD-23604] The restart of copylogdb and applylogdb fail if the length of copied log file path is over 64. (#2193)
  src/connection/heartbeat.c
  src/connection/heartbeat.h
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
Labels: bug

#2224 [CBRD-23603] The ha_make_slavedb.sh script should delete intended database exactly. (#2187)
  contrib/scripts/ha/ha_make_slavedb.sh
Labels: bug

#2226 [CBRD-23640] backupdb also allows a FIFO (named pipe) file (#1078)
  src/executables/util_cs.c
  src/storage/file_io.c
Labels: enhancement

#2228 [CBRD-23609] Before failure-over due to disk failure, syslog was used to record information and the disk failure detection algorithm was improved in HA environment. (#2195 #2211)
  src/connection/server_support.c
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
  src/storage/file_io.c
  src/transaction/log_manager.c
  src/transaction/log_manager.h
Labels: enhancement

#2229 [CBRD-23604] The restart of copylogdb and applylogdb fail if the length of copied log file path is over 64. (#2193)
  src/connection/heartbeat.c
  src/connection/heartbeat.h
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
Labels: bug

#2230 [CBRD-23603] The ha_make_slavedb.sh script should delete intended database exactly. (#2187)
  contrib/scripts/ha/ha_make_slavedb.sh
Labels: bug

#2227 [APIS-822] In JDBC Driver, translating empty string to null when the option oracleStyleEmptyString is set.
  src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/jci/UStatement.java
Labels: enhancement

#2215 [CBRD-23626] Fix regression of #2207
  src/base/system_parameter.c
  src/base/system_parameter.h
Labels: regression

#2225 [CBRD-23631] Change the maximum value of the 'ha_apply_max_mem_size' property from 500MB to INT_MAX. (#2217)
  src/base/system_parameter.c
  src/executables/util_cs.c
Labels: enhancement

#2219 [CBRD-23633] Prevent endless busy waiting for query execution in abnormal network circumstance
  src/broker/broker.c
  src/broker/broker_shm.c
  src/broker/broker_shm.h
  src/broker/cas.c
  src/broker/cas_function.h
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/jci/UInputBuffer.java
  src/jdbc/cubrid/jdbc/jci/UTimedDataInputStream.java
  src/jdbc/cubrid/jdbc/net/BrokerHandler.java
Labels: enhancement

#2237 [CBRD-23611] multi bytes blank is padded in char data of the table set to euckr
  src/base/intl_support.c
  src/base/language_support.c
Labels: bug

#2242 [CBRD-21565] Add system parameter for Java SP server to apply JVM options
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/jsp/jsp_sr.c
Labels: enhancement

#2188 [CBRD-22975] Broker CAS hangs in CLIENT_WAIT status when log file size is greater than 2G on Windows 64
  src/base/porting.h
  src/broker/cas_log.c
Labels: bug

#2232 [CBRD-23243] Modify the way to caculate available disk space (#2218)
  src/storage/file_io.c
Labels: bug

#2233 [CBRD-23243] Modify the way to caculate available disk space (#2218)
  src/storage/file_io.c
Labels: bug

#2240 [CBRD-23617] Query specification from system catalog is not displayed correctly when the syntax for creating view exceeds 4K
  src/compat/dbtype.h
  src/transaction/boot_cl.c
Labels: bug

#2241 [CBRD-23617] Query specification from system catalog is not displayed correctly when the syntax for creating view exceeds 4K (#2201)
  src/compat/dbtype_def.h
  src/transaction/boot_cl.c
Labels: bug

#2255 [CBRD-21565] Add system parameter for Java SP server to apply JVM options (#2242)
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/jsp/jsp_sr.c
Labels: enhancement

#2244 [CBRD-23643] A hang occurs when exiting 'csql' after connecting to server through csql in standalone mode
  src/storage/file_manager.c
Labels: bug

#2256 [APIS-782] JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException
  src/broker/broker.c
  src/broker/cas_common.h
  src/broker/cas_function.h
  src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/net/BrokerHandler.java
Labels: enhancement

#2260 [CBRD-21023] [JDBC] Clob's length() returns -1 when empty string
  src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
Labels: bug

#2258 [APIS-822] In JDBC Driver, translating empty string to null when the option oracleStyleEmptyString is set
  src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/jci/UStatement.java
Labels: enhancement

#2259 [CBRD-23633] Prevent endless busy waiting for query execution in abnormal network circumstance (#2219, #2259)
  src/broker/broker.c
  src/broker/broker_shm.c
  src/broker/broker_shm.h
  src/broker/cas.c
  src/broker/cas_function.h
  src/broker/cas_protocol.h
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/jci/UInputBuffer.java
  src/jdbc/cubrid/jdbc/jci/UTimedDataInputStream.java
  src/jdbc/cubrid/jdbc/net/BrokerHandler.java
Labels: enhancement

#2262 [CBRD-23633] Prevent endless busy waiting for query execution in abnormal network circumstance (#2219, #2259)
  src/broker/broker.c
  src/broker/broker_shm.c
  src/broker/broker_shm.h
  src/broker/cas.c
  src/broker/cas_function.h
  src/broker/cas_protocol.h
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/jci/UInputBuffer.java
  src/jdbc/cubrid/jdbc/jci/UTimedDataInputStream.java
  src/jdbc/cubrid/jdbc/net/BrokerHandler.java
Labels: enhancement

#2253 [CBRD-22975] Broker CAS hangs in CLIENT_WAIT status when log file size is greater than 2G on Windows 64 (#2188)
  src/base/porting.h
  src/broker/cas_log.c
Labels: bug

#2254 [CBRD-22975] Broker CAS hangs in CLIENT_WAIT status when log file size is greater than 2G on Windows 64 (#2188)
  src/base/porting.h
  src/broker/cas_log.c
Labels: bug

#2267 [APIS-782] JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException (#2256)
  src/broker/broker.c
  src/broker/cas_common.h
  src/broker/cas_function.h
  src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/net/BrokerHandler.java
Labels: enhancement

#2270 [APIS-782] JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException (#2256)
  src/broker/broker.c
  src/broker/cas_common.h
  src/broker/cas_function.h
  src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/net/BrokerHandler.java
Labels: enhancement

#2220 [CBRD-23637] Implementation of secure CUBRID jdbc driver
  src/jdbc/cubrid/jdbc/driver/CUBRIDDriver.java
  src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/jci/UUnreachableHostList.java
  src/jdbc/cubrid/jdbc/net/BrokerHandler.java
Labels: enhancement

#2271 [CBRD-22862] fix cubridtray actions for Windows
  cmake/CPackWixPatch.cmake.in
  msg/de_DE.utf8/cubridtray.msg
  msg/en_US.utf8/cubridtray.msg
  msg/en_US/cubridtray.msg
  msg/es_ES.utf8/cubridtray.msg
  msg/fr_FR.utf8/cubridtray.msg
  msg/it_IT.utf8/cubridtray.msg
  msg/ja_JP.utf8/cubridtray.msg
  msg/km_KH.utf8/cubridtray.msg
  msg/ko_KR.euckr/cubridtray.msg
  msg/ko_KR.utf8/cubridtray.msg
  msg/ro_RO.utf8/cubridtray.msg
  msg/tr_TR.utf8/cubridtray.msg
  msg/vi_VN.utf8/cubridtray.msg
  msg/zh_CN.utf8/cubridtray.msg
Labels: bug

#2273 [CBRD-23611] multi bytes blank is padded in char data of the table set to euckr
  src/query/string_opfunc.c
Labels: enhancement

#2274 [CBRD-23611] multi bytes blank is padded in char data of the table set to euckr (#2273)
  src/query/string_opfunc.c
Labels: enhancement

#2277 [CBRD-23611] multi bytes blank is padded in char data of the table set to euckr (#2273)
  src/query/string_opfunc.c
Labels: enhancement

#2276 [CBRD-23637] Implementation of secure CUBRID jdbc driver
  src/jdbc/cubrid/jdbc/driver/CUBRIDDriver.java
  src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/jci/UUnreachableHostList.java
  src/jdbc/cubrid/jdbc/net/BrokerHandler.java
Labels: enhancement

#2279 [CBRD-23639] CAS change for SSL
  cubrid_broker.conf
  src/broker/cas.c
  src/broker/cas_network.c
  src/broker/cas_ssl.c
Labels: enhancement

#2283 [CBRD-22862] fix cubridtray actions for Windows (#2271)
  cmake/CPackWixPatch.cmake.in
  msg/de_DE.utf8/cubridtray.msg
  msg/en_US.utf8/cubridtray.msg
  msg/en_US/cubridtray.msg
  msg/es_ES.utf8/cubridtray.msg
  msg/fr_FR.utf8/cubridtray.msg
  msg/it_IT.utf8/cubridtray.msg
  msg/ja_JP.utf8/cubridtray.msg
  msg/km_KH.utf8/cubridtray.msg
  msg/ko_KR.euckr/cubridtray.msg
  msg/ko_KR.utf8/cubridtray.msg
  msg/ro_RO.utf8/cubridtray.msg
  msg/tr_TR.utf8/cubridtray.msg
  msg/vi_VN.utf8/cubridtray.msg
  msg/zh_CN.utf8/cubridtray.msg
Labels: bug

#2282 [CBRD-22862] fix cubridtray actions for Windows (#2271)
  cmake/CPackWixPatch.cmake.in
  msg/de_DE.utf8/cubridtray.msg
  msg/en_US.utf8/cubridtray.msg
  msg/en_US/cubridtray.msg
  msg/es_ES.utf8/cubridtray.msg
  msg/fr_FR.utf8/cubridtray.msg
  msg/it_IT.utf8/cubridtray.msg
  msg/ja_JP.utf8/cubridtray.msg
  msg/km_KH.utf8/cubridtray.msg
  msg/ko_KR.euckr/cubridtray.msg
  msg/ko_KR.utf8/cubridtray.msg
  msg/ro_RO.utf8/cubridtray.msg
  msg/tr_TR.utf8/cubridtray.msg
  msg/vi_VN.utf8/cubridtray.msg
  msg/zh_CN.utf8/cubridtray.msg
Labels: bug

#2284 [CBRD-23639] Change default SSL mode to OFF (cubrid_broker.conf)
  conf/cubrid_broker.conf
  src/broker/broker_config.h
Labels: enhancement

#2285 [CBRD-23637] change default useSSL value true to false.
  src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
  src/jdbc/cubrid/jdbc/jci/UUnreachableHostList.java
Labels: enhancement

#2293 [CBRD-23633] revised: client protocol version 7
  src/jdbc/cubrid/jdbc/jci/UConnection.java
Labels: enhancement
