Repository CUBRID/cubrid, pull requests merged in 2020-11, with the labels that each got.

#2479 [CBRD-23759] [Regression][ha_repl_debug] Core dumped in btree_get_prefix_separator
  src/object/object_primitive.c
  src/storage/btree.c
Labels: bug, regression

#2478 [CBRD-23756] [Regression] [sql] Core dumped in lang_get_w_first_el
  src/base/language_support.c
Labels: bug, regression

#2475 [CBRD-23754] Outer join is incorrectly changed to inner join in queries that contain OR operation.
  src/optimizer/query_rewrite.c
Labels: bug

#2483 [CBRD-23731] regression fixed: In data comparing, no ignoring to trailing spaces at the end of the data.
  src/base/language_support.c
  src/base/language_support.h
  src/base/system_parameter.c
  src/communication/network_interface_sr.c
  src/executables/util_sa.c
  src/object/object_domain.c
  src/object/object_primitive.c
  src/parser/parser_support.c
  src/parser/type_checking.c
  src/query/fetch.c
  src/query/scan_manager.c
  src/query/string_opfunc.c
  src/transaction/boot_cl.c
Labels: bug, enhancement, regression, task

#2482 [CBRD-23767] Index scan cannot be used in hierarchical queries when there is a value predicate like '1=1'
  src/optimizer/query_rewrite.c
  src/parser/parser_support.c
Labels: bug

#2443 [CBRD-23602] Statement/Result cache to improve performance for frequently repeated queries
  src/base/system_parameter.c
  src/communication/network_interface_sr.c
  src/compat/db_vdb.c
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSet.java
  src/jdbc/cubrid/jdbc/jci/UResCache.java
  src/jdbc/cubrid/jdbc/jci/UStatement.java
  src/query/execute_statement.c
  src/query/list_file.c
  src/query/list_file.h
  src/query/query_executor.c
  src/query/query_manager.c
  src/query/query_manager.h
  src/query/xasl_cache.c
  src/query/xasl_cache.h
  src/storage/file_manager.c
  src/transaction/log_manager.c
Labels: enhancement, in progress

#2486 [CBRD-23629] Fix slip of checking java_stored_procedure on standalone
  src/transaction/boot_sr.c
Labels: bug

#2490 [CBRD-23629] Fix assertion caused by getting prm with wrong type
  src/transaction/boot_sr.c
Labels: bug

#2488 [CBRD-23731] regression-revised: In data comparing, no ignoring to trailing spaces at the end of the data.
  src/base/language_support.c
  src/query/string_opfunc.c
Labels: bug, enhancement, regression, task

#2487 [CBRD-23770] Get explicitly specified libjvm path from JVM_PATH env variable
  src/executables/javasp.cpp
  src/executables/util_service.c
  src/jsp/jsp_file.c
  src/jsp/jsp_sr.c
Labels: enhancement

#2492 [CBRD-23754] Outer join is incorrectly changed to inner join in queries that contain OR operation.
  src/optimizer/query_rewrite.c
Labels: bug, regression

#2495 [CBRD-23789] increase the disk compatibility level.
  src/base/release_string.c
Labels: change disk image

#2489 [CBRD-23602] regression: Statement cache to improve performance for frequently repeated queries
  src/base/system_parameter.c
  src/query/list_file.c
  src/query/list_file.h
  src/query/query_executor.c
  src/query/query_manager.c
  src/query/query_manager.h
  src/query/xasl_cache.c
  src/session/session.c
  src/storage/file_manager.c
Labels: bug, enhancement, regression, task

#2491 [CBRD-23783] Fix incorrect domain definition is printed for SET of arbitrarily type
  src/parser/parse_tree_cl.c
Labels: bug

#2496 [CBRD-23792] Refactoring get cpu clock
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/get_clock_freq.c
  src/base/get_clockfreq.c
  src/base/tsc_timer.c
  src/base/tsc_timer.h
Labels: refactoring

#2498 [CBRD-23629] Slip, remove wrong message changes in en_US.utf8/utils.msg
  msg/en_US.utf8/utils.msg
Labels: task

#2500 [CBRD-23787] Memory leak in csession_create_prepared_statement()
  src/communication/network_interface_cl.c
Labels: bug

#2499 [CBRD-23788] Change declaration position of a character array
  src/executables/util_sa.c
Labels: bug

#2501 [CBRD-23629] Fix slip in cubridservice on windows
  src/win_tools/cubridservice/cubridservice.cpp
Labels: bug

#2502 [CBRD-23793] [Regression] Core dumped in db_string_unique_prefix
  src/query/string_opfunc.c
Labels: bug, regression

#2503 [CBRD-23786] Always loading system parameter in process_heartbeat_util()
  src/executables/util_service.c
Labels: bug

#2504 [CBRD-23797] [Regression] JDBC, in TYPE_SCROLL_SENSITIVE and in maxRows setting, exception fail
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSet.java
  src/jdbc/cubrid/jdbc/jci/UStatement.java
Labels: bug, regression

#2507 [CBRD-23795] [Regression] cub_server terminate after drop table query.
  src/query/xasl_cache.c
Labels: bug, regression

#2506 [CBRD-23796] some rewrite query was not found the character size
  src/parser/type_checking.c
Labels: bug
