Repository CUBRID/cubrid, pull requests merged in 2020-02, with the labels that each got.

#1647 [CBRD-22783] Add support for REGEXP_REPLACE function
  src/optimizer/query_graph.c
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/func_type.cpp
  src/parser/parser_support.c
  src/parser/type_checking.c
  src/parser/xasl_generation.c
  src/parser/xasl_regu_alloc.cpp
  src/query/fetch.c
  src/query/query_executor.c
  src/query/query_opfunc.c
  src/query/regu_var.cpp
  src/query/regu_var.hpp
  src/query/stream_to_xasl.c
  src/query/string_opfunc.c
  src/query/string_opfunc.h
  src/query/string_regex.cpp
  src/query/string_regex.hpp
  src/storage/storage_common.c
  src/storage/storage_common.h
  src/xasl/xasl_predicate.cpp
Labels: enhancement

#2187 [CBRD-23603] The ha_make_slavedb.sh script should delete intended database exactly.
  contrib/scripts/ha/ha_make_slavedb.sh
Labels: bug

#2191 [CBRD-23604] The restart of copylogdb and applylogdb fail if the length of copied log file path is over 64.
  src/connection/heartbeat.c
  src/connection/heartbeat.h
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
Labels: bug

#2193 [CBRD-23604] The restart of copylogdb and applylogdb fail if the length of copied log file path is over 64.
  src/connection/heartbeat.c
  src/connection/heartbeat.h
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
Labels: bug

#2189 [CBRD-23612] Fix memory leak of compiled regex and pattern
  src/query/string_opfunc.c
  src/query/string_regex.cpp
  src/query/string_regex.hpp
Labels: bug, regression

#2194 [CBRD-22783] Fix regression of #1647
  src/query/string_regex.cpp
Labels: bug, regression

#1564 [CBRD-22856] Support Row Value Constructor
  src/optimizer/plan_generation.c
  src/optimizer/query_graph.c
  src/optimizer/query_graph.h
  src/optimizer/query_planner.c
  src/optimizer/query_planner.h
  src/optimizer/query_rewrite.c
  src/parser/csql_grammar.y
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/type_checking.c
  src/parser/xasl_generation.c
Labels: enhancement

#1671 [CBRD-22837] REGEXP unicode-aware enhancement
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/locale_helper.cpp
  src/base/locale_helper.hpp
  src/query/string_opfunc.c
  src/query/string_regex.cpp
  src/query/string_regex.hpp
Labels: enhancement

#2198 [CBRD-22837] fix slip setting error when collation incompatible
  src/query/string_opfunc.c
Labels: bug

#2199 [CBRD-23616] Time change to start ci build.
  Jenkinsfile
Labels: build

#1709 [CBRD-23071] REGEXP_SUBSTR function
  src/optimizer/query_graph.c
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/func_type.cpp
  src/parser/parser_support.c
  src/parser/type_checking.c
  src/parser/xasl_generation.c
  src/query/fetch.c
  src/query/query_executor.c
  src/query/query_opfunc.c
  src/query/regu_var.cpp
  src/query/string_opfunc.c
  src/query/string_opfunc.h
  src/query/string_regex.cpp
  src/query/string_regex.hpp
  src/storage/storage_common.c
  src/storage/storage_common.h
  src/xasl/xasl_predicate.cpp
Labels: enhancement
