Repository CUBRID/cubrid, pull requests merged in 2020-10, with the labels that each got.

#2466 [CBRD-23747] Enhance error message etc if cubrid user doesn't have permission about /etc/hosts
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/connection/tcp.c
  src/executables/master_heartbeat.c
  src/executables/util_sa.c
  src/transaction/boot_cl.c
  src/transaction/boot_sr.c
Labels: enhancement

#2416 [CBRD-23732] Optional Statistics Estimation
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/object/schema_manager.c
  src/storage/statistics_sr.c
Labels: enhancement, task

#2469 [CBRD-23752] Case-insensitive handling of %class keyword in loaddb object
  src/loaddb/load_common.cpp
Labels: bug

#2472 [CBRD-23688] fix incorrect error code return
  src/cci/cci_network.c
Labels: bug

#2467 [CBRD-23678] Remove the HANG bug that occurred when the table name and column name are the same.
  src/parser/parse_tree_cl.c
Labels: bug

#2470 [CBRD-23715] Display SSL parameter in broker info
  src/broker/broker_config.c
Labels: bug

#2471 [CBRD-23753] Fix destroying Internal JDBC resources is not working and unexpected behavior
  src/jdbc/com/cubrid/jsp/ExecuteThread.java
  src/jdbc/cubrid/jdbc/jci/UServerSideConnection.java
  src/jdbc/cubrid/jdbc/jci/UStatementHandlerCache.java
  src/jsp/jsp_cl.c
Labels: bug

#2477 [CBRD-23752] Case-insensitive handling of %class keyword in loaddb ob…
  src/loaddb/load_common.cpp
Labels: bug

#2476 [CBRD-23731] revised (no collation add): no ignoring to trailing spaces at the end of the data
  conf/cubrid_locales.all.txt
  locales/data/ldml/common_collations.xml
  locales/data/ldml/common_collations_ti.xml
  locales/data/ldml/cubrid_de_DE.xml
  locales/data/ldml/cubrid_de_DE_ti.xml
  locales/data/ldml/cubrid_es_ES.xml
  locales/data/ldml/cubrid_es_ES_ti.xml
  locales/data/ldml/cubrid_fr_FR.xml
  locales/data/ldml/cubrid_fr_FR_ti.xml
  locales/data/ldml/cubrid_it_IT.xml
  locales/data/ldml/cubrid_it_IT_ti.xml
  locales/data/ldml/cubrid_ja_JP.xml
  locales/data/ldml/cubrid_ja_JP_ti.xml
  locales/data/ldml/cubrid_km_KH.xml
  locales/data/ldml/cubrid_km_KH_ti.xml
  locales/data/ldml/cubrid_ko_KR.xml
  locales/data/ldml/cubrid_ko_KR_ti.xml
  locales/data/ldml/cubrid_ro_RO.xml
  locales/data/ldml/cubrid_ro_RO_ti.xml
  locales/data/ldml/cubrid_tr_TR.xml
  locales/data/ldml/cubrid_tr_TR_ti.xml
  locales/data/ldml/cubrid_vi_VN.xml
  locales/data/ldml/cubrid_vi_VN_ti.xml
  locales/data/ldml/cubrid_zh_CN_ti.xml
  src/base/language_support.c
  src/base/language_support.h
  src/base/locale_support.c
  src/base/locale_support.h
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/object/object_domain.c
  src/object/object_primitive.c
  src/parser/parser_support.c
  src/parser/type_checking.c
  src/query/string_opfunc.c
  src/query/string_opfunc.h
Labels: refactoring, regression, task, test case revise required

#2463 [CBRD-23607] When updating a column itself using Java SP and there is a WHERE clause condition, if you do not use an index scan, an 'Accessing deleted object' error occurs
  src/parser/xasl_generation.c
Labels: bug

#2461 [CBRD-23629] Create utility for Java SP server
  conf/cubrid.conf
  conf/cubrid.conf.large
  conf/cubrid.conf.small
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  sa/CMakeLists.txt
  src/connection/server_support.c
  src/executables/javasp.cpp
  src/executables/util_service.c
  src/executables/utility.h
  src/jdbc/com/cubrid/jsp/ExecuteThread.java
  src/jdbc/com/cubrid/jsp/Server.java
  src/jdbc/com/cubrid/jsp/SpSecurityManager.java
  src/jsp/jsp_cl.c
  src/jsp/jsp_cl.h
  src/jsp/jsp_comm.c
  src/jsp/jsp_comm.h
  src/jsp/jsp_file.c
  src/jsp/jsp_file.h
  src/jsp/jsp_sr.c
  src/jsp/jsp_sr.h
  src/transaction/boot_sr.c
  src/win_tools/ctrlservice/ctrlservice.cpp
  src/win_tools/cubridservice/cubridservice.cpp
  util/CMakeLists.txt
  win/cubridsa/cubridsa.def
Labels: enhancement

#2474 [CBRD-23687] Add error message for both cert & pk were not found (SSL)
  src/broker/cas_ssl.c
Labels: task

#2480 [CBRD-23688] fix incorrect error code return
  src/cci/cci_network.c
Labels: bug
