Repository CUBRID/cubrid, pull requests merged in 2020-03, with the labels that each got.

#1565 [CBRD-21023] JDBC Driver patch for Clob's length() returns -1 for empty string
  src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
Labels: bug

#2202 [CBRD-23619] gcc and g++ version 8 to build Regex library
  .travis.yml
Labels: build

#2201 [CBRD-23617] Query specification from system catalog is not displayed correctly when the syntax for creating view exceeds 4K
  src/compat/dbtype_def.h
  src/transaction/boot_cl.c
Labels: bug

#2197 [CBRD-22970] Constant variable is set to null when reusing cached XASL which is executed without data
  src/query/query_opfunc.c
Labels: bug

#1722 [CBRD-23073] REGEXP_INSTR function
  src/optimizer/query_graph.c
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/func_type.cpp
  src/parser/parser_support.c
  src/parser/type_checking.c
  src/parser/xasl_generation.c
  src/query/fetch.c
  src/query/query_executor.c
  src/query/query_opfunc.c
  src/query/regu_var.cpp
  src/query/string_opfunc.c
  src/query/string_opfunc.h
  src/query/string_regex.cpp
  src/query/string_regex.hpp
  src/storage/storage_common.c
  src/storage/storage_common.h
Labels: enhancement

#1741 [CBRD-23084] REGEXP_COUNT function
  src/optimizer/query_graph.c
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/func_type.cpp
  src/parser/parser_support.c
  src/parser/type_checking.c
  src/parser/xasl_generation.c
  src/query/fetch.c
  src/query/query_executor.c
  src/query/query_opfunc.c
  src/query/regu_var.cpp
  src/query/string_opfunc.c
  src/query/string_opfunc.h
  src/query/string_regex.cpp
  src/query/string_regex.hpp
  src/storage/storage_common.c
  src/storage/storage_common.h
Labels: enhancement

#2203 [CBRD-23085] REGEXP_LIKE function
  src/optimizer/query_graph.c
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/func_type.cpp
  src/parser/parser_support.c
  src/parser/type_checking.c
  src/parser/xasl_generation.c
  src/query/fetch.c
  src/query/query_executor.c
  src/query/query_opfunc.c
  src/query/regu_var.cpp
  src/query/string_opfunc.c
  src/query/string_opfunc.h
  src/storage/storage_common.c
  src/storage/storage_common.h
Labels: enhancement

#2200 [CBRD-23618] Error occur when rewriting subquery into derived table in delete or update statement
  src/optimizer/query_rewrite.c
  src/parser/parse_tree.h
Labels: bug

#2204 [CBRD-23623] Unexpected data overflow error occurs by order of select list when the numeric type and ROUND are used together
  src/query/numeric_opfunc.c
Labels: bug

#2210 [CBRD-22793] Reuse compiled regex for better performance of url matching
  src/cci/cci_util.c
Labels: bug

#2206 [CBRD-22135] Improve performance when using serial in HA environment.
  src/transaction/replication.c
Labels: bug

#2195 [CBRD-23609] Send messages to the system logger when there is insufficient space in operating system device.
  src/connection/server_support.c
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
  src/storage/file_io.c
  src/transaction/log_manager.c
  src/transaction/log_manager.h
Labels: enhancement

#2207 [CBRD-23626] Add system parameter to specify port number for Java SP server
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/jdbc/com/cubrid/jsp/Server.java
  src/jsp/jsp_sr.c
Labels: enhancement

#2208 [CBRD-23605] Wrong results returning in some select queries which has aggregate function as select list by groupby clause.
  src/query/query_aggregate.cpp
  src/query/query_aggregate.hpp
  src/query/query_executor.c
Labels: bug

#2211 [CBRD-23609] fix build error on Windows
  src/transaction/log_manager.c
  src/transaction/log_manager.h
Labels: bug

#2212 [CBRD-22837] Fix matching blank character class for regex
  src/query/string_regex.hpp
Labels: bug, regression

#2214 [CBRD-21452] In set (Union, Intersection, Difference) query, recompil…
  src/parser/csql_grammar.y
  src/parser/view_transform.c
Labels: bug
