Repository CUBRID/cubrid, pull requests merged in 2020-12, with the labels that each got.

#2509 [CBRD-23800] [Regression] the query includes function related to serial is cached unnecessarily
  src/parser/csql_grammar.y
Labels: bug, enhancement, regression

#2505 [CBRD-23798] [Regression] some collation has wrong checked the null value
  src/base/language_support.c
Labels: bug, regression

#2508 [CBRD-23629] Fix regression of Java SP server utility
  src/executables/util_service.c
Labels: bug

#2511 [CBRD-23790] Fix to add a space between num and msg
  msg/ja_JP.utf8/cubrid.msg
Labels: bug

#2510 [CBRD-23736] add query-output and loaddb-output option to csql utility
  src/executables/csql_result_format.c
Labels: bug

#2514 [CBRD-23608] Fix to use --CS-mode for TDE
  src/executables/util_admin.c
  src/executables/utility.h
Labels: bug

#2513 [CBRD-23802] The 'ignore_trailing_space' system parameter's property becomes 'hidden'
  src/base/system_parameter.c
Labels: refactoring, task

#2515 [CBRD-23803] The parameters related to 'query_cache_mode' reconfigured to change the mode.
  src/base/system_parameter.c
  src/query/list_file.c
  src/query/query_manager.c
Labels: refactoring, task

#2481 [CBRD-23726] Add DDL Audit log
  broker/CMakeLists.txt
  cs/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/ddl_log.c
  src/base/ddl_log.h
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/broker/cas.c
  src/broker/cas_execute.c
  src/broker/cas_function.c
  src/executables/csql.c
  src/executables/csql_support.c
  src/loaddb/load_db.c
Labels: enhancement

#2519 [CBRD-23608] Close the vdes of backup key file after validation (restoredb)
  src/transaction/boot_sr.c
Labels: bug

#2516 [CBRD-23608] restoredb from FIFO with TDE
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  src/transaction/log_page_buffer.c
Labels: bug

#2517 [CBRD-23629] Fix usage of javasp is displayed by cubrid service status
  src/executables/util_service.c
Labels: bug

#2518 [CBRD-23629] Revise calling function on restarting javasp
  src/executables/util_service.c
Labels: bug

#2523 [CBRD-23809] [Regression] Decreased volume reuse rate.
  src/storage/file_manager.c
Labels: bug, enhancement, regression

#2525 [CBRD-23810] Improvement of DML and transaction processing for result-cache
  src/query/list_file.c
  src/query/list_file.h
  src/query/query_manager.c
  src/query/xasl_cache.c
Labels: enhancement, regression, task

#2521 [CBRD-23808] Core dumped in csql_execute_statements
  src/executables/csql.c
Labels: bug

#2524 [CBRD-23731] Regression: in prepare containing + '%' query cast as char which expected cast as varchar.
  src/parser/type_checking.c
Labels: bug, enhancement, regression, task

#2526 [CBRD-23608] Revise error handling and cleanup when applying tde to files fails
  src/query/query_manager.c
  src/storage/btree.c
  src/storage/file_manager.c
Labels: bug, refactoring

#2529 [CBRD-23629] Fix slip of javasp utility
  src/executables/javasp.cpp
  win/cubridsa/cubridsa.def
Labels: bug

#2512 [CBRD-23801] [Regression] In JDBC, the cursor forward and backward doesn't work.
  src/jdbc/cubrid/jdbc/driver/CUBRIDResultSet.java
  src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/jci/UJCIManager.java
  src/jdbc/cubrid/jdbc/jci/UResCache.java
  src/jdbc/cubrid/jdbc/jci/UStatement.java
  src/jdbc/cubrid/jdbc/jci/UStatementCacheData.java
  src/jdbc/cubrid/jdbc/jci/UStmtCache.java
  src/jdbc/cubrid/jdbc/jci/UUrlCache.java
Labels: bug, enhancement, regression

#2531 [CBRD-23804][Regression] Core dumped in btree_key_find_and_insert_delete_mvccid
  src/storage/btree.c
Labels: bug, enhancement, regression, task

#2527 [CBRD-23726] change to record ddl audit log in csql
  src/base/ddl_log.c
  src/base/ddl_log.h
  src/executables/csql.c
  src/loaddb/load_db.c
Labels: bug, enhancement

#2532 [CBRD-23725] Modification of return value due to abnormal behavior in…
  src/executables/unload_object.c
Labels: bug

#2520 [CBRD-23749] Support HASH LIST SCAN for Hierarchical Queries
  src/parser/xasl_generation.c
  src/query/query_executor.c
  src/query/xasl.h
Labels: enhancement, task

#2530 [CBRD-23810] Regression, DML and transaction processing for result-cache
  src/base/system_parameter.c
  src/query/list_file.c
  src/query/list_file.h
  src/query/query_manager.c
  src/query/xasl_cache.c
Labels: bug, enhancement, regression, task

#2533 [CBRD-23819] [Regression] Conditional jump or move depends on uninitialised value(s)
  src/transaction/replication.c
Labels: regression
