Repository CUBRID/cubrid, pull requests merged in 2020-06, with the labels that each got.

#2341 [CBRD-23677] The heartbeat fails to start when 'cubrid service start' command is executed successfully even though the settings are normal.
  src/executables/util_service.c
Labels: bug

#2342 [CBRD-23609] Remove modifications other than syslog () in #2195
  src/connection/server_support.c
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
  src/transaction/log_manager.c
  src/transaction/log_manager.h
Labels: bug

#2343 [CBRD-23650] When a query specifying an OVER function in an aggregate function using rownum has a plan, the result is null.
  src/optimizer/plan_generation.c
  src/parser/xasl_generation.c
  src/parser/xasl_generation.h
  src/query/query_executor.c
  src/query/stream_to_xasl.c
  src/query/xasl.h
  src/query/xasl_to_stream.c
Labels: bug

#2350 [CBRD-23687] Add server certificate/private key for SSL
  conf/CMakeLists.txt
  conf/cas_ssl_cert.crt
  conf/cas_ssl_cert.key
  conf/cubrid_broker.conf
Labels: enhancement

#2345 [CBRD-23680] temporary temp volume file is not cleared when server restarted with temp_volume_path option
  src/transaction/boot_sr.c
Labels: bug

#2251 [CBRD-23642] Change the way to handle the wrong backup time when executing restoredb
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/base/error_code.h
  src/base/msgcat_set_log.hpp
  src/transaction/log_page_buffer.c
Labels: bug

#2347 [CBRD-23686] If the number of index columns is large, the optimizer cannot select a more appropriate index.
  src/optimizer/query_planner.c
Labels: bug

#2346 [CBRD-23637] Implementation of secure CUBRID jdbc driver
  src/jdbc/cubrid/jdbc/driver/ConnectionProperties.java
  src/jdbc/cubrid/jdbc/jci/UClientSideConnection.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/jci/UErrorCode.java
  src/jdbc/cubrid/jdbc/jci/UUnreachableHostList.java
  src/jdbc/cubrid/jdbc/net/BrokerHandler.java
Labels: enhancement

#2353 [CBRD-23642] Relieve error severity with a wrong backup time
  src/transaction/log_page_buffer.c
Labels: bug

#2352 [CBRD-22637] Excessive domain cache degrades search performance using index scan
  src/storage/btree.c
Labels: enhancement

#2356 [CBRD-23602] processing in case that xasl clone is disable
  src/query/query_manager.c
Labels: enhancement, in progress, task

#2358 [CBRD-23669] Provide FULL SQL_Text, if tranlist executed with -f opti…
  src/executables/util_admin.c
  src/executables/util_cs.c
  src/executables/utility.h
Labels: enhancement

#2355 [CBRD-23671] Fix regression caused by not completing Resultset in ServerSidePreparedStatement
  src/jdbc/cubrid/jdbc/driver/CUBRIDServerSidePreparedStatement.java
  src/jsp/jsp_cl.c
Labels: bug, regression

#2354 [CBRD-23696] Core dump occurs when correlated subquery is used as in-line view.
  src/optimizer/query_graph.c
  src/optimizer/query_graph.h
Labels: bug

#2360 [CBRD-23637] Add error code for ssl handshake exception
  src/jdbc/cubrid/jdbc/jci/UClientSideConnection.java
  src/jdbc/cubrid/jdbc/jci/UErrorCode.java
  src/jdbc/cubrid/jdbc/net/BrokerHandler.java
Labels: enhancement
