Repository CUBRID/cubrid, pull requests merged in 2020-08, with the labels that each got.

#2392 [CBRD-23679] Adding a configuration parameter and control for strict type translation
  src/compat/db_macro.c
  src/object/object_domain.c
  src/object/object_domain.h
  src/optimizer/query_rewrite.c
  src/parser/xasl_generation.c
  src/query/execute_schema.c
  src/query/fetch.c
  src/query/query_executor.c
  src/query/query_opfunc.c
  src/query/regu_var.hpp
  src/query/string_opfunc.c
  src/storage/heap_file.c
Labels: enhancement, task

#2394 [CBRD-23714] change an limit value of max_clients
  src/base/system_parameter.c
  src/broker/broker_shm.h
Labels: enhancement

#2396 [CBRD-23714] ] change an limit value of max_clients
  src/base/system_parameter.c
  src/broker/broker_shm.h
  src/connection/connection_globals.h
Labels: enhancement

#2397 [CBRD-23679] Adding a configuration parameter and control for strict type translation
  src/parser/xasl_generation.c
Labels: in progress, regression, task

#2385 [CBRD-23708] change table option's default value to reuse_oid
  demo/demodb_schema
  demo/make_cubrid_demo.sh
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/executables/unload_schema.c
  src/object/object_printer.cpp
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/semantic_check.c
  src/query/execute_schema.c
Labels: enhancement

#2362 [CBRD-23688] Implementation of secure CUBRID CCI driver
  cci/CMakeLists.txt
  src/cci/cas_cci.c
  src/cci/cas_cci.h
  src/cci/cci_handle_mng.c
  src/cci/cci_handle_mng.h
  src/cci/cci_network.c
  src/cci/cci_network.h
  src/cci/cci_properties.c
  src/cci/cci_query_execute.c
  src/cci/cci_ssl.c
  src/cci/cci_ssl.h
Labels: enhancement

#2395 [APIS-833] Add isolation level 1,2,3 for backward compatibility
  src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDDatabaseMetaData.java
  src/jdbc/cubrid/jdbc/jci/CUBRIDIsolationLevel.java
  src/jdbc/cubrid/jdbc/jci/UClientSideConnection.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
Labels: enhancement

#2400 [CBRD-23687] Backport CBRD-23687 (#2387) to 10.2
  CMakeLists.txt
  src/broker/broker_config.c
  src/broker/broker_config.h
  src/broker/cas.c
  src/broker/cas_error.h
  src/broker/cas_network.c
  src/broker/cas_protocol.h
  src/broker/cas_ssl.c
  src/jsp/jsp_cl.c
Labels: backport

#2402 [APIS-833] Backport APIS-833(#2395) to 10.2
  src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDDatabaseMetaData.java
  src/jdbc/cubrid/jdbc/jci/CUBRIDIsolationLevel.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
Labels: backport

#2393 [CBRD-23637] fix to terminate the connection immediately when an ssl …
  src/jdbc/cubrid/jdbc/jci/UClientSideConnection.java
Labels: enhancement

#2403 [CBRD-23697] Fix regression caused by different domain of db_value
  src/parser/type_checking.c
  src/query/query_dump.c
Labels: bug, regression

#2404 [CBRD-23697] Fix regression caused by different domain of db_value (#2403)
  src/parser/type_checking.c
  src/query/query_dump.c
Labels: bug, regression

#2405 [CBRD-23708] change table option's default value to reuse_oid
  src/base/system_parameter.c
Labels: enhancement

#2407 [CBRD-23722] Prevent endless busy waiting for query execution in abnormal network circumstanec
  src/cci/cci_common.h
  src/cci/cci_network.c
Labels: enhancement

#2409 [CBRD-23730] ignore user and password option at tranlist and killtran utility
  src/executables/util_cs.c
Labels: enhancement

#2412 [CBRD-23685] coredump while insert something into column of type 'char (1073741823)'
  src/compat/dbtype_def.h
Labels: enhancement

#2413 [CBRD-23714] change an limit value of max_client
  src/base/system_parameter.c
Labels: enhancement

#2414 [CBRD-23714] change an limit value of max_client
  src/base/system_parameter.c
Labels: enhancement

#2417 [CBRD-23733] Add Microsoft_VCXXX_MFC_xXX.msm for MFC DLL
  CMakeLists.txt
  cmake/CPackWixPatch.cmake.in
Labels: bug

#2415 [CBRD-23729] Enhance compactdb utility
  cs/CMakeLists.txt
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  sa/CMakeLists.txt
  src/compat/db_client_type.hpp
  src/executables/compactdb.c
  src/executables/compactdb_cl.c
  src/executables/compactdb_common.c
  src/executables/util_admin.c
  src/executables/utility.h
  src/transaction/boot.h
Labels: enhancement

#2418 [CBRD-23733] Add Microsoft_VCXXX_MFC_xXX.msm for MFC DLL
  CMakeLists.txt
  cmake/CPackWixPatch.cmake.in
Labels: backport

#2419 [CBRD-23679] Adding a configuration parameter and control for strict type translation
  src/query/execute_schema.c
Labels: bug

#2423 [CBRD-23734] Core dumped in cubbase::restrack_assert at src/base/resource_tracker.hpp:456
  src/query/fetch.c
Labels: bug

#2424 [CBRD-23734] Core dumped in cubbase::restrack_assert at src/base/resource_tracker.hpp:456
  src/query/fetch.c
Labels: bug

#2427 Revert "[CBRD-23734] Core dumped in cubbase::restrack_assert at src/base/resource_tracker.hpp:456"
  src/query/fetch.c
Labels: regression

#2428 [CBRD-23734] Core dumped in cubbase::restrack_assert at src/base/resource_tracker.hpp:456
  src/query/query_executor.c
Labels: bug

#2426 Revert "[CBRD-23734] Core dumped in cubbase::restrack_assert at src/base/resource_tracker.hpp:456"
  src/query/fetch.c
Labels: regression

#2430 [CBRD-23733] Add update warning popup when os is Window 7
  cmake/CPackWixPatch.cmake.in
Labels: bug
