Repository CUBRID/cubrid, pull requests merged in 2020-05, with the labels that each got.

#2287 [CBRD-23653] subquery in 'EXISTS' operation retrieves the entire data and degrades the performance.
  src/parser/xasl_generation.c
  src/query/query_executor.c
  src/query/xasl.h
Labels: enhancement

#2296 [CBRD-23658] counting Error occurred when argument of COUNT function is constant 'NULL'.
  src/parser/type_checking.c
Labels: bug

#2298 [CBRD-23659] [Regression][cci compatibility] Type conversion error of cci_get_data()
  src/cci/cas_cci.h
  src/cci/cci_network.c
Labels: bug, enhancement, regression

#2295 [CBRD-23609] Change incorrectly patched code in #2228
  src/storage/file_io.c
Labels: bug

#2250 [CBRD-23638] Remove getpeername () calls, replace it with ip_addr in …
  src/cci/cci_network.c
Labels: enhancement

#2301 [CBRD-23638] Remove getpeername () calls, replace it with ip_addr in …
  src/cci/cci_network.c
Labels: enhancement

#2304 [APIS-782] revised: JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException
  src/jdbc/cubrid/jdbc/jci/UConnection.java
Labels: enhancement, regression

#2305 [APIS-782] revised: JDBC isValid() in CUBRIDConnection throws UnsupportedOperationException
  src/jdbc/cubrid/jdbc/jci/UConnection.java
Labels: enhancement, regression

#2311 [CBRD-23668] Change pop-up guide text for JRE when installing windows…
  cmake/CPackWixPatch.cmake.in
Labels: enhancement

#2316 [CBRD-23609] Remove modifications other than syslog () in #2228
  src/connection/server_support.c
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
  src/transaction/log_manager.c
  src/transaction/log_manager.h
Labels: bug

#2314 [CBRD-23609] Remove modifications other than syslog () in #2222.
  src/connection/server_support.c
  src/executables/master_heartbeat.c
  src/executables/master_heartbeat.h
  src/transaction/log_manager.c
  src/transaction/log_manager.h
Labels: bug

#2318 [CBRD-23669] Provide FULL SQL_Text, if tranlist executed with -f option
  src/executables/util_admin.c
  src/executables/util_cs.c
  src/executables/utility.h
Labels: enhancement

#2319 [CBRD-23613] Fix bug for SSL with jsp
  src/jsp/jsp_cl.c
Labels: enhancement

#2320 [CBRD-23639] Change TLS default
  src/broker/cas_ssl.c
  src/jdbc/cubrid/jdbc/net/BrokerHandler.java
Labels: enhancement

#2302 [CBRD-23638] Remove getpeername () calls, replace it with ip_addr in …
  src/cci/cci_network.c
Labels: enhancement

#2315 [CBRD-21886] No query results if DECODE, CASE, or IF is used in a nested left outer join query
  src/optimizer/query_graph.c
  src/optimizer/query_graph.h
Labels: bug

#2294 [CBRD-23647] Add system parameter for debugging Java SP and Server-side JDBC
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/jsp/jsp_sr.c
  src/jsp/jsp_sr.h
Labels: enhancement

#2325 [CBRD-23669] Provide FULL SQL_Text, if tranlist executed with -f opti…
  src/executables/util_admin.c
  src/executables/util_cs.c
  src/executables/utility.h
Labels: enhancement

#2303 [APIS-825] Supports ResultSet.getBlob() or ResultSet.getClob() method to read BIT VARYING type or VARCHAR type.
  src/jdbc/cubrid/jdbc/driver/CUBRIDBlob.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDLobHandle.java
  src/jdbc/cubrid/jdbc/jci/UGetTypeConvertedValue.java
  src/jdbc/cubrid/jdbc/jci/UInputBuffer.java
  src/jdbc/cubrid/jdbc/jci/UStatement.java
Labels: enhancement

#2328 [APIS-825] Supports ResultSet.getBlob() or ResultSet.getClob() method to read BIT VARYING type or VARCHAR type. (#2303)
  src/jdbc/cubrid/jdbc/driver/CUBRIDBlob.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDLobHandle.java
  src/jdbc/cubrid/jdbc/jci/UGetTypeConvertedValue.java
  src/jdbc/cubrid/jdbc/jci/UInputBuffer.java
  src/jdbc/cubrid/jdbc/jci/UStatement.java
Labels: enhancement

#2329 [APIS-825] Supports ResultSet.getBlob() or ResultSet.getClob() method to read BIT VARYING type or VARCHAR type. (#2303)
  src/jdbc/cubrid/jdbc/driver/CUBRIDBlob.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDClob.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDLobHandle.java
  src/jdbc/cubrid/jdbc/jci/UGetTypeConvertedValue.java
  src/jdbc/cubrid/jdbc/jci/UInputBuffer.java
  src/jdbc/cubrid/jdbc/jci/UStatement.java
Labels: enhancement

#2278 [CBRD-23648] Separate server-side routine in JDBC
  src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDConnectionDefault.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDDriver.java
  src/jdbc/cubrid/jdbc/driver/CUBRIDPooledConnection.java
  src/jdbc/cubrid/jdbc/jci/UClientSideConnection.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/jci/UError.java
  src/jdbc/cubrid/jdbc/jci/UJCIManager.java
  src/jdbc/cubrid/jdbc/jci/UServerSideConnection.java
  src/jdbc/cubrid/jdbc/jci/UStatement.java
Labels: refactoring, task

#2330 [CBRD-23243] Modify the way to calculate available disk space in sector unit
  src/storage/file_io.c
Labels: bug

#2331 [CBRD-23243] Modify the way to calculate available disk space in sector unit (#2330)
  src/storage/file_io.c
Labels: bug

#2332 [CBRD-23243] Modify the way to calculate available disk space in sector unit (#2330)
  src/storage/file_io.c
Labels: bug

#2323 [CBRD-21022] executeBatch returns Cannot communicate with the broker or received invalid packet & CAS down with core dump
  src/parser/xasl_generation.c
  src/query/execute_statement.c
Labels: bug

#2336 [APIS-782] revised: added an omitted code
  src/jdbc/cubrid/jdbc/jci/UConnection.java
Labels: bug, enhancement, regression

#2337 [APIS-782] revised: added omitted codes
  src/jdbc/cubrid/jdbc/driver/CUBRIDConnection.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
Labels: bug, enhancement, regression

#2312 [CBRD-20577] Use of alias with function inside ‘Order By’ Clause
  src/parser/name_resolution.c
Labels: bug, enhancement

#2339 [CBRD-23637] Changing the method of sending magicString for SSL
  src/jdbc/cubrid/jdbc/driver/CUBRIDDriver.java
  src/jdbc/cubrid/jdbc/jci/UConnection.java
  src/jdbc/cubrid/jdbc/net/BrokerHandler.java
Labels: enhancement
