Repository CUBRID/cubrid, pull requests merged in 2021-12, with the labels that each got.

#3157 [CBRD-24100] Problem that the view's order by is copied to the main query needlessly when view is merging.
  src/parser/view_transform.c
Labels: in progress

#3166 [CBRD-24110] Enhance performance for count(*) where no predicates
  src/base/xserver_interface.h
  src/parser/compile.c
  src/parser/show_meta.c
  src/query/query_aggregate.cpp
  src/query/query_executor.c
  src/storage/btree.c
  src/storage/btree.h
  src/storage/btree_load.c
  src/storage/btree_load.h
  src/storage/heap_file.c
  src/transaction/locator_sr.c
  src/transaction/log_impl.h
  src/transaction/log_tran_table.c
  src/transaction/mvcc_table.cpp
Labels: enhancement, in progress, legacy

#3279 [CBRD-24110] revised: Enhance performance for count(*) where no predicates
  src/storage/btree_load.c
Labels: bug
