Repository CUBRID/cubrid, pull requests merged in 2021-06, with the labels that each got.

#2821 [LETS-34] Wrap recovery information into log_recovery_context class.
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/query/vacuum.c
  src/query/vacuum.h
  src/transaction/log_append.cpp
  src/transaction/log_append.hpp
  src/transaction/log_recovery.c
  src/transaction/log_recovery.h
  src/transaction/log_recovery_context.cpp
  src/transaction/log_recovery_context.hpp
  unit_tests/log/CMakeLists.txt
Labels: refactoring

#2827 [LETS-34] Move recovery analysis code to log_recovery_analysis files
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/transaction/log_impl.h
  src/transaction/log_page_buffer.c
  src/transaction/log_recovery.c
  src/transaction/log_recovery_analysis.cpp
  src/transaction/log_recovery_analysis.hpp
Labels: refactoring

#2832 [LETS-34] Group all corruption checking related info & code into corruption_checker
  src/transaction/log_impl.h
  src/transaction/log_page_buffer.c
  src/transaction/log_recovery_analysis.cpp
  src/transaction/log_writer.c
Labels: refactoring

#2829 [CBRD-23978] execute command returns error in prepared statement includes DECODE
  src/parser/type_checking.c
Labels: bug, legacy

#2824 [CBRD-23968] dblink: type casting and proper error handling
  msg/en_US/cubrid.msg
  src/base/error_code.h
  src/query/dblink_scan.c
  src/query/execute_schema.c
  src/query/query_executor.c
Labels: enhancement, task

#2856 [CBRD-23991] Clear the session information including holdable cursor when CAS connection is down
  src/communication/network_sr.c
  src/session/session.c
  src/session/session.h
Labels: bug, enhancement, legacy
