Repository CUBRID/cubrid, pull requests merged in 2021-05, with the labels that each got.

#2776 [CBRD-23907] POC: implementation of DBLink by cci
  .gitignore
  cubrid/CMakeLists.txt
  src/cci/cas_cci.h
  src/optimizer/query_graph.c
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/keyword.c
  src/parser/name_resolution.c
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/semantic_check.c
  src/parser/view_transform.c
  src/parser/xasl_generation.c
  src/parser/xasl_regu_alloc.cpp
  src/query/dblink_scan.c
  src/query/dblink_scan.h
  src/query/query_dump.c
  src/query/query_executor.c
  src/query/scan_manager.c
  src/query/scan_manager.h
  src/query/stream_to_xasl.c
  src/query/xasl.h
  src/query/xasl_to_stream.c
Labels: enhancement, in progress, task

#2792 [LETS-100] Remove start/end checkpoint log records related code
  src/transaction/log_2pc.c
  src/transaction/log_2pc.h
  src/transaction/log_append.cpp
  src/transaction/log_applier.c
  src/transaction/log_checkpoint_info.cpp
  src/transaction/log_checkpoint_info.hpp
  src/transaction/log_impl.h
  src/transaction/log_manager.c
  src/transaction/log_page_buffer.c
  src/transaction/log_record.hpp
  src/transaction/log_recovery.c
Labels: refactoring

#2786 [CBRD-23948] To CREATE a table as WITH cte query, the alias of attributes should be checked.
  src/parser/semantic_check.c
Labels: bug

#2814 [CBRD-23874] The function IFNULL returns incorrect data type at the query with numeric host-variables
  src/parser/semantic_check.c
Labels: bug, legacy
