Repository CUBRID/cubrid, pull requests merged in 2021-02, with the labels that each got.

#2557 [LETS-1] Set the version to 12.0
  VERSION
Labels: task

#2537 [CBRD-23828] Support the use of OID of temp file in HASH LIST SCAN.
  src/base/memory_hash.c
  src/base/memory_hash.h
  src/parser/type_checking.c
  src/query/query_hash_scan.c
  src/query/query_hash_scan.h
  src/query/scan_manager.c
Labels: enhancement, task

#2558 [LETS-5] Add server_type system parameter
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/server_type.cpp
  src/base/server_type.hpp
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/loaddb/load_error_handler.cpp
  src/transaction/boot_sr.c
Labels: task

#2563 [CBRD-22856] fix to avoid compilation warning
  src/parser/type_checking.c
Labels: bug, regression

#2562 [LETS-15] page_server_hosts system parameter
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/base/error_code.h
  src/base/server_type.cpp
  src/base/system_parameter.c
  src/base/system_parameter.h
Labels: enhancement

#2566 [LETS-17] incorrect test against mvcc flag in log recovery
  src/transaction/log_recovery.c
Labels: bug

#2565 [LETS-18] Separate TCP and UNIX socket open
  src/connection/tcp.c
  src/connection/tcp.h
  src/connection/wintcp.c
  src/connection/wintcp.h
  src/executables/master.c
  win/cubridcs/cubridcs.def
Labels: refactoring

#2572 [LETS-24] Handle SA_MODE server_type & communication channels
  sa/CMakeLists.txt
  src/base/server_type.cpp
Labels: build

#2571 [CBRD-23854] When using /*+ USE_SBR */, an error occurs on the slave node.
  src/query/execute_statement.c
Labels: bug, legacy, regression, task

#2570 [CBRD-23865] Hierarchical query execution time difference between V11 and V10.2 occurs when using SQL hints /*+ no_hash_list_scan */
  src/parser/parse_tree.h
  src/parser/xasl_generation.c
Labels: bug, regression

#2569 [CBRD-23859] ROUND()'s result of decimal data type is wrong
  src/query/arithmetic.c
Labels: bug, legacy

#2576 [LETS-16] Add client-server classes handling requests over network
  CMakeLists.txt
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  src/communication/communication_channel.cpp
  src/communication/communication_channel.hpp
  src/communication/request_client_server.hpp
  unit_tests/CMakeLists.txt
  unit_tests/request_client_server/CMakeLists.txt
  unit_tests/request_client_server/comm_channel_mock.cpp
  unit_tests/request_client_server/comm_channel_mock.hpp
  unit_tests/request_client_server/test_main.cpp
Labels: task

#2575 [CBRD-23850] coredump occurs when heap_get_visible_version_from_log() function is called after executing backupdb with -r option.
  src/transaction/log_page_buffer.c
Labels: bug

#2580 [LETS-26] Synchronize pushing requests and automate sending
  cubrid/CMakeLists.txt
  src/communication/request_client_server.hpp
  src/communication/request_sync_send_queue.hpp
  unit_tests/request_client_server/CMakeLists.txt
  unit_tests/request_client_server/comm_channel_mock.cpp
  unit_tests/request_client_server/comm_channel_mock.hpp
  unit_tests/request_client_server/test_main.cpp
Labels: task
