Repository CUBRID/cubrid, pull requests merged in 2021-04, with the labels that each got.

#2625 [CBRD-23879] Outer dependency is set improperly when rewriting SQL from outer join to inner join
  src/optimizer/query_graph.c
  src/optimizer/query_graph.h
  src/optimizer/query_planner.c
Labels: enhancement, legacy

#2657 [CBRD-23899] Fix errors detected by cppcheck in api, broker and cci
  src/api/cci_stub.c
  src/broker/broker_log_util.c
  src/broker/broker_process_size.c
  src/broker/cas_dbms_util.c
  src/broker/shard_metadata.c
Labels: bug, refactoring

#2665 [CBRD-23891] Fix num_instance for loaddb cs
  src/loaddb/load_session.cpp
Labels: bug

#2611 [CBRD-23877] To CREATE a table as SELECT query, the alias of attributes should be checked.
  src/parser/semantic_check.c
Labels: enhancement, legacy, task

#2612 [CBRD-23878] To prevent setting the precision to -1 for STRING type as derived attribute
  src/object/object_domain.h
  src/query/execute_schema.c
Labels: bug, legacy

#2559 [CBRD-23856] Adding mutex for result-cache to process multi-threaded transaction
  src/query/list_file.c
  src/query/list_file.h
  src/query/query_manager.c
  src/query/xasl_cache.c
Labels: bug, legacy, regression, task

#2670 [CBRD-23905] Enhance Index scan performance
  src/base/language_support.c
  src/base/language_support.h
  src/object/object_primitive.c
  src/query/query_manager.c
  src/query/scan_manager.c
  src/query/scan_manager.h
  src/query/string_opfunc.h
  src/storage/btree.c
  win/cubridcs/cubridcs.def
  win/cubridsa/cubridsa.def
Labels: enhancement
