Repository CUBRID/cubrid, pull requests merged in 2021-01, with the labels that each got.

#2536 [CBRD-23827] Policy changing to disable result-cache in default.
  src/base/system_parameter.c
Labels: enhancement, task

#2535 [CBRD-23812] [Regression] The results of two queries that scan different indexes in the same transaction are different.
  src/object/object_domain.c
  src/object/object_primitive.c
  src/parser/parser_support.c
  src/query/string_opfunc.c
  src/storage/btree.c
Labels: bug, enhancement, regression

#2538 Revert "[CBRD-23812] [Regression] The results of two queries that scan different indexes in the same transaction are different."
  src/object/object_domain.c
  src/object/object_primitive.c
  src/parser/parser_support.c
  src/query/string_opfunc.c
  src/storage/btree.c
Labels: bug

#2540 [CBRD-23678] support to keywords when using /*+ USE_SBR */ hint.
  src/query/execute_statement.c
Labels: bug

#2539 [CBRD-23812] [revised] The results of two queries that scan different indexes in the same transaction are different.
  src/object/object_domain.c
  src/object/object_primitive.c
  src/parser/csql_grammar.y
  src/parser/parser_support.c
  src/parser/type_checking.c
  src/query/string_opfunc.c
Labels: bug, enhancement, regression

#2543 [CBRD-22803] Fixed the performance degradation in the wips workload of the TPC-W benchmark.
  src/storage/page_buffer.c
Labels: regression

#2544 [CBRD-23649] Get rid of warnings due to data type
  src/transaction/boot_cl.c
Labels: bug

#2547 [CBRD-23830] [Regression] [shell_ext] Core dumped in do_prepare_select
  src/query/execute_statement.c
Labels: bug

#2546 [CBRD-23608] [regression] Modified to be able to change master key in Windows environment.
  src/executables/util_cs.c
  src/storage/tde.c
  src/transaction/log_page_buffer.c
Labels: bug, enhancement

#2542 [CBRD-23812] [Regression] The results of two queries that scan different indexes in the same transaction are different.
  src/compat/db_vdb.c
  src/object/object_domain.c
  src/object/object_primitive.c
  src/parser/csql_grammar.y
  src/parser/parse_dbi.c
  src/parser/parser_support.c
  src/parser/type_checking.c
  src/query/string_opfunc.c
Labels: bug, enhancement, task

#2548 [CBRD-23733] add windows security patch update notification popup when cubrid install
  cmake/CPackWixPatch.cmake.in
Labels: bug

#2545 [CBRD-23587] Add sym link of libncurses.so.6 to libncurses.so.5 for C…
  cmake/CPack.STGZ_Header.sh.in
  cmake/CPack_postinstall.sh.in
  contrib/rpm/cubrid.sh
Labels: build

#2550 [CBRD-23833] Changing default character set to utf8 for demodb in Windows
  demo/make_cubrid_demo.bat
Labels: task

#2549 [CBRD-23831] Some collection-related (has VARCHAR elements) query returns incorrect result
  src/parser/type_checking.c
Labels: bug

#2551 [CBRD-23608] bug fix in PR#2546
  src/storage/tde.c
Labels: bug

#2552 [CBRD-23587] Fix OS identification error - fedota
  cmake/CPack.STGZ_Header.sh.in
  contrib/rpm/cubrid.sh
Labels: bug

#2553 [CBRD-23825] change comment such as copyright and license
  msg/de_DE.utf8/cubrid.msg
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/cubrid.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/cubrid.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/cubrid.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/cubrid.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/cubrid.msg
  msg/zh_CN.utf8/utils.msg
  src/base/release_string.c
Labels: bug

#2554 [CBRD-23834] Add inst script to add .cubrid.sh exec script to .bash_p…
  cmake/CPack.STGZ_Header.sh.in
Labels: task

#2555 [CBRD-23587] Change shell script symbolic link test condition from -f…
  cmake/CPack.STGZ_Header.sh.in
  contrib/rpm/cubrid.sh
Labels: bug

#2556 [CBRD-23834] Change the way to find bash as login shell
  cmake/CPack.STGZ_Header.sh.in
Labels: bug
