Repository CUBRID/cubrid, pull requests merged in 2021-03, with the labels that each got.

#2591 [LETS-39] perfmon_initialize() with one transaction in CS/SA mode
  src/base/perf_monitor.c
  src/transaction/boot_cl.c
  src/transaction/log_append.cpp
  unit_tests/log_transfer/test_main_prior_list_serialize.cpp
Labels: regression

#2585 [CBRD-23870] occurred core dump when getting the specific system parameter at csql
  src/base/system_parameter.c
Labels: bug

#2592 [CBRD-21446] Installing CUBRID with zip on Windows, cubrid server start fail.
  contrib/CMakeLists.txt
  contrib/windows_scripts/cubrid_env.bat
Labels: bug

#2595 [CBRD-21446] Installing CUBRID with zip on Windows, cubrid server start fail.
  contrib/CMakeLists.txt
  contrib/windows_scripts/cubrid_env.bat
Labels: bug

#2594 [CBRD-21446] Installing CUBRID with zip on Windows, cubrid server start fail.
  contrib/CMakeLists.txt
  contrib/windows_scripts/cubrid_env.bat
Labels: bug

#2601 [CBRD-23850] coredump occurs when heap_get_visible_version_from_log() function is called after executing backupdb with -r option. (#2575)
  src/transaction/log_page_buffer.c
Labels: backport, bug

#2602 [CBRD-23850] coredump occurs when heap_get_visible_version_from_log() function is called after executing backupdb with -r option. (#2575)
  src/transaction/log_page_buffer.c
Labels: backport, bug

#2603 [CBRD-23850] coredump occurs when heap_get_visible_version_from_log() function is called after executing backupdb with -r option. (#2575)
  src/transaction/log_page_buffer.c
Labels: backport, bug

#2600 [CBRD-23860] Do broker Keywords validation check
  src/broker/broker_config.c
Labels: enhancement

#2617 [CBRD-23883] Change keyword to JDBC_CACHE_ONLY_HINT
  src/broker/broker_admin_pub.c
  src/broker/broker_config.c
Labels: bug

#2618 [CBRD-23860] Change broker keyword JDBC_CACHE_HINT_ONLY
  src/broker/broker_admin_pub.c
  src/broker/broker_config.c
Labels: bug

#2630 [CBRD-23890] Fix order of update statistics of loaddb CS
  src/loaddb/load_class_registry.hpp
Labels: enhancement

#2629 [CBRD-23881] Add a new option to the vacuumdb utility to output the smallest log page ID and log volume name referenced by vacuum
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  src/communication/network.h
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/communication/network_interface_sr.h
  src/communication/network_sr.c
  src/executables/util_admin.c
  src/executables/util_cs.c
  src/executables/utility.h
  src/query/vacuum.c
  src/query/vacuum.h
Labels: enhancement, task

#2632 [CBRD-23860] Two broker keywords, SQL_LOG2, SHARD, are added by QA re…
  src/broker/broker_config.c
Labels: enhancement

#2639 [CBRD-23860] Add a broker keyword, SHARD_NUM_PROXY
  src/broker/broker_config.c
Labels: enhancement

#2637 [CBRD-23881] Add a new option to the vacuumdb utility to output the smallest log page ID and log volume name referenced by vacuum (#2629)
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  src/communication/network.h
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/communication/network_interface_sr.h
  src/communication/network_sr.c
  src/executables/util_admin.c
  src/executables/util_cs.c
  src/executables/utility.h
  src/query/vacuum.c
  src/query/vacuum.h
Labels: enhancement, task

#2636 [CBRD-23881] Add a new option to the vacuumdb utility to output the smallest log page ID and log volume name referenced by vacuum (#2629)
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  src/communication/network.h
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/communication/network_interface_sr.h
  src/communication/network_sr.c
  src/compat/db_client_type.hpp
  src/executables/util_admin.c
  src/executables/util_cs.c
  src/executables/utility.h
  src/query/vacuum.c
  src/query/vacuum.h
  src/transaction/boot.h
  src/transaction/boot_sr.c
  src/transaction/boot_sr.h
Labels: enhancement, task

#2640 [CBRD-23881] Add a new option to the vacuumdb utility to output the smallest log page ID and log volume name referenced by vacuum (#2629)
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  src/communication/network.h
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/communication/network_interface_sr.h
  src/communication/network_sr.c
  src/compat/db.h
  src/executables/util_admin.c
  src/executables/util_cs.c
  src/executables/utility.h
  src/query/vacuum.c
  src/query/vacuum.h
  src/transaction/boot.h
  src/transaction/boot_sr.c
  src/transaction/boot_sr.h
Labels: enhancement, task

#2645 [CBRD-23860] Add broker keywords, SHARD_PROXY_LOG, SHARD_PROXY_LOG_DIR
  src/broker/broker_config.c
Labels: enhancement

#2641 [CBRD-21446] Installing CUBRID with zip on Windows, cubrid server start fail.
  contrib/windows_scripts/cubrid_env.bat
Labels: bug

#2643 [CBRD-21446] Installing CUBRID with zip on Windows, cubrid server start fail.
  contrib/windows_scripts/cubrid_env.bat
Labels: bug

#2644 [CBRD-21446] Installing CUBRID with zip on Windows, cubrid server start fail.
  contrib/windows_scripts/cubrid_env.bat
Labels: bug

#2652 [CBRD-23901] Remove the hidden property of the dont_reuse_heap_file system parameter.
  src/base/system_parameter.c
Labels: bug

#2653 [CBRD-23901] Remove the hidden property of the dont_reuse_heap_file system parameter. (#2652)
  src/base/system_parameter.c
Labels: bug

#2654 [CBRD-23901] Remove the hidden property of the dont_reuse_heap_file system parameter. (#2652)
  src/base/system_parameter.c
Labels: bug

#2655 [CBRD-23901] Remove the hidden property of the dont_reuse_heap_file system parameter. (#2652)
  src/base/system_parameter.c
Labels: bug
