Repository CUBRID/cubrid, pull requests merged in 2021-11, with the labels that each got.

#3121 [CBRD-24088] Assert_release error occurred when creating index (#3107 back port to 11.1)
  src/query/string_opfunc.c
Labels: bug, regression

#3142 [CBRD-24097] Could not lookup the result cache entry for a query predicates with rownum.
  src/base/memory_hash.c
Labels: bug, regression

#3077 [CBRD-23843] Create CAS ODBC Gateway for DBLink
  CMakeLists.txt
  broker/CMakeLists.txt
  conf/cubrid_broker.conf
  msg/en_US/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  src/base/error_code.h
  src/broker/broker_admin_so.c
  src/broker/broker_config.c
  src/broker/broker_config.h
  src/broker/broker_filename.h
  src/broker/broker_shm.c
  src/broker/broker_shm.h
  src/broker/cas.c
  src/broker/cas_cgw.c
  src/broker/cas_cgw.h
  src/broker/cas_execute.c
  src/broker/cas_execute.h
  src/broker/cas_function.c
  src/broker/cas_function.h
  src/broker/cas_handle.c
  src/broker/cas_handle.h
  src/query/dblink_scan.c
Labels: enhancement, task

#3144 [CBRD-23842] Fixed memory leaks in server-side processing for CDC
  src/communication/network_interface_sr.c
  src/transaction/log_manager.c
Labels: bug

#3159 [CBRD-24109] No error produced for recursive triggering in SA mode.
  src/object/work_space.c
Labels: bug, regression

#3199 [CBRD-24119] server corrupted while executing connect by query
  src/query/query_opfunc.c
Labels: bug, legacy

#3200 [CBRD-24119] server corrupted while executing connect by query (#3199)
  src/query/query_opfunc.c
Labels: bug, legacy, backport
