Repository CUBRID/cubrid, pull requests merged in 2022-10, with the labels that each got.

#3820 [CBRD-24505] fix assert for a migration tool to 11.2
  src/base/object_representation.h
  src/storage/catalog_class.c
Labels: task

#3866 [CBRD-24505] fix assert for a migration tool to 11.2 (#3820)
  src/base/object_representation.h
  src/storage/catalog_class.c
Labels: backport

#3862 [CBRD-24422] When an error occurs in update_class(), it is not initialized to NULL after classobj_free_template() is executed, so core occurs later. (#3711)
  src/object/schema_manager.c
Labels: backport

#3863 [CBRD-24435] When renaming a view, even if there is a not null constraint, change it so that no error occurs. (#3744)
  src/query/execute_schema.c
Labels: backport

#3853 [CBRD-24422] When an error occurs in update_class(), it is not initialized to NULL after classobj_free_template() is executed, so core occurs later. (#3711)
  src/object/schema_manager.c
Labels: backport

#3856 [CBRD-24435] When renaming a view, even if there is a not null constraint, change it so that no error occurs. (#3744)
  src/query/execute_schema.c
Labels: backport

#3854 [CBRD-24422] When an error occurs in update_class(), it is not initialized to NULL after classobj_free_template() is executed, so core occurs later. (#3711)
  src/object/schema_manager.c
Labels: backport

#3857 [CBRD-24435] When renaming a view, even if there is a not null constraint, change it so that no error occurs. (#3744)
  src/query/execute_schema.c
Labels: backport

#3855 [CBRD-24422] When an error occurs in update_class(), it is not initialized to NULL after classobj_free_template() is executed, so core occurs later. (#3711)
  src/object/schema_manager.c
Labels: backport

#3858 [CBRD-24435] When renaming a view, even if there is a not null constraint, change it so that no error occurs. (#3744)
  src/query/execute_schema.c
Labels: backport

#3859 [CBRD-24464] CREATE SERVER must be done before ADD QUERY to the view. (#3778)
  src/executables/unload_schema.c
Labels: backport

#3864 [CBRD-24371] In alter synonym, comments can be changed without a for clause, and empty string comments become NULL. (#3694)
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/parser/csql_grammar.y
  src/parser/parse_tree_cl.c
  src/parser/parser_message.h
  src/parser/parser_support.c
  src/parser/semantic_check.c
  src/query/execute_statement.c
Labels: backport

#3861 [CBRD-24431] In synccoll_check and tzc_update functions, not only class_name but also owner_name should be compared. (#3774)
  src/base/tz_compile.c
  src/executables/util_sa.c
Labels: backport

#3868 [CBRD-24431] Add a join for the missing _db_index_key and separate the owner name and object name in the resulting file from syncolldb. (#3823)
  src/base/dynamic_array.c
  src/base/dynamic_array.h
  src/executables/util_sa.c
Labels: backport

#3844 [CBRD-24504] When an error occurs in a function that uses a buffer to convert an identifier name, the buffer must be initialized.
  src/object/schema_manager.c
Labels: bug

#3870 [CBRD-24510] When data is deleted and the MIN, MAX function of the indexed column is called, the result value is strange.
  src/storage/btree.c
Labels: bug, regression
