Repository CUBRID/cubrid, pull requests merged in 2022-07, with the labels that each got.

#3666 [CBRD-24401] In case of using UNION in an IN clause in an inline view, a segment fault occurs
  src/parser/type_checking.c
Labels: bug, legacy

#3716 [CBRD-24401] In case of using UNION in an IN clause in an inline view, a segment fault occurs (#3666)
  src/parser/type_checking.c
Labels: bug, backport

#3717 [CBRD-24392] After an index is created, filtering index is created, but not vice versa. (#3661)
  src/object/class_object.c
Labels: bug, backport

#3722 [CBRD-24372] Add new client type for loaddb to resolve migration issue by user schema. (#3636)
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/compat/db_client_type.hpp
  src/loaddb/load_db.c
  src/loaddb/load_sa_loader.cpp
  src/loaddb/load_server_loader.cpp
  src/loaddb/load_session.cpp
  src/object/trigger_manager.c
  src/parser/name_resolution.c
  src/parser/semantic_check.c
  src/query/execute_statement.c
  src/transaction/locator_cl.c
Labels: backport

#3723 [CBRD-24384] The core occurs if the user drops a synonym for which the target object is dropped. (#3690)
  src/communication/network_interface_cl.c
  src/query/execute_statement.c
Labels: backport

#3724 [CBRD-24424] When the pt_set_user_specified_name function is called in the show statement, a core dump occurs because the continue_walk argument is NULL. (#3712)
  src/parser/parser_support.c
Labels: backport

#3705 [CBRD-24420] dblink: correct oracle syntax error in rewritten query.
  src/parser/view_transform.c
Labels: bug

#3731 [CBRD-24420] dblink: correct oracle syntax error in rewritten query (backport to 11.2). (#3705)
  src/parser/view_transform.c
Labels: bug, backport

#3725 [CBRD-24428] dblink: correct error message for repeated query execution
  src/query/dblink_scan.c
Labels: bug, regression

#3734 [CBRD-24428] dblink: correct error message for repeated query execution (#3725) (backport to 11.2.1)
  src/query/dblink_scan.c
Labels: bug, backport
