Repository CUBRID/cubrid, pull requests merged in 2022-11, with the labels that each got.

#3943 [CBRD-24119] server corrupted while executing connect by query (#3199)
  src/query/query_opfunc.c
Labels: bug, regression

#3892 [CBRD-24516] replace the information which is printed in "show trace" from aggregate function optimization
  src/query/query_executor.c
  src/query/scan_manager.c
  src/query/scan_manager.h
Labels: task

#3952 [CBRD-24493] Reduce repeated subqueries in the system view (virtual class) (Bug fixed).
  src/transaction/boot_cl.c
Labels: bug

#3937 [CBRD-24554] incorrect result of "NOT EXISTS" and "NOT IN" with sub-query returning null
  src/parser/parse_tree.h
  src/parser/type_checking.c
Labels: bug

#3957 [CBRD-24545] Can not create a lot of statements within one transaction
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/query/query_manager.c
Labels: enhancement, task

#3919 [CBRD-24537] Improve the performance of MERGE query by using NOT EXISTS sub-query
  src/parser/xasl_generation.c
Labels: enhancement

#3959 [CBRD-24564] reflect reuse-oid option in error message prining at view updating query.
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/parser/parse_tree.h
  src/parser/parser_message.h
  src/parser/view_transform.c
Labels: task
