Repository CUBRID/cubrid, pull requests merged in 2022-06, with the labels that each got.

#3662 [CBRD-24391] Add primary key to code table on demodb
  demo/demodb_schema
Labels: enhancement, legacy

#3675 [CBRE-24401] backport: In case of using UNION in an IN clause in an inline view, a segment fault occurs
  src/parser/query_result.c
  src/parser/type_checking.c
Labels: bug, legacy

#3684 [CBRD-24401] backport to 11.0, In case of using UNION in an IN clause in an inline view, a segment fault occurs
  src/parser/query_result.c
  src/parser/type_checking.c
Labels: bug, legacy, backport

#3661 [CBRD-24392] After an index is created, filtering index is created, but not vice versa.
  src/object/class_object.c
Labels: bug, regression

#3693 [CBRD-24385] Revert: Clean up unused items after creating with xehas_create()
  src/storage/system_catalog.c
  src/storage/system_catalog.h
  src/transaction/boot_sr.c
Labels: revert
