Repository CUBRID/cubrid, pull requests merged in 2022-05, with the labels that each got.

#3593 [CBRD-23974] refined 'not supported type message' for dblink
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/broker/cas_cgw.c
  src/query/dblink_scan.c
Labels: bug, regression, legacy

#3596 [CBRD-23974] refined - not supported type message for dblink
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
Labels: bug, regression

#3609 [CBRD-24344] [Regression] Core dumped in cubbase::restrack_assert
  src/query/dblink_scan.c
Labels: bug, regression, legacy

#3614 [CBRD-24347] [Regression] [shell_ext] When executing sql with valgrind, Invalid free() / delete / delete[] / realloc() occurs.
  cubrid/CMakeLists.txt
  src/query/dblink_scan.c
Labels: regression, legacy

#3621 [CBRD-23974] correct dblink error message and remove rewritten print
  src/parser/view_transform.c
  src/query/dblink_scan.c
Labels: bug, regression
