Repository CUBRID/cubrid, pull requests merged in 2023-10, with the labels that each got.

#4688 [CBRD-24009] Plan cache is not updated when view changes including inline view. (#2915)
  src/parser/view_transform.c
Labels: backport

#4743 [CBRD-25046] typo error in jsp_sr.c
  src/jsp/jsp_sr.c
Labels: bug, legacy

#4748 [CBRD-25046] typo error in jsp_sr.c (#4743)
  src/jsp/jsp_sr.c
Labels: bug, legacy, backport

#4749 [CBRD-25046] typo error in jsp_sr.c (#4743)
  src/jsp/jsp_sr.c
Labels: bug, legacy, backport

#4750 [CBRD-25046] typo error in jsp_sr.c (#4743)
  src/jsp/jsp_sr.c
Labels: bug, legacy, backport
