Repository CUBRID/cubrid, pull requests merged in 2023-01, with the labels that each got.

#4021 [CBRD-24598] Memory allocated on the global heap must be freed on the global heap. (#4015)
  src/query/query_evaluator.c
Labels: backport

#4022 [CBRD-24598] Memory allocated on the global heap must be freed on the global heap. (#4015)
  src/query/query_evaluator.c
Labels: backport

#4002 [CBRD-24584] Improved to minimize the impact of query execution speed when setting sql_trace_slow
  src/base/perf_monitor.c
  src/base/perf_monitor.h
  src/base/xserver_interface.h
  src/communication/network_interface_sr.c
Labels: enhancement, task

#4030 [CBRD-24615] Result value error when using query cache in partition table
  src/transaction/locator_sr.c
Labels: bug, regression

#4052 [CBRD-24429] Not allowed multiple foreign keys on a column attribute (#3733)
  src/object/class_object.c
Labels: backport

#4054 [CBRD-24600] Problem with creating the same index with different names (#4020)
  src/object/class_object.c
  src/object/class_object.h
Labels: backport

#4045 [CBRD-24598] Memory allocated on the global heap must be freed on the global heap. (#4015)
  src/query/query_evaluator.c
Labels: backport

#4043 [CBRD-24609] When loading objects files online, if the schema name is not specified, the schema name of the current session must be used. (#4026)
  src/loaddb/load_server_loader.cpp
Labels: backport

#4047 [CBRD-24573] Among the SERVER information, dbname and user can be input as a string type (#3989)
  msg/de_DE.utf8/cubrid.msg
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/es_ES.utf8/cubrid.msg
  msg/fr_FR.utf8/cubrid.msg
  msg/it_IT.utf8/cubrid.msg
  msg/ja_JP.utf8/cubrid.msg
  msg/km_KH.utf8/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  msg/ro_RO.utf8/cubrid.msg
  msg/tr_TR.utf8/cubrid.msg
  msg/vi_VN.utf8/cubrid.msg
  msg/zh_CN.utf8/cubrid.msg
  src/executables/unload_schema.c
  src/parser/csql_grammar.y
  src/parser/parser_message.h
  src/query/execute_statement.c
Labels: backport

#4048 [CBRD-24581] Assert occurs when using indexes using IFNULL(), NULLIF() functions (#4005)
  src/query/scan_manager.c
Labels: backport

#4049 [CBRD-24582] Assert occurred during Loose index scan operation (#4006)
  src/object/object_primitive.c
  src/storage/btree.c
Labels: backport

#4050 [CBRD-24594] fix pr_midxkey_add_elements() (#4012)
  src/object/object_primitive.c
  src/object/object_primitive.h
Labels: backport

#4051 [CBRD-24597] fix coerce strict with char to numeric (#4016)
  src/object/object_domain.c
Labels: backport

#4058 [CBRD-24615] Result value error when using query cache in partition table
  src/transaction/locator_sr.c
Labels: backport

#4064 [CBRD-24609] When loading object files online, system class/vclass does not use the schema name of the current session. (#4063)
  src/executables/util_common.c
  src/executables/utility.h
  src/loaddb/load_server_loader.cpp
Labels: backport

#4028 [CBRD-24615] Result value error when using query cache in partition table
  src/transaction/locator_sr.c
Labels: bug, regression
