Repository CUBRID/cubrid, pull requests merged in 2023-06, with the labels that each got.

#4370 [CBRD-24516] rev: replace the information which is printed in "show trace" from aggregate function optimization
  src/query/query_executor.c
  src/query/scan_manager.c
  src/query/scan_manager.h
Labels: enhancement, task

#4421 [CBRD-24844] Garbage value when querying bit varying(n) column using DBLINK.
  src/query/dblink_scan.c
Labels: bug, regression

#4424 [CBRD-24516] multi-aggregate-optimize: replace the information which is printed in "show trace" from aggregate function optimization
  src/query/query_executor.c
  src/query/scan_manager.c
  src/query/scan_manager.h
Labels: task

#4431 [CBRD-24806] The use of synonyms is not allowed in the update statistics statement (#4362)
  src/parser/semantic_check.c
Labels: backport

#4430 [CBRD-24698] Change table names to lowercase in pt_resolve_showstmt_args_unnamed (#4423)
  src/parser/parser_support.c
Labels: backport
