Repository CUBRID/cubrid, pull requests merged in 2023-07, with the labels that each got.

#4465 [CBRD-24684] fix mis-modified: divide operation result into numeric type
  src/parser/view_transform.c
Labels: invalid

#4454 [CBRD-24516] regression: bug-fix
  src/query/scan_manager.c
Labels: bug, regression

#4450 [CBRD-24867] regression bug-fix related to DBLINK (DML and extended table specification)
  src/parser/parse_tree_cl.c
  src/parser/parser_support.c
Labels: bug, regression

#4484 [CBRD-24883] combine with oracle_style_number_return parameter
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/parser/parser_support.c
  src/parser/type_checking.c
  src/query/numeric_opfunc.c
  src/query/query_opfunc.c
Labels: task

#4490 [CBRD-24516] separate agl-index-list: replace the information which is printed in "show trace" from aggregate function optimization
  src/query/scan_manager.c
Labels: task, regression

#4478 [CBRD-24881] division operation bug for limit and offset
  src/parser/csql_grammar.y
  src/parser/parser_support.c
Labels: bug, regression

#4488 [CBRD-24867] rev: regression bug-fix related to DBLINK - alias check, DELETE query check
  src/parser/name_resolution.c
  src/parser/parse_tree.c
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/parser.h
  src/parser/parser_support.c
  src/parser/view_transform.c
Labels: bug, regression

#4520 [CBRD-24906] The problem of performing a cross join by changing to the '0 <> 0' condition when the WHERE clause is always false (#4510)
  src/parser/parser.h
  src/parser/type_checking.c
Labels: backport

#4518 [CBRD-24906] The problem of performing a cross join by changing to the '0 <> 0' condition when the WHERE clause is always false (#4510)
  src/parser/parser.h
  src/parser/type_checking.c
Labels: backport

#4519 [CBRD-24906] The problem of performing a cross join by changing to the '0 <> 0' condition when the WHERE clause is always false (#4510)
  src/parser/parser.h
  src/parser/type_checking.c
Labels: backport
