Repository CUBRID/cubrid, pull requests merged in 2023-04, with the labels that each got.

#4238 [CBRD-24734] ERROR -1042 (concat string size max size) error on SP query with NVL2
  src/parser/name_resolution.c
Labels: bug

#4252 [CBRD-24734] ERROR -1042 (concat string size max size) error on SP query with NVL2 (#4238)
  src/parser/name_resolution.c
Labels: bug, backport

#4036 [CBRD-24501] extending dblink dml
  cs/CMakeLists.txt
  src/compat/db_vdb.c
  src/optimizer/query_graph.c
  src/parser/compile.c
  src/parser/csql_grammar.y
  src/parser/name_resolution.c
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/parser.h
  src/parser/parser_support.c
  src/parser/semantic_check.c
  src/parser/view_transform.c
  src/parser/xasl_generation.c
  src/parser/xasl_generation.h
  src/query/dblink_scan.c
  src/query/dblink_scan.h
  src/query/execute_schema.h
  src/query/execute_statement.c
  src/query/execute_statement.h
  src/query/query_executor.c
Labels: enhancement, task

#4253 [CBRD-24734] ERROR -1042 (concat string size max size) error on SP query with NVL2 (#4238)
  src/parser/name_resolution.c
Labels: bug, backport

#4273 [CBRD-24753] If the schedule is already registered in Install, hang occurs on windows installer.
  cmake/CPackWixPatch.cmake.in
Labels: backport

#4272 [CBRD-24753] If the schedule is already registered in Install, hang occurs on windows installer.
  cmake/CPackWixPatch.cmake.in
Labels: backport

#4282 [CBRD-24705] When attempting a covered index scan in a connect by query, encountering 'Execute: Query execution failure' (#4237)
  src/query/query_executor.c
Labels: backport

#4290 [CBRD-24735] When attempting 'Multiple Key Ranges Optimization (MRO)', An internal error occurs because the '1=1' predicate (data filer) generated by constant folding is not removed (#4240)
  src/parser/parser.h
  src/parser/type_checking.c
Labels: backport

#4291 [CBRD-24735] When attempting 'Multiple Key Ranges Optimization (MRO)', An internal error occurs because the '1=1' predicate (data filer) generated by constant folding is not removed (#4240)
  src/parser/parser.h
  src/parser/type_checking.c
Labels: backport

#4292 [CBRD-24735] When attempting 'Multiple Key Ranges Optimization (MRO)', An internal error occurs because the '1=1' predicate (data filer) generated by constant folding is not removed (#4240)
  src/parser/parser.h
  src/parser/type_checking.c
Labels: backport

#4296 [CBRD-24772] A segfault occurs when using the connect by REGEXP_SUBSTR statement
  src/parser/xasl_generation.c
Labels: bug

#4307 [CBRD-24772] A segfault occurs when using the connect by REGEXP_SUBSTR statement (#4296)
  src/parser/xasl_generation.c
Labels: bug, backport

#4308 [CBRD-24772] A segfault occurs when using the connect by REGEXP_SUBSTR statement (#4296)
  src/parser/xasl_generation.c
Labels: bug, backport

#4309 [CBRD-24772] A segfault occurs when using the connect by REGEXP_SUBSTR statement (#4296)
  src/parser/xasl_generation.c
Labels: bug, backport

#4312 [CBRD-24770] Whenever one `QFILE_TUPLE_RECORD` of `(CONNECTBY_PROC_NODE *)->start_with_list_id` is completed, `(INDX_SCAN_ID *)->indx_cov.list_id` must be cleared (#4297)
  src/query/query_executor.c
Labels: backport

#4311 [CBRD-24770] Whenever one `QFILE_TUPLE_RECORD` of `(CONNECTBY_PROC_NODE *)->start_with_list_id` is completed, `(INDX_SCAN_ID *)->indx_cov.list_id` must be cleared (#4297)
  src/query/query_executor.c
Labels: backport

#4329 [CBRD-24781] Added csql option for catalog rebuild (#4325)
  src/compat/db_client_type.hpp
  src/executables/csql.c
  src/executables/csql.h
  src/executables/csql_launcher.c
  src/executables/utility.h
  src/object/authenticate.c
  src/object/authenticate.h
  src/query/execute_schema.c
  src/transaction/boot.h
  src/transaction/boot_sr.c
Labels: backport
