Repository CUBRID/cubrid, pull requests merged in 2023-11, with the labels that each got.

#4586 [CBRD-24933] Fix some cost formula based on actual execution time.
  src/base/perf_monitor.c
  src/base/system_parameter.c
  src/optimizer/query_graph.c
  src/optimizer/query_planner.c
  src/optimizer/query_planner.h
  src/query/query_aggregate.cpp
  src/query/query_executor.c
  src/query/scan_manager.c
  src/query/xasl.h
  src/storage/statistics.h
Labels: in progress

#4684 [CBRD-24988] Improves the process of calculating the size of midxkey.buf required when reading records from nodes in a multi-column index
  src/base/object_representation.h
  src/base/object_representation_constants.h
  src/object/object_primitive.c
  src/object/object_primitive.h
  src/query/execute_statement.c
  src/query/scan_manager.c
  src/storage/btree.c
  src/storage/btree_load.c
  src/storage/heap_file.c
Labels: enhancement

#4727 [CBRD-25035] extend query cache to CTE
  src/parser/parse_tree.h
  src/parser/xasl_generation.c
  src/query/execute_statement.c
  src/query/query_executor.c
  src/query/query_manager.c
  src/query/stream_to_xasl.c
  src/query/xasl.h
  src/query/xasl_to_stream.c
Labels: enhancement, task

#4765 [CBRD-25053] [Regression] Core dumped in tp_is_domain_cached at src/object/object_domain.c:2276
  src/object/object_domain.c
Labels: bug, regression

#4766 [CBRD-25054] Numeric type column inserted by using rownum does not show error even it's outranged.
  src/object/object_domain.c
  src/object/object_domain.h
  src/storage/heap_file.c
Labels: bug, legacy
