Repository CUBRID/cubrid, pull requests merged in 2023-03, with the labels that each got.

#4096 [CBRD-24654] When getting a NUMERIC type value, if the value after the decimal point is 0, it should be improved so that the trailing 0's are not passed.
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/query/numeric_opfunc.c
Labels: task

#4074 [CBRD-24638] The problem of the default value of column when altering the type of column.
  src/object/schema_template.c
Labels: bug, enhancement

#4179 [CBRD-24504] When an error occurs in a function that uses a buffer to convert an identifier name, the buffer must be initialized. (#3844)
  src/object/schema_manager.c
Labels: backport

#4184 [CBRD-24701] Modify packer class not to call abort in check_range() function
  src/base/packer.cpp
Labels: bug, enhancement

#4190 [CBRD-24701] Modify packer class not to call abort in check_range() function (#4184)
  src/base/packer.cpp
Labels: backport

#3925 [CBRD-24544] not allow to alter the column type to a type that does not support auto-increment.
  src/query/execute_schema.c
Labels: enhancement, task

#4192 [CBRD-24544] not allow to alter the column type to a type that does not support auto-increment. (#3925)
  src/object/schema_template.c
  src/optimizer/query_planner.c
  src/query/execute_schema.c
  src/transaction/boot_cl.c
Labels: backport

#4208 [CBRD-24704] demodb is not installed when installing CUBRID engine with msi file for windows.
  demo/make_cubrid_demo.bat
Labels: backport

#4217 [CBRD-22503] Fix big tuple case for aggregates (#1317)
  src/query/query_opfunc.c
Labels: bug, backport
