Repository CUBRID/cubrid, pull requests merged in 2023-09, with the labels that each got.

#4635 [CBRD-24974] The problem is that error occurs when loading unloaded schema file if both DBA and user have tables and views with same name (#4624)
  src/executables/unload_schema.c
Labels: backport

#4632 [CBRD-24905] The problem is that a core dump occurs when a value of an invalid index type (such as Collection Type) is bound to host variables (#4614)
  src/query/scan_manager.c
  src/storage/btree.c
Labels: backport

#4631 [CBRD-24905] The problem is that a core dump occurs when a value of an invalid index type (such as Collection Type) is bound to host variables (#4614)
  src/query/scan_manager.c
  src/storage/btree.c
Labels: backport

#4666 [CBRD-24984] error occurs depending on optimization level in dblink queries containing server-name
  src/query/execute_statement.c
Labels: bug, regression

#4668 [CBRD-24986] Error when creating a view containing dblink in loaddb
  src/parser/name_resolution.c
Labels: bug, regression

#4690 [CBRD-24994] Revert "[CBRD-22860] Select query on VIEW which contains inline view, and that inline view contains SP call have problem with LIMIT clause" (#2156)
  src/parser/name_resolution.c
Labels: revert

#4689 [CBRD-24009] Plan cache is not updated when view changes including inline view. (#2915)
  src/parser/view_transform.c
Labels: backport

#4694 [CBRD-24996] er_clear() is slipped even if synonym is found succesfully (#4693)
  src/object/schema_manager.c
Labels: backport

#4700 [CBRD-25004] function pushed incorrectly in dblink
  src/parser/view_transform.c
Labels: bug, regression
