Repository CUBRID/cubrid, pull requests merged in 2023-08, with the labels that each got.

#4543 [CBRD-24844] Garbage value when querying bit varying(n) column using DBLINK.
  src/query/dblink_scan.c
Labels: bug, backport

#4544 [CBRD-24828] Executor error when using udf() and bind variable in update query (#4394)
  src/parser/name_resolution.c
  src/parser/type_checking.c
Labels: bug, backport

#4505 [CBRD-24899] check push predicate and quoted name for dblink
  src/parser/type_checking.c
  src/parser/view_transform.c
Labels: task

#4513 [CBRD-24909] dblink related synonym processing
  src/parser/csql_grammar.y
  src/parser/parse_tree.h
  src/parser/parser_support.c
  src/parser/semantic_check.c
  src/query/execute_statement.c
Labels: task

#4545 [CBRD-24897] Query rewriter can lose parent paths of a name in qo_collect_name_spec() (#4501)
  src/optimizer/query_rewrite.c
Labels: backport

#4547 [CBRD-24897] Query rewriter can lose parent paths of a name in qo_collect_name_spec() (#4501)
  src/optimizer/query_rewrite.c
Labels: backport

#4507 [CBRD-24867] rev: regression bug-fix related to DBLINK - CCI_U_TYPE, no serve name
  src/parser/name_resolution.c
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/parser_support.c
  src/parser/view_transform.c
  src/query/execute_statement.c
Labels: bug, regression

#4546 [CBRD-24897] Query rewriter can lose parent paths of a name in qo_collect_name_spec() (#4501)
  src/optimizer/query_rewrite.c
Labels: backport

#4557 [CBRD-24924] [Regression] Core dumped in pt_bind_names
  src/parser/name_resolution.c
Labels: bug, regression

#4561 [CBRD-24899] rev: check push predicate
  src/parser/parse_tree_cl.c
  src/parser/parser.h
  src/parser/parser_support.c
  src/parser/view_transform.c
Labels: bug, regression

#4541 [CBRD-24920] to not output decimal point 0 of double type in csql
  src/executables/csql_result_format.c
Labels: task

#4571 [CBRD-24899] rev2: check push predicate
  src/parser/type_checking.c
  src/parser/view_transform.c
Labels: bug, regression

#4587 [CBRD-24934] [Regression] extending dblink to DML: double quoted identifier
  src/base/intl_support.c
  src/base/intl_support.h
  src/parser/name_resolution.c
Labels: bug, regression

#4588 [CBRD-24935] extending dblink to DML: function is pushed
  src/parser/parse_tree_cl.c
  src/parser/type_checking.c
  src/parser/view_transform.c
Labels: bug, regression

#4591 [CBRD-24938] add comment to dblink query for statement type checking in gateway
  src/parser/name_resolution.c
  src/parser/parser_support.c
  src/parser/xasl_generation.c
Labels: enhancement, task

#4594 [CBRD-24934] rev: [Regression] extending dblink to DML: double quoted…
  src/base/intl_support.c
Labels: task

#4595 [CBRD-24939] dblink query could return zero column count in column info.
  src/parser/name_resolution.c
Labels: bug, regression

#4600 [CBRD-24920] [regression] to not output decimal point 0 of double type in csql
  src/executables/csql_result_format.c
Labels: bug, regression

#4607 [CBRD-24944] Remove cast function from dblink predicate push
  src/parser/view_transform.c
Labels: bug, regression

#4606 [CBRD-24942] System parameter oracle_compat_number_behavior not reflected in CAS
  src/parser/type_checking.c
  src/query/numeric_opfunc.c
  src/query/query_opfunc.c
Labels: bug, regression

#4608 [CBRD-24945] Correct value node print in dblink query rewritten
  src/parser/name_resolution.c
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/parser_support.c
Labels: bug, regression

#4610 [CBRD-24952] Failed to read precision and character set of remote bit type and bit varying type from dblink
  src/parser/name_resolution.c
Labels: bug, regression

#4612 [CBRD-24966] Core dump while processing DML with subquery in dblink
  src/parser/parser_support.c
Labels: bug, regression

#4615 [CBRD-24920] [regression-rev] to not output decimal point 0 of double type in csql
  src/executables/csql_result_format.c
Labels: bug, regression

#4621 [CBRD-24968] An error occurs when a table alias name is used and a column name is used within a function.
  src/parser/name_resolution.c
Labels: bug, regression

#4623 [CBRD-24975] Remove date and time related modifier from dblink query
  src/parser/type_checking.c
Labels: bug, regression
