Repository CUBRID/cubrid, pull requests merged in 2024-07, with the labels that each got.

#5283 [CBRD-25395] whether the result-cache is referenced must be indicated…
  src/query/query_dump.c
  src/query/query_executor.c
  src/query/xasl.h
Labels: enhancement, task

#5234 [CBRD-24658] Name binding error for SP in CTE and Aggregate statements
  src/parser/method_transform.c
Labels: bug, legacy

#5305 [CBRD-25036] Improved key reading in B-Tree index
  src/query/partition.c
  src/query/query_evaluator.c
  src/query/query_evaluator.h
  src/query/scan_manager.c
  src/storage/btree.c
  src/storage/btree.h
Labels: enhancement, refactoring

#5280 [CBRD-25337] Fixed an issue where dbname could not be read when an error occurred in loaddb.
  src/base/ddl_log.c
  src/loaddb/load_db.c
Labels: bug

#5344 [CBRD-25337] Backport to 11.3 - Fixed an issue where dbname could not be read when an error occurred in loaddb.
  src/base/ddl_log.c
  src/loaddb/load_db.c
Labels: bug

#5313 [CBRD-25454] performance enhancement at TRACE ON
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/perf_monitor.c
  src/base/tsc_timer.c
  src/base/tsc_timer.h
  util/CMakeLists.txt
Labels: enhancement, task, legacy

#5357 [CBRD-25481] Corrects an error in unloaddb when the JSON type column contains data larger than 1MB
  src/loaddb/load_object.c
  src/loaddb/load_object.h
Labels: bug

#5356 [CBRD-25480] When an error occurs in loaddb, it does not stop and continues execution.
  src/loaddb/load_db.c
Labels: bug

#5367 [CBRD-25490] fix stack overflow on windows
  src/storage/btree_load.c
Labels: refactoring
