Repository CUBRID/cubrid, pull requests merged in 2024-03, with the labels that each got.

#4972 [CBRD-25171] Use PEEK_KEY_VALUE instead of COPY_KEY_VALUE in btree_range_scan_read_record()
  src/storage/btree.c
  src/storage/btree.h
Labels: enhancement

#5001 [CBRD-25239] user variable time format
  src/query/string_opfunc.c
Labels: bug

#5002 [CBRD-25236] Output error related to TZM in timezone information
  src/query/string_opfunc.c
Labels: bug

#5006 [CBRD-25233] When executing multiple statements at once in SetAutocommit(false), there is a commit or rollback statement between the statements
  src/base/ddl_log.c
Labels: enhancement

#4996 [CBRD-25234] refactor the code that uses strlen() to check the condition of the loop
  src/base/locale_support.c
  src/base/uca_support.c
  src/compat/cnv.c
  src/executables/util_service.c
  src/object/schema_manager.c
  src/parser/compile.c
  src/query/query_executor.c
  src/query/query_opfunc.c
  src/query/string_opfunc.c
Labels: enhancement, refactoring

#5012 [CBRD-25235] Improved performance of time_format() and date_format()
  src/parser/type_checking.c
  src/query/string_opfunc.c
Labels: enhancement, refactoring

#5034 [CBRD-25242] Improved speed of parse_digits()
  src/query/string_opfunc.c
Labels: enhancement, refactoring

#5058 [CBRD-25129] Change CSQL environment variable name (#4846)
  src/executables/csql.c
Labels: backport

#5021 [CBRD-25115] fixed inaccuracy in length limit of where clause when creating filter index
  src/executables/unload_schema.c
  src/object/schema_system_catalog_install.cpp
  src/query/execute_schema.c
Labels: enhancement, refactoring, change disk image

#5065 [CBRD-25128] In STRING_CAT '||' operation, incorrect handling of null when setting oracle_style_empty_string (#4842)
  src/executables/csql_result.c
  src/parser/type_checking.c
Labels: backport

#5066 [CBRD-25128] In STRING_CAT '||' operation, incorrect handling of null when setting oracle_style_empty_string (#4842)
  src/executables/csql_result.c
  src/parser/type_checking.c
Labels: backport

#5067 [CBRD-25139] When using oracle style empty string, the result of replace is null. (#4848)
  src/parser/type_checking.c
  src/query/fetch.c
Labels: backport

#5068 [CBRD-25139] When using oracle style empty string, the result of replace is null. (#4848)
  src/parser/type_checking.c
  src/query/fetch.c
Labels: backport
