Repository CUBRID/cubrid, pull requests merged in 2024-08, with the labels that each got.

#5409 [CBRD-25525] Modify cub_vsnprintf() to support vsnprintf() in Windows build
  src/base/porting.c
Labels: bug, legacy

#5411 [CBRD-25323] Remove unnecessary code (#5404)
  src/optimizer/query_rewrite.c
Labels: backport

#5383 [CBRD-25503] Added parameter to set ACL per broker
  src/broker/broker_acl.c
  src/broker/broker_admin_pub.c
  src/broker/broker_config.c
  src/broker/broker_config.h
  src/broker/broker_shm.c
  src/broker/broker_shm.h
  src/broker/cas_common.h
Labels: enhancement

#5421 [CBRD-25525] Modify cub_vsnprintf() to support vsnprintf() in Windows build (#5409) : to release/11.3
  src/base/porting.c
Labels: bug, legacy

#5400 [CBRD-25505] insert ... select .. on duplicate key update query result error with view
  src/parser/parse_tree.h
  src/parser/view_transform.c
Labels: bug, legacy

#5286 [CBRD-25230] rev: Extending result-cache to uncorrelated subqueries
  msg/en_US.utf8/cubrid.msg
  msg/en_US/cubrid.msg
  msg/ko_KR.euckr/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  src/base/error_code.h
  src/compat/db_vdb.c
  src/parser/parse_tree.h
  src/parser/xasl_generation.c
  src/query/execute_statement.c
  src/query/query_executor.c
  src/query/xasl.h
Labels: task

#5352 [CBRD-25473] 서브 쿼리의 호스트 변수 처리
  src/compat/db_query.c
  src/compat/db_vdb.c
  src/parser/parse_tree.h
  src/query/execute_statement.c
Labels: enhancement, task

#5402 [CBRD-25517] Limit the size of the data buffer that can be processed at one time in loaddb to 2GB or less
  src/loaddb/load_common.cpp
Labels: bug, legacy

#5428 [CBRD-25473] rev: subquery cache is incorrect in prepare statement
  src/query/execute_statement.c
Labels: bug, regression

#5429 [CBRD-25534] [Regression] prepare 쿼리에서 서브쿼리 캐시 안됨
  src/query/query_manager.c
Labels: bug, regression

#5420 [CBRD-25525] Modify cub_vsnprintf() to support vsnprintf() in Windows build (#5409) : to release/11.2
  src/base/porting.c
Labels: bug, legacy

#5434 [CBRD-25535] [regression] WITH를 참조하는 UPDATE / DELETE 쿼리에서 서브쿼리 캐시 안됨
  src/parser/xasl_generation.c
Labels: bug, regression

#5074 [CBRD-25282] Improve speed of unloaddb
  cs/CMakeLists.txt
  msg/en_US.utf8/utils.msg
  msg/ko_KR.utf8/utils.msg
  sa/CMakeLists.txt
  src/base/memory_alloc.c
  src/base/xserver_interface.h
  src/communication/network.h
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/executables/compactdb.c
  src/executables/unload_object.c
  src/executables/unload_object_file.c
  src/executables/unload_object_file.h
  src/executables/unload_schema.c
  src/executables/unloaddb.c
  src/executables/unloaddb.h
  src/executables/util_admin.c
  src/executables/utility.h
  src/loaddb/load_object.c
  src/loaddb/load_object.h
  src/object/object_primitive.c
  src/object/quick_fit.c
  src/object/quick_fit.h
  src/storage/heap_file.c
  src/thread/thread_entry.cpp
  src/thread/thread_entry.hpp
  src/thread/thread_entry_task.cpp
  src/transaction/locator.c
  src/transaction/locator.h
  src/transaction/locator_cl.c
  src/transaction/locator_sr.c
Labels: enhancement, task

#5437 [CBRD-25536] add fence key information to SHOW INDEX CAPACITY and diagdb
  src/parser/show_meta.c
  src/storage/btree.c
  src/storage/btree.h
Labels: enhancement
