Repository CUBRID/cubrid, pull requests merged in 2024-09, with the labels that each got.

#5436 [CBRD-25159] Refactoring reading of B-tree keys to update statistical information or obtain capacity
  src/storage/btree.c
Labels: refactoring

#5459 [CBRD-25559] [regression] CREATE ... AS SELECT 쿼리에 서브쿼리 캐시 적용 시 core dump
  src/parser/semantic_check.c
Labels: bug, regression

#5474 [CBRD-25578] [regression] exists 서브 쿼리에 캐시 힌트 적용 시 core dump
  src/query/xasl.h
Labels: bug

#5476 [CBRD-25567] Problem with Range Predicates Using Pipe Operators Not Being Reducible to Common Range Terms (#5467)
  src/parser/parse_tree_cl.c
Labels: backport

#5475 [CBRD-25579] [regression] SYSDATE, SERIAL 함수 등을 사용할 때, 서브쿼리 캐시가 설정됨
  src/query/execute_statement.c
Labels: bug, regression

#5488 [CBRD-25579] rev: [regression] system class, SYSDATE, SERIAL 함수 등을 사용할 때, 서브쿼리 캐시가 설정됨
  src/query/execute_statement.c
Labels: bug, regression

#5493 [CBRD-25589] PREPARE 구문을 사용할 때 쿼리 캐시
  src/compat/db_query.c
  src/compat/db_query.h
  src/compat/db_vdb.c
  src/parser/parse_tree.h
  src/query/execute_statement.c
Labels: enhancement, task

#5501 [CBRD-25593] stack smashing detected due to buffer overflow in networ_interface_cl
  src/communication/network_interface_cl.c
Labels: bug

#5486 [CBRD-25584] refactoring macros in parse_tree.h
  src/parser/func_type.cpp
  src/parser/parse_dbi.c
  src/parser/parse_tree.h
Labels: refactoring

#5515 [CBRD-25605] DBLINK 서브쿼리를 쿼리 캐시에서 제외
  src/query/execute_statement.c
Labels: task
