Repository CUBRID/cubrid, pull requests merged in 2024-12, with the labels that each got.

#5665 [CBRD-25714] 필터 인덱스 생성 중 core dump 발생
  src/object/class_object.c
Labels: bug, legacy

#5664 [CBRD-25718] REPEAT 함수의 리턴 타입은 VARCHAR타입이어야 함
  src/query/string_opfunc.c
Labels: bug, legacy

#5632 [CBRD-25302] Strengthens checks on date_lang_string_literal in functions such as TO_DATE()
  msg/en_US.utf8/cubrid.msg
  msg/ko_KR.utf8/cubrid.msg
  src/base/error_code.h
  src/base/language_support.c
  src/base/language_support.h
  src/parser/csql_grammar.y
  src/parser/parse_tree_cl.c
  src/parser/parser_message.h
  src/parser/type_checking.c
  src/query/fetch.c
  src/query/string_opfunc.c
Labels: bug

#5658 [CBRD-25713] CHAR 타입 최대 길이 2048로 제한
  src/compat/dbtype_def.h
Labels: task

#5702 [CBRD-25713] revert to MAX CHAR Length
  src/compat/dbtype_def.h
Labels: revert

#5650 [CBRD-25186] [bugfix] Run-time exception of expression BIT_LENGTH('CUBRID')
  src/parser/parse_tree_cl.c
  src/parser/type_checking.c
  src/query/fetch.c
  src/query/string_opfunc.c
Labels: bug

#5703 [CBRD-25302] fix core dump to TO_CHAR() on PLCSQL
  src/parser/type_checking.c
Labels: bug

#5705 [CBRD-25737] When unloading serial and trigger as dba user, schema name is missing
  src/executables/unload_schema.c
  src/object/trigger_description.cpp
Labels: bug
