Repository CUBRID/cubrid, pull requests merged in 2024-06, with the labels that each got.

#5223 [CBRD-25337] After switching users from csql to session command, DDL Log must be recorded in the changed DB log file.
  src/base/ddl_log.c
  src/broker/cas.c
  src/executables/csql.c
  src/loaddb/load_db.c
Labels: bug

#5254 [CBRD-25419] If you use the -i and --input-class-only options together in unloaddb, unrelated alter serial statements will be output.
  src/executables/unload_schema.c
Labels: bug

#5259 [CBRD-25419] If you use the -i and --input-class-only options together in unloaddb, unrelated alter serial statements will be output.
  src/executables/unload_schema.c
Labels: bug, backport

#5260 [CBRD-25426] If the current_val of serial is the same as max_val, an error occurs during unloaddb/loaddb.
  src/executables/unload_schema.c
Labels: bug

#5262 [CBRD-25426] Backport to 11.3 - If the current_val of serial is the same as max_val, an error occurs during unloaddb/loaddb.
  src/executables/unload_schema.c
Labels: bug, backport

#5265 [CBRD-25426] Backport to 11.2 - If the current_val of serial is the s…
  src/compat/db_vdb.c
  src/executables/unload_schema.c
Labels: bug, backport

#5268 [CBRD-25426] Backport to 10.2 - If the current_val of serial is the same as max_val, an error occurs during unloaddb/loaddb.
  src/compat/db_vdb.c
  src/executables/unload_schema.c
Labels: bug, backport

#5267 [CBRD-25426] Remove empty space in schema file
  src/executables/unload_schema.c
Labels: bug

#5269 [CBRD-25425] refacto the er_log()
  src/base/error_manager.c
Labels: bug, refactoring

#5273 [CBRD-25358] error handling when using for update clause for system tables such as db_root, dual, etc.
  src/parser/name_resolution.c
Labels: bug, regression

#4973 [CBRD-25230] Extending result-cache to uncorrelated subqueries
  src/compat/db_query.c
  src/compat/db_query.h
  src/compat/db_vdb.c
  src/parser/parse_tree.h
  src/parser/parse_tree_cl.c
  src/parser/scanner_support.c
  src/parser/view_transform.c
  src/parser/xasl_generation.c
  src/query/execute_statement.c
  src/query/execute_statement.h
  src/query/list_file.c
  src/query/query_evaluator.c
  src/query/query_executor.c
  src/query/query_executor.h
  src/query/query_list.h
  src/query/stream_to_xasl.c
  src/query/xasl.h
  src/query/xasl_to_stream.c
Labels: enhancement, task

#5275 [CBRD-25432] Add Support for Git Worktrees in CMake Configuration
  CMakeLists.txt
Labels: enhancement
