Repository CUBRID/cubrid, pull requests merged in 2024-02, with the labels that each got.

#4908 [CBRD-25207] count(*) value is incorrect after no-logging option loaddb
  src/base/xserver_interface.h
  src/transaction/log_manager.c
  src/transaction/log_tran_table.c
Labels: bug, legacy

#4910 [CBRD-25206] Change the statistical information of the B-tree index root header to 64 bits.
  src/storage/btree.c
  src/storage/btree_load.c
  src/storage/btree_load.h
Labels: refactoring, task

#4919 [CBRD-25209] If a transaction is terminated without commit/rollback, write the ABORT log to the ddl_audit log
  src/base/ddl_log.c
  src/base/ddl_log.h
  src/broker/cas.c
  src/broker/cas_execute.c
  src/broker/cas_execute.h
  src/broker/cas_function.c
  src/broker/cas_xa.c
Labels: enhancement, legacy

#4912 [CBRD-24438] fixed error when executing more than 2 statements with CallableStatement
  src/base/ddl_log.c
  src/base/ddl_log.h
  src/broker/cas_execute.c
  src/executables/csql.c
Labels: bug

#4936 [CBRD-25044] Supports Windows build in Debug mode
  src/storage/page_buffer.c
  win/cubridsa/cubridsa.def
Labels: build

#4926 [CBRD-25176] Failure when creating fk of deduplicate attribute
  src/storage/btree.c
  src/storage/btree.h
  src/storage/btree_load.c
Labels: bug

#4932 [CBRD-25043] refactor functions related to isspace, tolower, and toupper
  src/base/chartype.c
  src/base/chartype.h
  src/base/hide_password.cpp
  src/base/intl_support.c
  src/base/porting.c
  src/base/porting.h
  src/base/system_parameter.h
  src/broker/broker_log_sql_list.c
  src/broker/broker_log_util.c
  src/broker/broker_log_util.h
  src/broker/broker_util.c
  src/broker/cas_common.h
  src/broker/cas_util.c
  src/broker/cas_util.h
  src/broker/shard_proxy_log.c
  src/cm_common/cm_utils.c
  src/cm_common/cm_utils.h
  src/connection/connection_support.c
  src/executables/util_common.c
  src/parser/csql_grammar.y
  src/parser/csql_lexer.l
  src/parser/scanner_support.c
  src/query/string_opfunc.c
  win/cubridcs/cubridcs.def
Labels: enhancement, refactoring

#4955 [CBRD-25216] Check if there is enough buffer to store the user-specified name (#4946)
  src/object/authenticate.c
  src/object/schema_manager.c
  src/object/schema_manager.h
  src/parser/parser_support.c
Labels: backport

#4956 [CBRD-25216] Check if there is enough buffer to store the user-specified name (#4946)
  src/object/authenticate.c
  src/object/schema_manager.c
  src/object/schema_manager.h
  src/parser/parser_support.c
Labels: backport

#4886 [CBRD-25161] reduce column id compare in range_scan
  src/query/partition.c
  src/query/query_evaluator.c
  src/query/query_evaluator.h
  src/query/scan_manager.c
  src/storage/btree.c
  src/storage/btree.h
Labels: enhancement

#4974 [CBRD-25054] Numeric type column inserted by using rownum does not show error even it's outranged. (#4766)
  src/object/object_domain.c
  src/object/object_domain.h
  src/storage/heap_file.c
Labels: bug, regression

#4975 [CBRD-25179] A core dump occurs when the CTE query is a false query (null query) (#4890)
  src/parser/xasl_generation.c
Labels: bug, legacy

#4976 [CBRD-25207] count(*) value is incorrect after no-logging option loaddb (#4908)
  src/base/xserver_interface.h
  src/transaction/log_manager.c
  src/transaction/log_tran_table.c
Labels: bug, legacy

#4977 [CBRD-25195] A core dump occurs when multiple tables and serial functions are used simultaneously in one query. (#4897)
  src/parser/xasl_generation.c
Labels: bug, legacy

#4950 [CBRD-25228] Query with CTE sub-query, query-cache does not work.
  src/query/execute_statement.c
Labels: bug, regression
