Repository CUBRID/cubrid, pull requests merged in 2025-04, with the labels that each got.

#6084 [CBRD-26002] In system parameter.c, PRM_ID_JAVA_STORED_PROCEDURE_JVM_OPTIONS is incorrectly written as PRM_ID_STORED_PROCEDURE_JVM_OPTIONS
  src/base/system_parameter.c
Labels: bug

#6082 [CBRD-26001] [Regression][shell] Core dumped in dblink_end_tran
  src/query/dblink_scan.c
  src/query/query_manager.c
Labels: bug, regression

#6073 [CBRD-25480] Backport from develop to 11.0 - When an error occurs in loaddb, it does not stop and continues execution.
  src/loaddb/load_db.c
Labels: backport

#6088 [CBRD-25360] Backport to 10.2 - Modify the method of obtaining schema information for tables with auto_increment using unloaddb
  src/executables/unload_schema.c
Labels: backport

#6087 [CBRD-25360] Backport to 11.0 - Modify the method of obtaining schema information for tables with auto_increment using unloaddb
  src/compat/db_vdb.c
  src/executables/unload_schema.c
Labels: backport

#6094 [CBRD-25358] rev (error for system class / view in inline view): error handling when using for update clause for system tables such as db_root, dual, etc.
  src/parser/name_resolution.c
  src/parser/view_transform.c
Labels: regression

#6100 [CBRD-25358] rev (error for system class / view in inline view): error handling when using for update clause for system tables such as db_root, dual, etc. (#6094)
  src/parser/name_resolution.c
  src/parser/view_transform.c
Labels: backport

#6107 [CBRD-25358] rev (error check at resolve names): error handling when using for update clause for inline view
  src/parser/name_resolution.c
  src/parser/view_transform.c
Labels: bug, regression

#6108 [CBRD-25358] rev (error check at resolve names): error handling when using for update clause for inline view (#6107)
  src/parser/name_resolution.c
  src/parser/view_transform.c
Labels: bug, regression

#6118 [CBRD-26025] Error occurs when sending NULL value to DBLink via JDBC
  src/broker/cas_cgw.c
Labels: bug

#5930 [CBRD-25358] backport: error handling when using for update clause for inline view (#5882)
  src/parser/name_resolution.c
Labels: backport

#5985 [CBRD-25617] The phenomenon that position numbers within the analytic function become incorrect occurs when the analytic function is included in the view (#5590)
  src/parser/semantic_check.c
  src/parser/semantic_check.h
  src/parser/view_transform.c
Labels: backport

#5992 [CBRD-25317] The problem is that the Oracle-style LEFT OUTER JOIN is not rewritten as an INNER JOIN if there is a method call and host variables are used in the WHERE clause (#5292)
  src/parser/name_resolution.c
Labels: backport

#6138 [CBRD-26031] Backport from develop to 11.3 - When entering Korean characters using bind variables in DBLINK, Korean characters are broken
  src/broker/cas_cgw.c
  src/broker/cas_cgw.h
  src/broker/cas_execute.c
Labels: bug, backport

#6137 [CBRD-26031] When entering Korean characters using bind variables in DBLINK, Korean characters are broken
  src/broker/cas_cgw.c
  src/broker/cas_cgw.h
  src/broker/cas_execute.c
Labels: bug

#5964 [CBRD-25454] Backport: performance enhancement at TRACE ON (#5313)
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/perf_monitor.c
  src/base/tsc_timer.c
  src/base/tsc_timer.h
  util/CMakeLists.txt
Labels: backport
