Repository CUBRID/cubrid, pull requests merged in 2025-09, with the labels that each got.

#6406 [CBRD-26282] Fixed an issue where the string output from unloaddb would break when the length was longer than the remaining space in the buffer
  src/executables/unload_object_file.c
Labels: bug

#6425 [CBRD-26282] Fixed an issue where the string output from unloaddb would break when the length was longer than the remaining space in the buffer (#6406)
  src/executables/unload_object_file.c
Labels: backport

#6424 [CBRD-26282] Fixed an issue where the string output from unloaddb would break when the length was longer than the remaining space in the buffer (#6406)
  src/executables/unload_object_file.c
Labels: backport

#6423 [CBRD-26282] Fixed an issue where the string output from unloaddb would break when the length was longer than the remaining space in the buffer (#6406)
  src/executables/unload_object_file.c
Labels: backport

#6422 [CBRD-26282] Fixed an issue where the string output from unloaddb would break when the length was longer than the remaining space in the buffer (#6406)
  src/executables/unload_object_file.c
Labels: backport

#6421 [CBRD-26282] Fixed an issue where the string output from unloaddb would break when the length was longer than the remaining space in the buffer (#6406)
  src/executables/unload_object_file.c
Labels: backport

#6447 [CBRD-26240] rev: Core dump occurs when using like_match_upper_bound(empty-string) in a query
  src/object/object_primitive.c
Labels: bug, regression, legacy

#6472 [CBRD-26240] rev2: Core dump occurs when using like_match_upper_bound(empty-string) in a query
  src/object/object_primitive.c
Labels: bug, regression

#6496 [CBRD-25271] Core occurs when applying nvl function index to char type column (#5047)
  src/query/string_opfunc.c
  src/storage/btree.c
Labels: bug, backport

#6501 [CBRD-26319] backport: fix core dump left join or use function index (#6497)
  src/optimizer/query_bitset.c
  src/optimizer/query_graph.c
Labels: bug, backport

#6487 [CBRD-26315] Refactoring code related to locale_support
  src/base/locale_support.c
  src/base/locale_support.h
  src/base/tz_compile.c
  src/base/uca_support.c
  src/base/uca_support.h
  src/base/unicode_support.c
  src/base/unicode_support.h
  src/base/xml_parser.c
  src/base/xml_parser.h
Labels: refactoring
