Repository CUBRID/cubrid, pull requests merged in 2025-03, with the labels that each got.

#5932 [CBRD-25854] result-cache enable 환경에서 DML 사용 시 memory leak 발생 (#5838)
  src/query/query_manager.c
  src/transaction/locator_sr.c
Labels: backport

#5931 [CBRD-25854] result-cache enable 환경에서 DML 사용 시 memory leak 발생 (#5838)
  src/query/query_manager.c
  src/transaction/locator_sr.c
Labels: backport

#5974 [CBRD-25480] Backport from develop to 11.2 - When an error occurs in loaddb, it does not stop and continues execution.
  src/loaddb/load_db.c
Labels: backport

#5965 [CBRD-25944] Differences in results related to time zone when using user-defined variables in the time_format function (#5947)
  src/query/string_opfunc.c
Labels: backport

#5988 [CBRD-25951] PL/CSQL Static SQL Loop 내 CTE에서 SP 사용 시 Core Dump 발생
  src/parser/xasl_generation.c
Labels: bug, legacy

#5966 [CBRD-25944] Differences in results related to time zone when using user-defined variables in the time_format function (#5947)
  src/query/string_opfunc.c
Labels: backport

#5996 [CBRD-25713] for merge : CHAR 타입 최대 길이 2048로 제한
  pl_engine/pl_server/src/main/java/com/cubrid/plcsql/compiler/type/TypeChar.java
  src/compat/dbtype_def.h
Labels: task

#5933 [CBRD-25505] backport: 뷰가 포함된 insert ... select .. on duplicate key update 쿼리 결과 오류 (#5400)
  src/parser/parse_tree.h
  src/parser/view_transform.c
Labels: backport

#5928 [CBRD-25457] backport: Executing the “AUTO_INCREMENT” and “DEFAULT” attributes separately using the “ALTER TABLE MODIFY” syntax on the same column resulted in an error of two attributes co-existing in that column (#5364)
  src/query/execute_schema.c
Labels: backport

#5929 [CBRD-25454] backport: performance enhancement at TRACE ON (#5313)
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/perf_monitor.c
  src/base/tsc_timer.c
  src/base/tsc_timer.h
  util/CMakeLists.txt
Labels: backport

#5927 [CBRD-25358] backport: error handling when using for update clause for inline view (#5882)
  src/parser/name_resolution.c
Labels: backport

#5938 [CBRD-24795] When using a function under <= and >= conditions, the plan generator does not perform a range scan (#4365, #4830)
  src/optimizer/query_rewrite.c
  src/parser/semantic_check.c
Labels: backport

#5954 [CBRD-25912] the problem of memory leak occurs when the SP function generates an error
  src/query/query_executor.c
  src/query/stream_to_xasl.c
  src/query/xasl.h
  src/query/xasl_cache.c
Labels: bug, backport

#5890 [CBRD-25902] Changed to use stx_alloc_struct() to support reuse of SP-related xasl
  src/method/query_method.cpp
  src/parser/xasl_generation.c
  src/query/query_executor.c
  src/query/regu_var.cpp
  src/query/stream_to_xasl.c
  src/query/xasl_to_stream.c
  src/sp/pl_connection.cpp
  src/sp/pl_signature.cpp
  src/sp/pl_signature.hpp
  src/xasl/xasl_stream.cpp
Labels: refactoring

#5991 [CBRD-25317] The problem is that the Oracle-style LEFT OUTER JOIN is not rewritten as an INNER JOIN if there is a method call and host variables are used in the WHERE clause (#5292)
  src/parser/name_resolution.c
Labels: backport

#5986 [CBRD-25484] When using an inner join and an Oracle style outer join together, errors may occur depending on the order of the join predicates (#5365)
  src/parser/name_resolution.c
Labels: backport

#5984 [CBRD-25617] The phenomenon that position numbers within the analytic function become incorrect occurs when the analytic function is included in the view (#5590)
  src/parser/semantic_check.c
  src/parser/semantic_check.h
  src/parser/view_transform.c
Labels: backport

#5973 [CBRD-25480] Backport from develop to 11.3 - When an error occurs in loaddb, it does not stop and continues execution.
  src/loaddb/load_db.c
Labels: backport

#6002 [CBRD-25957] Memory leak problem in packer when using PL function
  src/base/packer.hpp
Labels: bug

#5977 [CBRD-25905] backport the speed-up unloaddb to lower version to 11.3.3
  cs/CMakeLists.txt
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  sa/CMakeLists.txt
  src/base/memory_alloc.c
  src/base/xserver_interface.h
  src/communication/network.h
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/executables/compactdb.c
  src/executables/unload_object.c
  src/executables/unload_object_file.c
  src/executables/unload_object_file.h
  src/executables/unload_schema.c
  src/executables/unloaddb.c
  src/executables/unloaddb.h
  src/executables/util_admin.c
  src/executables/utility.h
  src/jsp/jsp_sr.c
  src/loaddb/load_object.c
  src/loaddb/load_object.h
  src/object/object_primitive.c
  src/object/quick_fit.c
  src/object/quick_fit.h
  src/storage/heap_file.c
  src/thread/thread_entry.cpp
  src/thread/thread_entry.hpp
  src/thread/thread_entry_task.cpp
  src/transaction/locator.c
  src/transaction/locator.h
  src/transaction/locator_cl.c
  src/transaction/locator_sr.c
Labels: backport

#6008 [CBRD-25934] Skip errors due to ownership change in unloaddb.
  src/object/authenticate.c
Labels: bug

#6036 [CBRD-25964] clear CHECK_OVER_CODE_VALUE macro
  src/base/chartype.h
Labels: bug

#6004 [CBRD-25905] backport the speed-up unloaddb to lower version to 10.2.16
  cs/CMakeLists.txt
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  sa/CMakeLists.txt
  src/base/memory_alloc.c
  src/base/xserver_interface.h
  src/communication/network.h
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/executables/compactdb.c
  src/executables/extract_schema.hpp
  src/executables/unload_object.c
  src/executables/unload_object_file.c
  src/executables/unload_object_file.h
  src/executables/unload_schema.c
  src/executables/unloaddb.c
  src/executables/unloaddb.h
  src/executables/util_admin.c
  src/executables/utility.h
  src/loaddb/load_object.c
  src/loaddb/load_object.h
  src/object/object_primitive.c
  src/object/quick_fit.c
  src/object/quick_fit.h
  src/transaction/locator.c
  src/transaction/locator.h
  src/transaction/locator_cl.c
  src/transaction/locator_sr.c
Labels: backport

#6015 [CBRD-25905] backport the speed-up unloaddb to lower version to 11.2.10
  cs/CMakeLists.txt
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  sa/CMakeLists.txt
  src/base/memory_alloc.c
  src/base/xserver_interface.h
  src/communication/network.h
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/executables/compactdb.c
  src/executables/extract_schema.hpp
  src/executables/unload_object.c
  src/executables/unload_object_file.c
  src/executables/unload_object_file.h
  src/executables/unload_schema.c
  src/executables/unloaddb.c
  src/executables/unloaddb.h
  src/executables/util_admin.c
  src/executables/utility.h
  src/jsp/jsp_sr.c
  src/loaddb/load_object.c
  src/loaddb/load_object.h
  src/object/object_primitive.c
  src/object/quick_fit.c
  src/object/quick_fit.h
  src/storage/heap_file.c
  src/thread/thread_entry_task.cpp
  src/transaction/locator.c
  src/transaction/locator.h
  src/transaction/locator_cl.c
  src/transaction/locator_sr.c
Labels: backport

#6017 [CBRD-25905] backport the speed-up unloaddb to lower version to 11.0.14
  cs/CMakeLists.txt
  msg/de_DE.utf8/utils.msg
  msg/en_US.utf8/utils.msg
  msg/en_US/utils.msg
  msg/es_ES.utf8/utils.msg
  msg/fr_FR.utf8/utils.msg
  msg/it_IT.utf8/utils.msg
  msg/ja_JP.utf8/utils.msg
  msg/km_KH.utf8/utils.msg
  msg/ko_KR.euckr/utils.msg
  msg/ko_KR.utf8/utils.msg
  msg/ro_RO.utf8/utils.msg
  msg/tr_TR.utf8/utils.msg
  msg/vi_VN.utf8/utils.msg
  msg/zh_CN.utf8/utils.msg
  sa/CMakeLists.txt
  src/base/memory_alloc.c
  src/base/xserver_interface.h
  src/communication/network.h
  src/communication/network_cl.c
  src/communication/network_interface_cl.c
  src/communication/network_interface_cl.h
  src/communication/network_interface_sr.c
  src/executables/compactdb.c
  src/executables/extract_schema.hpp
  src/executables/unload_object.c
  src/executables/unload_object_file.c
  src/executables/unload_object_file.h
  src/executables/unload_schema.c
  src/executables/unloaddb.c
  src/executables/unloaddb.h
  src/executables/util_admin.c
  src/executables/utility.h
  src/jsp/jsp_sr.c
  src/loaddb/load_object.c
  src/loaddb/load_object.h
  src/object/object_primitive.c
  src/object/quick_fit.c
  src/object/quick_fit.h
  src/storage/heap_file.c
  src/thread/thread_entry_task.cpp
  src/transaction/locator.c
  src/transaction/locator.h
  src/transaction/locator_cl.c
  src/transaction/locator_sr.c
Labels: backport

#6037 [CBRD-25737] Add user schema to SELECT NEXT_VALUE statement
  src/executables/unload_schema.c
Labels: bug

#6024 [CBRD-25934] Backport from develop to 11.0 - Skip errors due to ownership change in unloaddb.
  src/object/authenticate.c
Labels: backport

#6023 [CBRD-25934] Backport from develop to 11.2 - Skip errors due to ownership change in unloaddb.
  src/object/authenticate.c
Labels: backport

#5995 [CBRD-25360] Backport to 11.2 -Modify the method of obtaining schema information for tables with auto_increment using unloaddb
  src/executables/unload_schema.c
Labels: backport

#6041 [CBRD-25737] Backport from develop to 11.3 - Add user schema to SELECT NEXT_VALUE statement
  src/executables/unload_schema.c
Labels: backport

#5746 [CBRD-25737] Backport from develop to 11.2 - When unloading serial and trigger as dba user, schema name is missing
  src/executables/unload_schema.c
  src/object/trigger_description.cpp
Labels: bug

#6026 [CBRD-25934] Backport from develop to 10.2 - Skip errors due to ownership change in unloaddb.
  src/object/authenticate.c
Labels: backport

#6045 [CBRD-25737] Add user schema to SELECT NEXT_VALUE statement
  src/executables/unload_schema.c
Labels: backport

#6048 [CBRD-25980] Prepared Statement error for TIME values ​​starting with '13:'
  src/communication/network_interface_cl.c
Labels: bug, regression

#6043 [CBRD-25358] Revert: backport: error handling when using for update clause for inline view (#5882)
  src/parser/name_resolution.c
Labels: revert

#6047 [CBRD-25358] rev (no error for system class): error handling when using for update clause for inline view
  src/parser/name_resolution.c
  src/parser/view_transform.c
Labels: enhancement, task

#6061 [CBRD-25985] memory leak at cubscan::method::scanner::init()
  src/query/scan_manager.c
Labels: bug, regression, legacy

#5978 [CBRD-25480] Backport from develop to 10.2 - When an error occurs in loaddb, it does not stop and continues execution.
  src/loaddb/load_db.c
Labels: backport

#6064 [CBRD-25922] rev: DBLink Auto-commit OFF Handling
  src/connection/connection_defs.h
  src/query/dblink_scan.c
  src/query/dblink_scan.h
  src/query/query_executor.c
  src/query/query_manager.c
  src/query/query_manager.h
  src/query/scan_manager.c
  src/thread/thread_entry.cpp
  src/thread/thread_entry.hpp
  src/transaction/transaction_sr.c
Labels: regression

#6063 [CBRD-25996] max_query_per_tran=1 does not apply in PL/CSQL SP.
  src/query/query_manager.c
Labels: bug, legacy
