Repository CUBRID/cubrid, pull requests merged in 2025-02, with the labels that each got.

#5839 [CBRD-25713] rev for pl: limit max length of CHAR type to 2048
  pl_engine/pl_server/src/main/java/com/cubrid/plcsql/compiler/type/TypeChar.java
Labels: task

#5838 [CBRD-25854] result-cache enable 환경에서 DML 사용 시 memory leak 발생
  src/query/query_manager.c
  src/transaction/locator_sr.c
Labels: bug, legacy

#5841 [CBRD-25854] result-cache enable 환경에서 DML 사용 시 memory leak 발생 (#5838)
  src/query/query_manager.c
  src/transaction/locator_sr.c
Labels: bug, backport

#5857 [CBRD-25873] SP Function의 NUMERIC 리턴 사이즈를 System Parameter로 설정
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/parser/type_checking.c
  src/parser/xasl_generation.c
Labels: enhancement, task

#5898 [CBRD-25903] Hide password when writing logs to cubrid_utiliity.log
  src/base/util_func.c
  src/base/util_func.h
  src/cm_common/cm_utils.c
  src/executables/util_service.c
Labels: task

#5962 [CBRD-25454] performance enhancement at TRACE ON (#5313)
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/perf_monitor.c
  src/base/tsc_timer.c
  src/base/tsc_timer.h
  util/CMakeLists.txt
Labels: backport

#5963 [CBRD-25454] performance enhancement at TRACE ON (#5313)
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/perf_monitor.c
  src/base/tsc_timer.c
  src/base/tsc_timer.h
  util/CMakeLists.txt
Labels: backport

#5947 [CBRD-25944] Differences in results related to time zone when using user-defined variables in the time_format function
  src/query/string_opfunc.c
Labels: bug
