Repository CUBRID/cubrid, pull requests merged in 2025-07, with the labels that each got.

#6306 [CBRD-26169] fix condition for assert()
  src/query/execute_statement.c
Labels: bug

#6324 [CBRD-26189] Core dump occurs when inserting integer into ENUM column in UTF-8 charset environment
  src/object/object_representation.c
  src/parser/type_checking.c
Labels: bug, regression, legacy

#6327 [CBRD-26190] remove code using cnvlex
  src/base/adjustable_array.c
  src/base/adjustable_array.h
  src/base/condition_handler.c
  src/base/condition_handler.h
  src/base/condition_handler_code.h
  src/compat/cnv.c
  src/compat/cnv.h
  src/compat/cnverr.h
  src/compat/cnvlex.c
  src/compat/cnvlex.h
  src/compat/db_macro.c
  src/compat/dbtype.h
  src/compat/dbtype_function.h
  src/thread/thread_entry.cpp
  src/thread/thread_entry.hpp
  src/transaction/boot_cl.c
Labels: refactoring

#6346 [CBRD-26190] Delete code related to ENABLE_USE_CNVLEX define and erase unnecessary files
  cs/CMakeLists.txt
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/adjustable_array.c
  src/base/adjustable_array.h
  src/base/condition_handler.c
  src/base/condition_handler.h
  src/base/condition_handler_code.h
  src/base/condition_handler_err.h
  src/compat/cnv.c
  src/compat/cnv.h
  src/compat/cnverr.h
  src/compat/cnvlex.c
  src/compat/cnvlex.h
  src/compat/cnvlex.l
  src/compat/db_macro.c
  src/compat/dbtype.h
  src/compat/dbtype_function.h
  src/thread/thread_entry.cpp
  src/thread/thread_entry.hpp
  src/transaction/boot_cl.c
Labels: refactoring
