Repository CUBRID/cubrid, pull requests merged in 2025-08, with the labels that each got.

#6289 [CBRD-26150] change DWB files to cpp extension.
  cubrid/CMakeLists.txt
  sa/CMakeLists.txt
  src/base/system_parameter.c
  src/storage/disk_manager.c
  src/storage/double_write_buffer.cpp
  src/storage/double_write_buffer.hpp
  src/storage/file_io.c
  src/storage/page_buffer.c
  src/transaction/boot_sr.c
  src/transaction/log_page_buffer.c
Labels: refactoring

#6364 [CBRD-26220] Refactoring the structures and related code that handle system parameters.
  src/base/system_parameter.c
  src/base/system_parameter.h
  src/broker/cas_execute.c
  src/compat/db_admin.c
Labels: refactoring

#6389 [CBRD-24130] Exclude view related statement in object file of unloaddb utility (#3259)
  src/executables/unload_object.c
Labels: backport

#6373 [CBRD-26231] Core dump occurs when processing like_match_lower_bound in a UTF-8 charset environment.
  src/base/intl_support.c
Labels: bug, legacy

#6393 [CBRD-25765] Refactor system catalog function namings
  src/executables/unload_object.c
  src/object/authenticate_access_user.cpp
  src/object/schema_manager.c
  src/object/schema_system_catalog.cpp
  src/object/schema_system_catalog_constants.h
  src/object/schema_system_catalog_install.cpp
  src/object/schema_system_catalog_install.hpp
  src/object/schema_system_catalog_install_query_spec.cpp
  src/object/trigger_manager.c
  src/query/execute_statement.c
  src/storage/oid.c
  src/transaction/boot_cl.c
Labels: refactoring
